# Supplemental informal, online, and gaming words not reliably found in
# standard dictionaries.  These are unioned with the english-words base set.

SLANG_WORDS: frozenset = frozenset({
    # Informal spoken / written contractions
    "gonna", "wanna", "gotta", "kinda", "sorta", "lotta", "outta",
    "dunno", "gimme", "lemme", "tho", "thru", "nite",
    "yep", "yup", "nope", "yall", "yer", "cuz", "cos",
    # Internet / gaming
    "noob", "noobs", "nub", "nubs", "pwn", "pwned", "pwning",
    "gank", "ganked", "ganking", "ganks",
    "nerf", "nerfed", "nerfing", "nerfs",
    "buff", "buffed", "buffing", "buffs",
    "grind", "grinding", "grinds",
    "loot", "looted", "looting", "loots",
    "glitch", "glitched", "glitching", "glitches",
    "modded", "modding",
    "devs",
    "meme", "memes", "memed", "meming",
    "troll", "trolled", "trolling", "trolls",
    "spam", "spammed", "spamming",
    "selfie", "selfies",
    "emoji", "emojis",
    "noob",
    "lagged", "lagging", "lags",
    "streamer", "streamers", "streaming",
    "gamer", "gamers", "gaming",
    # Modern slang
    "yeet", "yeeted", "yeeting", "yeets",
    "slay", "slayed", "slaying",
    "vibe", "vibes", "vibing", "vibed",
    "stan", "stans", "stanning", "stanned",
    "cringe", "cringey", "cringed",
    "bussin",
    "lowkey", "highkey",
    "bruh", "bro", "bros", "sis", "fam", "bestie", "besties",
    "sus", "pog", "poggers", "kek",
    "goated", "rizz", "rizzed",
    "hyped", "hype",
    "clutched", "clutching",
    "flexed", "flexing",
    "owned", "owns",
    "dude", "dudes",
    "babe", "babes",
    "chilling", "chillin",
    # Tech / social
    "tweet", "tweets", "tweeted", "tweeting",
    "retweet", "retweets", "retweeted",
    "texting", "texted",
    "wifi", "hotspot",
    "hashtag", "hashtags",
    "podcast", "podcasts", "podcasting",
    "blogging", "blogger", "bloggers",
    "streamed",
    "viral",
    "collab", "collabs", "collabing",
    "unfriend", "unfriended", "unfriending",
    "unfollow", "unfollowed", "unfollowing",
})
