# People data for retardguesser game
# 650 entries — generated in batches; do not edit manually
# Bios deliberately omit the subject's first and last name.

PEOPLE = {
    "Jesus Christ": {
        "name": "Jesus Christ",
        "profession": "religious figure",
        "bio": "Born in Bethlehem and raised in Nazareth, widely regarded as the central figure of Christianity and the Son of God by believers. His teachings on love, forgiveness, and salvation are recorded in the four Gospels of the New Testament. Crucified under Roman governor Pontius Pilate around 30–33 AD, with billions believing he rose from the dead three days later.",
        "known_for": "Sermon on the Mount, crucifixion and resurrection, founding of Christianity, the Lord's Prayer",
    },
    "Muhammad": {
        "name": "Muhammad",
        "profession": "Islamic prophet",
        "bio": "Born in Mecca around 570 AD, he is regarded as the founder of Islam and the last prophet of God in Islamic tradition. He received divine revelations later compiled into the Quran, the holy book of Islam. He united the Arabian Peninsula under the new faith before his death in 632 AD.",
        "known_for": "founding of Islam, the Quran, Night Journey (Isra and Mi'raj), Hijra to Medina",
    },
    "William Shakespeare": {
        "name": "William Shakespeare",
        "profession": "playwright",
        "bio": "An English playwright and poet born in Stratford-upon-Avon in 1564, widely considered the greatest writer in the English language. He produced 37 plays and 154 sonnets that remain central to the literary canon. His works have been translated into every major language and are performed more often than those of any other playwright in history.",
        "known_for": "Hamlet, Romeo and Juliet, Macbeth, A Midsummer Night's Dream",
    },
    "Albert Einstein": {
        "name": "Albert Einstein",
        "profession": "physicist",
        "bio": "A German-born physicist who developed the theory of relativity, one of the two pillars of modern physics. His mass-energy equivalence formula E=mc² has become the world's most famous equation. He received the Nobel Prize in Physics in 1921 for his discovery of the law of the photoelectric effect.",
        "known_for": "theory of relativity, E=mc², Nobel Prize in Physics, general relativity",
    },
    "Abraham Lincoln": {
        "name": "Abraham Lincoln",
        "profession": "U.S. president",
        "bio": "The 16th President of the United States, he led the nation through the Civil War and worked to preserve the Union. He issued the Emancipation Proclamation in 1863, declaring enslaved people in Confederate states to be free. He was assassinated by John Wilkes Booth at Ford's Theatre in Washington, D.C. in 1865.",
        "known_for": "Emancipation Proclamation, Civil War leadership, Gettysburg Address, assassination at Ford's Theatre",
    },
    "George Washington": {
        "name": "George Washington",
        "profession": "founding father",
        "bio": "The commander-in-chief of the Continental Army during the American Revolutionary War, he led the colonies to victory against Britain. He served as the first President of the United States from 1789 to 1797 and is often called the Father of His Country. He set a key precedent by voluntarily stepping down from power after two terms.",
        "known_for": "American Revolutionary War, first U.S. president, crossing the Delaware, Mount Vernon",
    },
    "Adolf Hitler": {
        "name": "Adolf Hitler",
        "profession": "dictator",
        "bio": "An Austrian-born politician who rose to power as Chancellor and then Führer of Germany in the 1930s, leading the Nazi Party. He initiated World War II in Europe and oversaw the Holocaust, in which approximately six million Jews and millions of others were systematically murdered. He died by suicide in Berlin in April 1945 as Allied forces closed in.",
        "known_for": "World War II, the Holocaust, Nazi Party, Mein Kampf",
    },
    "Buddha (Siddhartha Gautama)": {
        "name": "Buddha (Siddhartha Gautama)",
        "profession": "spiritual teacher",
        "bio": "Born a prince in what is now Nepal around 563 BCE, he renounced his privileged life to seek the end of human suffering. After years of meditation he achieved spiritual awakening under the Bodhi tree and spent the rest of his life teaching the path to liberation. His teachings form the foundation of Buddhism, one of the world's major religions.",
        "known_for": "founding of Buddhism, Four Noble Truths, Eightfold Path, achieving enlightenment",
    },
    "Martin Luther King Jr.": {
        "name": "Martin Luther King Jr.",
        "profession": "civil rights leader",
        "bio": "An American Baptist minister and activist who became the most prominent leader of the U.S. civil rights movement, advocating for nonviolent resistance inspired by Gandhi. He delivered the iconic 'I Have a Dream' speech at the 1963 March on Washington. He was assassinated in Memphis, Tennessee in 1968 at the age of 39.",
        "known_for": "'I Have a Dream' speech, March on Washington, Nobel Peace Prize, Montgomery Bus Boycott",
    },
    "Napoleon Bonaparte": {
        "name": "Napoleon Bonaparte",
        "profession": "emperor",
        "bio": "A French military genius who rose to prominence during the French Revolution and conquered much of Europe as Emperor of the French from 1804 to 1814. He implemented sweeping legal reforms known as the Napoleonic Code that influenced legal systems across the world. He was ultimately defeated at the Battle of Waterloo and died in exile on the remote island of Saint Helena.",
        "known_for": "Battle of Waterloo, Napoleonic Code, conquering Europe, exile to Saint Helena",
    },
    "Leonardo da Vinci": {
        "name": "Leonardo da Vinci",
        "profession": "Renaissance polymath",
        "bio": "An Italian painter, scientist, and inventor of the 15th and 16th centuries, widely regarded as one of the greatest painters of all time and perhaps the most diversely talented person who ever lived. His notebooks contain discoveries in anatomy, astronomy, and engineering that were centuries ahead of their time. He is the archetype of the Renaissance man.",
        "known_for": "Mona Lisa, The Last Supper, Vitruvian Man, scientific notebooks",
    },
    "Isaac Newton": {
        "name": "Isaac Newton",
        "profession": "physicist",
        "bio": "An English mathematician and physicist born in 1643, widely regarded as one of the most influential scientists of all time. He formulated the laws of motion and universal gravitation, laying the foundations for classical mechanics, and independently developed calculus. His landmark work Principia Mathematica transformed our understanding of the physical world.",
        "known_for": "laws of motion, law of universal gravitation, development of calculus, Principia Mathematica",
    },
    "Julius Caesar": {
        "name": "Julius Caesar",
        "profession": "Roman general",
        "bio": "A Roman general and statesman who played a critical role in the transformation of the Roman Republic into the Roman Empire. His conquest of Gaul extended Roman territory to the English Channel, and he was the first Roman general to cross both the Rhine and the English Channel. He was assassinated by a group of senators on the Ides of March, 44 BCE.",
        "known_for": "conquest of Gaul, crossing the Rubicon, assassination on the Ides of March, Gallic Wars",
    },
    "Winston Churchill": {
        "name": "Winston Churchill",
        "profession": "prime minister",
        "bio": "A British statesman who served as Prime Minister of the United Kingdom during World War II, rallying the nation against Nazi Germany with powerful speeches and resolute leadership. He was also a Nobel Prize-winning author and a gifted amateur painter. His wartime oratory, including 'We shall fight on the beaches,' remains iconic to this day.",
        "known_for": "WWII leadership, 'We shall fight on the beaches' speech, Nobel Prize in Literature, Iron Curtain speech",
    },
    "Queen Elizabeth II": {
        "name": "Queen Elizabeth II",
        "profession": "British monarch",
        "bio": "The longest-reigning British monarch in history, she ascended to the throne in 1952 following the death of her father and reigned for 70 years until her death in September 2022. She served as head of state for the United Kingdom and the Commonwealth realms through enormous social and political change. During her reign she met with 13 of the 14 U.S. presidents who served alongside her.",
        "known_for": "longest British reign, Commonwealth leadership, Platinum Jubilee, 70-year reign",
    },
    "Charles Darwin": {
        "name": "Charles Darwin",
        "profession": "naturalist",
        "bio": "An English naturalist and geologist who developed the theory of evolution by natural selection after years of research, including a pivotal voyage aboard HMS Beagle. He published his findings in On the Origin of Species in 1859, fundamentally changing how humans understand the natural world. His ideas remain the foundation of modern evolutionary biology.",
        "known_for": "theory of evolution, On the Origin of Species, voyage of the Beagle, natural selection",
    },
    "Mahatma Gandhi": {
        "name": "Mahatma Gandhi",
        "profession": "independence leader",
        "bio": "An Indian lawyer and activist who became the principal leader of India's independence movement against British colonial rule, championing nonviolent civil disobedience. His philosophy of satyagraha (truth-force) inspired civil rights movements around the world. He was assassinated in January 1948 by a Hindu nationalist, just months after India achieved independence.",
        "known_for": "Indian independence movement, Salt March, nonviolent civil disobedience, assassination in 1948",
    },
    "Alexander the Great": {
        "name": "Alexander the Great",
        "profession": "conqueror",
        "bio": "A king of Macedon who created one of the largest empires in ancient history — stretching from Greece to northwestern India — before the age of 33. Tutored by Aristotle as a boy, he proved to be a brilliant military strategist who never lost a battle. His campaigns spread Greek culture and language across the ancient world in what became the Hellenistic period.",
        "known_for": "conquering Persia and Egypt, founding Alexandria, Battle of Gaugamela, Hellenistic spread of culture",
    },
    "Christopher Columbus": {
        "name": "Christopher Columbus",
        "profession": "explorer",
        "bio": "An Italian explorer sailing under the Spanish crown who completed four voyages across the Atlantic Ocean, opening sustained contact between Europe and the Americas. Though not the first European to reach the New World, his 1492 arrival in the Caribbean is considered a turning point in world history. His voyages initiated the widespread colonization of the Americas.",
        "known_for": "1492 voyage to the Americas, opening the New World, four Atlantic voyages, Columbian Exchange",
    },
    "Mother Teresa": {
        "name": "Mother Teresa",
        "profession": "humanitarian",
        "bio": "An Albanian-Indian Roman Catholic nun who founded the Missionaries of Charity in Calcutta, India in 1950. She devoted her life to caring for the sick, dying, and destitute, establishing hospices and homes across the world. She received the Nobel Peace Prize in 1979 and was canonized as a saint by the Catholic Church in 2016.",
        "known_for": "Missionaries of Charity, Nobel Peace Prize, canonization as saint, work with the poorest of the poor",
    },
    "Plato": {
        "name": "Plato",
        "profession": "ancient philosopher",
        "bio": "An ancient Greek philosopher and student of Socrates who founded the Academy in Athens, one of the earliest institutions of higher learning in the Western world. His philosophical dialogues have been studied for over two millennia and cover topics from justice and beauty to the nature of reality. He is one of the most important figures in the development of Western philosophy.",
        "known_for": "The Republic, Theory of Forms, founding the Academy, philosophical dialogues",
    },
    "Socrates": {
        "name": "Socrates",
        "profession": "ancient philosopher",
        "bio": "An ancient Greek philosopher considered one of the founders of Western philosophy, known for developing the Socratic method of inquiry through questioning. He wrote nothing himself; his ideas survive through the writings of his students, chiefly Plato. He was tried and executed by Athens for allegedly corrupting the youth and impiety, choosing to drink hemlock rather than flee.",
        "known_for": "Socratic method, trial and execution by hemlock, influence on Plato, 'Know thyself'",
    },
    "Karl Marx": {
        "name": "Karl Marx",
        "profession": "political philosopher",
        "bio": "A German philosopher, economist, and revolutionary whose theories about capitalism, class struggle, and historical materialism formed the basis of Marxism and communism. He co-authored The Communist Manifesto with Friedrich Engels in 1848 and spent years producing his landmark work Das Kapital. His ideas profoundly shaped the development of the Soviet Union, China, and other communist states.",
        "known_for": "The Communist Manifesto, Das Kapital, founding of Marxism, critique of capitalism",
    },
    "Benjamin Franklin": {
        "name": "Benjamin Franklin",
        "profession": "founding father",
        "bio": "An American statesman, scientist, and inventor who was one of the Founding Fathers of the United States, helping draft both the Declaration of Independence and the Constitution. His electrical experiments, including the famous kite experiment, led to the invention of the lightning rod. He also founded the first public lending library and the first fire department in America.",
        "known_for": "electricity experiments, Poor Richard's Almanack, Founding Father, bifocals invention",
    },
    "Thomas Jefferson": {
        "name": "Thomas Jefferson",
        "profession": "founding father",
        "bio": "The principal author of the Declaration of Independence and the third President of the United States, serving from 1801 to 1809. He orchestrated the Louisiana Purchase in 1803, effectively doubling the size of the United States. He was also a noted architect, inventor, and founder of the University of Virginia.",
        "known_for": "Declaration of Independence, Louisiana Purchase, third U.S. president, founding University of Virginia",
    },
    "John F. Kennedy": {
        "name": "John F. Kennedy",
        "profession": "U.S. president",
        "bio": "The 35th President of the United States and the youngest person ever elected to the office. He navigated the Cuban Missile Crisis in 1962, bringing the world back from the brink of nuclear war. He was assassinated in Dallas, Texas on November 22, 1963, in one of the most shocking events in American history.",
        "known_for": "Cuban Missile Crisis, assassination in Dallas, moon-shot speech, 'Ask not what your country can do for you'",
    },
    "Nelson Mandela": {
        "name": "Nelson Mandela",
        "profession": "anti-apartheid leader",
        "bio": "A South African anti-apartheid activist who spent 27 years in prison for his opposition to the apartheid regime. After his release he negotiated the end of apartheid and became South Africa's first democratically elected president, serving from 1994 to 1999. He received the Nobel Peace Prize in 1993 and became a global symbol of justice and reconciliation.",
        "known_for": "ending apartheid, 27 years in prison, first South African democratic president, Nobel Peace Prize",
    },
    "Franklin D. Roosevelt": {
        "name": "Franklin D. Roosevelt",
        "profession": "U.S. president",
        "bio": "The 32nd President of the United States, serving a record four terms from 1933 to 1945 through the Great Depression and World War II. He implemented the New Deal, a sweeping series of programs providing relief, recovery, and reform after the economic crisis. The only U.S. president to serve more than two terms, he died in office in April 1945 just weeks before Germany's surrender.",
        "known_for": "New Deal, four presidential terms, leading the U.S. through WWII, overcoming polio",
    },
    "Galileo Galilei": {
        "name": "Galileo Galilei",
        "profession": "astronomer",
        "bio": "An Italian astronomer, physicist, and engineer often called the father of modern science for his pioneering use of the telescope to observe the heavens. His support for the heliocentric model of the solar system brought him into conflict with the Catholic Church, which forced him to recant under threat of torture. He spent the remainder of his life under house arrest.",
        "known_for": "telescope observations, supporting heliocentrism, conflict with the Catholic Church, laws of falling bodies",
    },
    "Sigmund Freud": {
        "name": "Sigmund Freud",
        "profession": "psychoanalyst",
        "bio": "An Austrian neurologist and founder of psychoanalysis, a clinical method for treating psychopathology through dialogue between patient and analyst. He developed influential theories about the unconscious mind, dream interpretation, and the Oedipus complex. Though many of his specific ideas have been superseded, he profoundly shaped 20th-century culture, literature, and thought.",
        "known_for": "founding psychoanalysis, The Interpretation of Dreams, Oedipus complex, theory of the unconscious",
    },
    "Elvis Presley": {
        "name": "Elvis Presley",
        "profession": "rock singer",
        "bio": "Known as the King of Rock and Roll, he is one of the most culturally influential musicians of the 20th century, blending country, rhythm and blues, and gospel into a revolutionary new sound. His energetic performances and good looks made him a global icon in the 1950s. He died at his Graceland estate in Memphis in 1977 at age 42.",
        "known_for": "'Hound Dog', 'Jailhouse Rock', Graceland, Las Vegas residency",
    },
    "Marilyn Monroe": {
        "name": "Marilyn Monroe",
        "profession": "actress",
        "bio": "An American actress, model, and singer who became one of the most recognizable pop culture icons of the 20th century. She rose from a difficult childhood in foster care to become one of Hollywood's biggest stars, excelling in comedic roles. She died of a barbiturate overdose in 1962 at age 36, and her image continues to define an era of Hollywood glamour.",
        "known_for": "'Some Like It Hot', 'Gentlemen Prefer Blondes', JFK birthday serenade, iconic white dress photo",
    },
    "Pablo Picasso": {
        "name": "Pablo Picasso",
        "profession": "artist",
        "bio": "A Spanish painter, sculptor, and printmaker who co-founded the Cubist movement and is widely regarded as one of the most influential artists of the 20th century. Over his long career he created approximately 20,000 works including paintings, sculptures, ceramics, and prints. His anti-war masterpiece Guernica is considered one of the most powerful political statements in modern art.",
        "known_for": "Guernica, Cubism, Les Demoiselles d'Avignon, prolific and diverse output",
    },
    "Ludwig van Beethoven": {
        "name": "Ludwig van Beethoven",
        "profession": "composer",
        "bio": "A German composer and pianist who bridged the Classical and Romantic eras of Western music. Despite becoming completely deaf in his later years, he continued to compose some of his most celebrated works, including his Ninth Symphony. His nine symphonies, five piano concertos, and string quartets remain among the most performed pieces in the classical repertoire.",
        "known_for": "Ninth Symphony ('Ode to Joy'), Moonlight Sonata, composing while deaf, Fifth Symphony",
    },
    "Mozart": {
        "name": "Mozart",
        "profession": "composer",
        "bio": "An Austrian prodigy who began composing at age five and produced over 800 works during his short 35-year life. Widely regarded as one of the greatest composers in the history of Western music, he achieved an unmatched range across virtually every genre of his era. He died in poverty in Vienna in 1791 and was buried in an unmarked grave.",
        "known_for": "The Magic Flute, Don Giovanni, Symphony No. 40, Requiem Mass in D minor",
    },
    "Genghis Khan": {
        "name": "Genghis Khan",
        "profession": "conqueror",
        "bio": "Born Temüjin around 1162, he united the Mongol tribes and founded the Mongol Empire, the largest contiguous land empire in history. His military campaigns were characterized by ruthless efficiency and resulted in the deaths of tens of millions of people. By his death in 1227 he had conquered much of Central Asia, China, and Persia.",
        "known_for": "Mongol Empire, conquering Central Asia and China, Mongolian unification, Pax Mongolica",
    },
    "Joseph Stalin": {
        "name": "Joseph Stalin",
        "profession": "Soviet dictator",
        "bio": "A Georgian revolutionary who became leader of the Soviet Union after Lenin's death, ruling from the mid-1920s until his death in 1953. His forced industrialization and collectivization policies led to the deaths of millions through famine and forced labor. He led the Soviet Union through World War II but maintained a totalitarian police state marked by mass purges and the gulag system.",
        "known_for": "Soviet industrialization, Great Purge, WWII leadership, gulag system",
    },
    "Vladimir Lenin": {
        "name": "Vladimir Lenin",
        "profession": "revolutionary",
        "bio": "A Russian revolutionary and political theorist who led the Bolshevik Revolution of October 1917, overthrowing the provisional government and establishing the world's first communist state. As head of the new Soviet government he navigated the brutal Russian Civil War and implemented a radical socialist economic policy. His embalmed body remains on public display in Moscow's Red Square.",
        "known_for": "Bolshevik Revolution, founding the Soviet Union, 'What Is to Be Done?', New Economic Policy",
    },
    "Steve Jobs": {
        "name": "Steve Jobs",
        "profession": "tech entrepreneur",
        "bio": "An American business magnate who co-founded Apple Inc. and transformed the personal computer, animated film, music, and smartphone industries. After being ousted from Apple in 1985 he returned in 1997 and led the company to become one of the most valuable in the world. He died of pancreatic cancer in 2011, leaving a legacy as one of the most innovative figures in technology history.",
        "known_for": "iPhone, Mac computer, Pixar Studios, 'one more thing' product launches",
    },
    "Bill Gates": {
        "name": "Bill Gates",
        "profession": "tech billionaire",
        "bio": "An American business magnate and philanthropist who co-founded Microsoft and helped transform the personal computer industry by developing software for IBM-compatible PCs. He was the world's wealthiest person for much of the 1990s and 2000s. Through the Bill & Melinda Gates Foundation he has committed tens of billions of dollars to fighting disease and poverty worldwide.",
        "known_for": "founding Microsoft, Windows operating system, Bill & Melinda Gates Foundation, philanthropic work",
    },
    "Michael Jackson": {
        "name": "Michael Jackson",
        "profession": "pop singer",
        "bio": "Known as the King of Pop, he became one of the most commercially successful entertainers in history, transforming the music video into an art form with groundbreaking clips like 'Thriller.' His career began as a child with the Jackson 5 and reached its apex with Thriller, which remains the best-selling album of all time. He died of acute propofol intoxication in 2009 at age 50.",
        "known_for": "Thriller album, moonwalk, 'Billie Jean', child sexual abuse allegations",
    },
    "Taylor Swift": {
        "name": "Taylor Swift",
        "profession": "pop singer",
        "bio": "An American singer-songwriter who began as a country teen sensation and grew into one of the best-selling music artists of all time. Known for writing autobiographical songs about her personal life, she holds the record for the most Grammy Awards won by any artist. Her Eras Tour became the highest-grossing concert tour in history.",
        "known_for": "'Shake It Off', 'Love Story', Eras Tour, re-recording her albums (Taylor's Version)",
    },
    "Oprah Winfrey": {
        "name": "Oprah Winfrey",
        "profession": "TV host",
        "bio": "An American television host, actress, and media mogul who ran the highest-rated daytime talk show in American history for 25 seasons. She overcame a deeply difficult childhood in poverty to become one of the wealthiest and most influential women in the world. Her book club recommendations became a cultural phenomenon, turning selected titles into instant bestsellers.",
        "known_for": "The Oprah Winfrey Show, Oprah's Book Club, 'You get a car!' giveaway, OWN Network",
    },
    "Barack Obama": {
        "name": "Barack Obama",
        "profession": "U.S. president",
        "bio": "The 44th President of the United States and the first African American to hold that office, serving from 2009 to 2017. He signed the Affordable Care Act into law, ended the U.S. combat mission in Iraq, and ordered the operation that resulted in the death of Osama bin Laden. He was awarded the Nobel Peace Prize in 2009, just nine months into his first term.",
        "known_for": "first Black U.S. president, Affordable Care Act, Nobel Peace Prize, killing of Osama bin Laden",
    },
    "Donald Trump": {
        "name": "Donald Trump",
        "profession": "U.S. president",
        "bio": "An American real estate mogul and television personality who served as the 45th and 47th President of the United States. As president he pursued aggressive trade policies, large tax cuts, and a hardline stance on immigration. He was impeached twice by the House of Representatives and became the first U.S. president to be convicted of felony crimes.",
        "known_for": "'Make America Great Again', two impeachments, felony conviction, 'The Apprentice' TV show",
    },
    "Muhammad Ali": {
        "name": "Muhammad Ali",
        "profession": "boxer",
        "bio": "An American professional boxer widely regarded as the greatest heavyweight of all time, known for his exceptional speed, power, and psychological tactics in the ring. He was stripped of his heavyweight title in 1967 for refusing induction into the U.S. military on religious grounds, a stance that defined him as a symbol of conscience. He later reclaimed the title with legendary bouts nicknamed the 'Rumble in the Jungle' and the 'Thrilla in Manila.'",
        "known_for": "'Rumble in the Jungle', 'Thrilla in Manila', conscientious objector to Vietnam, 'Float like a butterfly, sting like a bee'",
    },
    "Michael Jordan": {
        "name": "Michael Jordan",
        "profession": "basketball player",
        "bio": "An American former professional basketball player who played primarily for the Chicago Bulls and is widely considered the greatest basketball player of all time. He led the Bulls to six NBA championships in the 1990s, winning the Finals MVP award each time. His global celebrity and Air Jordan brand permanently transformed the business of sports marketing.",
        "known_for": "six NBA championships, Air Jordan sneakers, 'Space Jam', 'The Last Dance' documentary",
    },
    "LeBron James": {
        "name": "LeBron James",
        "profession": "basketball player",
        "bio": "An American professional basketball player frequently cited alongside Michael Jordan as the greatest of all time. He has won four NBA championships with three different franchises and holds the NBA all-time scoring record. He is one of the first active athletes to own a stake in a major professional sports franchise and is widely recognized for his social justice advocacy.",
        "known_for": "four NBA championships, NBA all-time scoring record, 'The Decision', social activism",
    },
    "Beyoncé": {
        "name": "Beyoncé",
        "profession": "pop singer",
        "bio": "An American singer, songwriter, and actress who rose to fame as the lead vocalist of Destiny's Child before launching one of the most successful solo careers in music history. She holds the record for the most Grammy Awards won by any artist and is considered one of the defining entertainers of her generation. Her visual album Lemonade and her Renaissance album are regarded as landmark works in contemporary music.",
        "known_for": "Lemonade album, Destiny's Child, Grammy record holder, Coachella 2018 performance",
    },
    "Madonna": {
        "name": "Madonna",
        "profession": "pop singer",
        "bio": "An American singer, songwriter, and actress who dominated pop culture in the 1980s and is often called the Queen of Pop. She has continuously reinvented her image and pushed the boundaries of artistic expression in music and video across five decades. With estimated sales of over 300 million records worldwide, she is one of the best-selling music artists in history.",
        "known_for": "'Like a Virgin', 'Material Girl', Blonde Ambition Tour, constantly reinventing her image",
    },
    "Pelé": {
        "name": "Pelé",
        "profession": "soccer player",
        "bio": "A Brazilian football legend widely regarded as the greatest player in the history of the sport. He won three FIFA World Cup titles with Brazil in 1958, 1962, and 1970, scoring over 1,000 career goals. He remains the only footballer to have won three World Cups.",
        "known_for": "three World Cup titles, 1,000 career goals, Santos FC, Brazil national team",
    },
    "Diego Maradona": {
        "name": "Diego Maradona",
        "profession": "soccer player",
        "bio": "An Argentine football icon considered one of the greatest players of all time, famous for his extraordinary dribbling ability and vision on the pitch. He led Argentina to the 1986 FIFA World Cup title and scored the infamous 'Hand of God' goal against England. He spent his peak club years at Napoli, where he led them to their first-ever league titles.",
        "known_for": "1986 World Cup, Hand of God goal, Goal of the Century, Napoli",
    },
    "Frida Kahlo": {
        "name": "Frida Kahlo",
        "profession": "painter",
        "bio": "A Mexican artist known for her deeply personal and symbolically rich self-portraits, many of which reflect physical and emotional pain. She suffered a near-fatal bus accident at age 18 that left her with lifelong injuries and inspired much of her artwork. Her work blends realism with surrealism and Mexican folk art and gained international recognition after her death.",
        "known_for": "self-portraits, The Two Fridas, Mexican folk art style, feminist icon",
    },
    "Andy Warhol": {
        "name": "Andy Warhol",
        "profession": "pop artist",
        "bio": "An American artist and leading figure of the pop art movement who blurred the boundary between fine art and commercial culture. He became famous for silkscreen paintings of everyday consumer goods and celebrities, created at his New York studio known as 'The Factory'. His work challenged traditional notions of what constitutes art.",
        "known_for": "Campbell's Soup Cans, Marilyn Monroe prints, The Factory, pop art movement",
    },
    "Salvador Dalí": {
        "name": "Salvador Dalí",
        "profession": "surrealist painter",
        "bio": "A Spanish surrealist artist celebrated for his bizarre dreamlike imagery and meticulous technical skill. He was deeply influenced by Freud's theories on the unconscious mind and incorporated psychoanalytic elements into his work. His eccentric public persona was as famous as his paintings.",
        "known_for": "The Persistence of Memory, surrealism, melting clocks, eccentric persona",
    },
    "J.R.R. Tolkien": {
        "name": "J.R.R. Tolkien",
        "profession": "fantasy author",
        "bio": "A British author, poet, and philologist who created the beloved fantasy world of Middle-earth in a series of novels that have sold over 150 million copies. He was a professor at Oxford University and drew on Norse mythology, Old English literature, and his own invented languages to build an extraordinarily detailed fictional universe. His books were adapted into some of the highest-grossing film trilogies in cinema history.",
        "known_for": "The Lord of the Rings, The Hobbit, Middle-earth mythology, Elvish languages",
    },
    "George R.R. Martin": {
        "name": "George R.R. Martin",
        "profession": "fantasy author",
        "bio": "An American novelist and screenwriter best known for his epic fantasy series A Song of Ice and Fire, adapted into the massively popular HBO series Game of Thrones. He began writing science fiction and fantasy stories as a child and sold them to other kids for pennies. His morally complex characters and willingness to kill off major characters revolutionized popular fantasy fiction.",
        "known_for": "A Song of Ice and Fire, Game of Thrones, subverting fantasy tropes, Westeros",
    },
    "Steven Spielberg": {
        "name": "Steven Spielberg",
        "profession": "film director",
        "bio": "An American filmmaker widely considered one of the most influential directors in cinema history, having shaped the modern blockbuster era. He broke into film with a string of iconic hits across multiple genres after beginning his career in television. He has won three Academy Awards and directed some of the highest-grossing films of all time.",
        "known_for": "Jaws, E.T., Schindler's List, Indiana Jones series",
    },
    "Martin Scorsese": {
        "name": "Martin Scorsese",
        "profession": "film director",
        "bio": "An American film director, producer, and screenwriter regarded as one of the most significant filmmakers in cinema history. He is known for gritty portrayals of crime, violence, and moral ambiguity, often set against the backdrop of New York City. He has worked repeatedly with Robert De Niro and Leonardo DiCaprio, creating some of the most celebrated films of the past five decades.",
        "known_for": "Goodfellas, Taxi Driver, The Departed, Raging Bull",
    },
    "Alfred Hitchcock": {
        "name": "Alfred Hitchcock",
        "profession": "film director",
        "bio": "A British-American filmmaker known as the 'Master of Suspense' who pioneered many cinematic techniques now standard in thrillers. He directed over 50 feature films spanning six decades, developing a signature style involving psychological tension, dark humor, and unexpected plot twists. He is considered one of the greatest and most influential filmmakers of all time.",
        "known_for": "Psycho, Vertigo, Rear Window, North by Northwest",
    },
    "Stan Lee": {
        "name": "Stan Lee",
        "profession": "comic book writer",
        "bio": "An American comic book writer, editor, and publisher who co-created many of Marvel Comics' most beloved characters alongside artists Jack Kirby and Steve Ditko. He revolutionized the superhero genre by giving characters human flaws and personal problems alongside their powers. He became a beloved public figure famous for cameo appearances in Marvel film adaptations.",
        "known_for": "co-creating Spider-Man, Iron Man, the X-Men, Marvel Cinematic Universe cameos",
    },
    "Hayao Miyazaki": {
        "name": "Hayao Miyazaki",
        "profession": "anime director",
        "bio": "A Japanese animator, director, and co-founder of Studio Ghibli who is widely considered the greatest animation filmmaker of all time. His films are celebrated for their hand-drawn artistry, environmental themes, strong female protagonists, and a sense of wonder that appeals to all ages. He won the Academy Award for Best Animated Feature for Spirited Away.",
        "known_for": "Spirited Away, My Neighbor Totoro, Princess Mononoke, Studio Ghibli",
    },
    "Akira Kurosawa": {
        "name": "Akira Kurosawa",
        "profession": "film director",
        "bio": "A Japanese filmmaker widely considered one of the most important and influential directors in the history of cinema. His epic samurai films and humanist dramas profoundly shaped Western filmmakers including George Lucas, Francis Ford Coppola, and Steven Spielberg. He directed 30 films over more than five decades, ranging from historical epics to contemporary drama.",
        "known_for": "Seven Samurai, Rashomon, Ran, influence on Western cinema",
    },
    "Charlie Chaplin": {
        "name": "Charlie Chaplin",
        "profession": "comedian and filmmaker",
        "bio": "A British actor, filmmaker, and composer who rose to fame in the silent film era and became one of the most celebrated performers in history. His iconic 'Tramp' character — with bowler hat, cane, and toothbrush mustache — is one of the most recognized images in cinema. He wrote, directed, produced, and composed music for many of his films, demonstrating extraordinary creative range.",
        "known_for": "The Tramp character, Modern Times, The Great Dictator, silent film era",
    },
    "Frank Sinatra": {
        "name": "Frank Sinatra",
        "profession": "singer and actor",
        "bio": "An American singer and actor who became one of the most popular and influential musical artists of the 20th century, often called 'Ol' Blue Eyes'. He was a member of the Rat Pack, a group of entertainers who performed together in Las Vegas, and starred in numerous Hollywood films. His distinctive voice and phrasing influenced countless musicians across multiple generations.",
        "known_for": "'My Way', 'New York, New York', the Rat Pack, Capitol Records era",
    },
    "Aretha Franklin": {
        "name": "Aretha Franklin",
        "profession": "singer",
        "bio": "An American singer and songwriter often called the 'Queen of Soul' who is widely regarded as one of the greatest vocalists of all time. She recorded 112 charted singles including 17 number-one R&B singles during her career. She was the first woman inducted into the Rock and Roll Hall of Fame in 1987.",
        "known_for": "'Respect', '(You Make Me Feel Like) A Natural Woman', Queen of Soul, Rock and Roll Hall of Fame",
    },
    "Whitney Houston": {
        "name": "Whitney Houston",
        "profession": "singer",
        "bio": "An American singer and actress regarded as one of the greatest vocalists in history, known for her powerful and technically flawless voice. She achieved extraordinary commercial success in the 1980s and 1990s with a string of number-one hits and best-selling albums. Her rendition of 'I Will Always Love You' became one of the best-selling singles of all time.",
        "known_for": "'I Will Always Love You', 'I Wanna Dance with Somebody', The Bodyguard soundtrack, record-breaking album sales",
    },
    "Prince": {
        "name": "Prince",
        "profession": "musician",
        "bio": "An American singer, songwriter, musician, and record producer considered one of the most gifted and prolific artists in popular music history. He was a multi-instrumentalist who played dozens of instruments on his recordings and was known for his flamboyant stage presence and genre-defying music blending funk, rock, R&B, and pop. His 1984 film and album Purple Rain catapulted him to superstardom.",
        "known_for": "'Purple Rain', 'When Doves Cry', Minneapolis Sound, multi-instrumentalist virtuosity",
    },
    "David Bowie": {
        "name": "David Bowie",
        "profession": "rock musician",
        "bio": "A British rock musician, actor, and artist who was one of the most innovative and influential performers in rock history. He reinvented himself through a series of iconic personas — including Ziggy Stardust and the Thin White Duke — that shaped glam rock, new wave, and art rock. His final album Blackstar, released two days before his death in 2016, was critically acclaimed as a masterpiece.",
        "known_for": "Ziggy Stardust, 'Heroes', 'Let's Dance', Blackstar",
    },
    "Kurt Cobain": {
        "name": "Kurt Cobain",
        "profession": "rock musician",
        "bio": "An American singer, songwriter, and guitarist who was the lead vocalist and primary creative force behind the grunge band Nirvana. With the release of Nevermind in 1991, the band brought alternative rock into the mainstream and defined the sound of a generation. His death at age 27 made him an enduring symbol of creative genius and rock's dark mythology.",
        "known_for": "Nirvana, 'Smells Like Teen Spirit', Nevermind album, grunge movement",
    },
    "Jimi Hendrix": {
        "name": "Jimi Hendrix",
        "profession": "rock guitarist",
        "bio": "An American rock guitarist, singer, and songwriter widely considered the greatest electric guitarist in rock history. His flamboyant and innovative playing style incorporated distortion, feedback, and virtuosic technique in ways that transformed what the electric guitar could do. He headlined the Woodstock festival in 1969 and died at age 27, becoming one of the earliest members of the '27 Club'.",
        "known_for": "revolutionary guitar playing, 'Purple Haze', Woodstock performance, '27 Club'",
    },
    "Tupac Shakur": {
        "name": "Tupac Shakur",
        "profession": "rapper",
        "bio": "An American rapper, actor, and activist widely considered one of the greatest and most influential rappers of all time. His work addressed social issues including racism, poverty, and police brutality, bringing political consciousness to mainstream hip-hop. He was shot and killed in Las Vegas in 1996 at age 25 and has since sold over 75 million records worldwide.",
        "known_for": "'California Love', 'Dear Mama', All Eyez on Me album, social activism",
    },
    "The Notorious B.I.G.": {
        "name": "The Notorious B.I.G.",
        "profession": "rapper",
        "bio": "An American rapper from Brooklyn, New York, widely regarded as one of the greatest rappers of all time. Known for his smooth delivery, dark storytelling, and ability to switch between street narratives and introspective lyrics, he became the defining voice of East Coast hip-hop in the mid-1990s. He was murdered in a drive-by shooting in Los Angeles in 1997 at age 24.",
        "known_for": "'Juicy', 'Big Poppa', Ready to Die album, East Coast hip-hop",
    },
    "Snoop Dogg": {
        "name": "Snoop Dogg",
        "profession": "rapper",
        "bio": "An American rapper, media personality, and entrepreneur who rose to fame in 1992 on Dr. Dre's landmark album The Chronic and became one of the best-known figures in hip-hop. His laid-back delivery and distinctive voice made him instantly recognizable, and he has appeared in dozens of films and television shows. He lit the torch at the 2024 Paris Olympics, reflecting his status as a global cultural icon.",
        "known_for": "Doggystyle album, G-funk style, NBC Olympics coverage, 2024 Paris Olympics torch",
    },
    "Dr. Dre": {
        "name": "Dr. Dre",
        "profession": "rapper and producer",
        "bio": "An American rapper, record producer, and entrepreneur who is one of the most influential figures in hip-hop history. He co-founded Death Row Records and later Aftermath Entertainment, discovering and launching the careers of artists including Snoop Dogg, Eminem, and Kendrick Lamar. His headphone brand Beats Electronics was acquired by Apple in 2014 for $3 billion.",
        "known_for": "N.W.A., Beats Electronics, producing Eminem and Kendrick Lamar, The Chronic album",
    },
    "Celine Dion": {
        "name": "Celine Dion",
        "profession": "singer",
        "bio": "A Canadian singer widely regarded as one of the greatest vocalists of all time, known for her powerful voice and emotional ballads. She rose to international fame with the theme song for the 1997 film Titanic and has become one of the best-selling music artists in history. She has faced significant personal challenges in recent years, including the death of her husband and manager and a rare neurological condition.",
        "known_for": "'My Heart Will Go On', Titanic soundtrack, record-breaking Las Vegas residency, extraordinary vocal range",
    },
    "Adele": {
        "name": "Adele",
        "profession": "singer",
        "bio": "A British singer-songwriter who is one of the best-selling music artists in history, celebrated for her powerful contralto voice and emotional songwriting. Each of her studio albums — 19, 21, 25, and 30 — has debuted at number one and achieved multi-platinum status worldwide. She has won 15 Grammy Awards, making her one of the most decorated artists in the award's history.",
        "known_for": "'Rolling in the Deep', 'Hello', 21 album, Grammy record holder",
    },
    "Ed Sheeran": {
        "name": "Ed Sheeran",
        "profession": "singer-songwriter",
        "bio": "A British singer-songwriter who has become one of the world's best-selling music artists, known for blending pop, folk, and hip-hop in an accessible style. He began busking on the streets of London before being signed and his debut album + launched him to international stardom. He has set multiple chart records worldwide and is known for his sold-out stadium tours.",
        "known_for": "'Shape of You', 'Thinking Out Loud', Divide album, stadium tours",
    },
    "Shakira": {
        "name": "Shakira",
        "profession": "singer",
        "bio": "A Colombian singer-songwriter who is one of the best-selling Latin artists of all time and a global pop superstar. She began recording music in her native Colombia as a teenager and broke into the English-language market with her 2001 album Laundry Service. She is also known as a passionate philanthropist and has won Grammy Awards in both Latin and general categories.",
        "known_for": "'Hips Don't Lie', 'Waka Waka', Super Bowl halftime show, philanthropic work",
    },
    "Ariana Grande": {
        "name": "Ariana Grande",
        "profession": "pop singer",
        "bio": "An American singer, songwriter, and actress who began her career in Broadway musical theatre and later became one of the best-selling music artists in the world. She is known for her four-octave vocal range and whistle register and has broken numerous streaming and chart records. In 2017, a terrorist attack at one of her concerts in Manchester killed 22 people, after which she organized a benefit concert that raised millions for victims.",
        "known_for": "'Thank U, Next', whistle register vocal range, Thank U, Next album, One Love Manchester concert",
    },
    "Justin Bieber": {
        "name": "Justin Bieber",
        "profession": "pop singer",
        "bio": "A Canadian singer who was discovered through YouTube videos at age 13 and became one of the most popular teen idols in history. He released his debut album My World in 2009 at age 15 and quickly became a global phenomenon. He has sold over 150 million records worldwide and his journey from child star to adult artist has been one of the most documented in modern entertainment.",
        "known_for": "'Baby', 'Sorry', YouTube discovery story, record-breaking streaming numbers",
    },
    "Justin Timberlake": {
        "name": "Justin Timberlake",
        "profession": "singer and actor",
        "bio": "An American singer, songwriter, and actor who first rose to fame as a member of the boy band NSYNC before launching one of the most successful solo careers in pop music. He has won 10 Grammy Awards and 4 Emmy Awards and appeared in critically acclaimed films including The Social Network. He is widely credited with bringing funk and R&B influences back to mainstream pop music.",
        "known_for": "NSYNC, 'Cry Me a River', FutureSex/LoveSounds album, The Social Network",
    },
    "Kendrick Lamar": {
        "name": "Kendrick Lamar",
        "profession": "rapper",
        "bio": "An American rapper, songwriter, and record producer widely considered the greatest rapper of his generation. His album To Pimp a Butterfly is frequently cited as one of the greatest albums ever made, and his 2024 Super Bowl halftime show followed a high-profile rap feud that dominated internet discourse. In 2018, he became the first non-classical, non-jazz musician to win the Pulitzer Prize for Music.",
        "known_for": "To Pimp a Butterfly, Pulitzer Prize for Music, Super Bowl halftime show, Compton storytelling",
    },
    "Nicki Minaj": {
        "name": "Nicki Minaj",
        "profession": "rapper",
        "bio": "A Trinidadian-American rapper, singer, and songwriter who became the first female solo artist to have 100 entries on the Billboard Hot 100. She is known for her rapid-fire rhymes, alter egos, and colorful personality, and helped pave the way for female rappers in the modern era. She has collaborated with some of the biggest names in pop and hip-hop and remains one of the most influential artists in contemporary music.",
        "known_for": "'Super Bass', Pink Friday album, Billboard Hot 100 record, female rap trailblazer",
    },
    "Cardi B": {
        "name": "Cardi B",
        "profession": "rapper",
        "bio": "An American rapper and media personality who rose to fame through social media before becoming the first female rapper in history to have two number-one singles on the Billboard Hot 100 without featured artists. She worked as a stripper before landing a role on the reality TV series Love & Hip Hop: New York, which launched her music career. Her debut album Invasion of Privacy won the Grammy Award for Best Rap Album, making her the first solo female rapper to win the award.",
        "known_for": "'Bodak Yellow', Invasion of Privacy album, Grammy for Best Rap Album, reality TV origins",
    },
    "Ellen DeGeneres": {
        "name": "Ellen DeGeneres",
        "profession": "comedian and host",
        "bio": "An American stand-up comedian, television host, and actress who became one of the most popular daytime TV hosts in America with a talk show that ran for 19 seasons. She made television history in 1997 when her sitcom character came out as gay, making her one of the first openly gay people in mainstream entertainment. She has received the Presidential Medal of Freedom and numerous entertainment awards.",
        "known_for": "The Ellen DeGeneres Show, coming out in 1997, 'Finding Nemo' voice role, Presidential Medal of Freedom",
    },
    "Jimmy Fallon": {
        "name": "Jimmy Fallon",
        "profession": "TV host",
        "bio": "An American comedian, TV host, and writer who became the host of The Tonight Show in 2014, one of the youngest people to hold the position. He previously co-anchored Weekend Update on Saturday Night Live before hosting Late Night. He is known for celebrity games, musical impressions, and a cheerful on-screen personality.",
        "known_for": "The Tonight Show, Saturday Night Live, celebrity games and bits, musical impressions",
    },
    "Stephen Colbert": {
        "name": "Stephen Colbert",
        "profession": "TV host",
        "bio": "An American comedian, writer, and TV host who first gained widespread fame playing a right-wing pundit character on The Daily Show and later his own spinoff The Colbert Report. He took over The Late Show in 2015 and transformed it into one of the most-watched late-night programs in America. He is known for his sharp political satire and quick wit.",
        "known_for": "The Colbert Report, The Late Show, political satire, character-based comedy",
    },
    "Jon Stewart": {
        "name": "Jon Stewart",
        "profession": "TV host",
        "bio": "An American comedian, writer, and television host who transformed The Daily Show from a comedy news program into one of the most influential political commentary shows in America. He hosted the show from 1999 to 2015 and became a trusted news source for millions of younger Americans. He has since become a prominent advocate for veterans' rights and healthcare coverage for 9/11 first responders.",
        "known_for": "The Daily Show, political satire, advocacy for 9/11 first responders, influence on political comedy",
    },
    "Conan O'Brien": {
        "name": "Conan O'Brien",
        "profession": "TV host",
        "bio": "An American comedian, writer, and TV host who has hosted multiple late-night talk shows over more than 30 years. He is a Harvard graduate who worked as a writer for Saturday Night Live and The Simpsons before becoming a TV host. His self-deprecating humor and unique comedic sensibility have made him a beloved figure in American entertainment.",
        "known_for": "Late Night with Conan O'Brien, Tonight Show handover controversy, Harvard-educated comedy writer, Conan podcast",
    },
    "Gordon Ramsay": {
        "name": "Gordon Ramsay",
        "profession": "celebrity chef",
        "bio": "A British chef, restaurateur, and television personality who has been awarded 17 Michelin stars across his various restaurants, making him one of the most celebrated chefs in the world. He became a global television star through series including Hell's Kitchen, MasterChef, and Kitchen Nightmares, known for his high standards, fiery temper, and brutal critiques. Before becoming a chef, he trained as a professional footballer.",
        "known_for": "Hell's Kitchen, MasterChef, 17 Michelin stars, explosive on-screen persona",
    },
    "Anthony Bourdain": {
        "name": "Anthony Bourdain",
        "profession": "chef and author",
        "bio": "An American chef, author, and travel documentarian who became famous through his memoir Kitchen Confidential, a no-holds-barred account of life in professional kitchens. He hosted several acclaimed travel and food shows, most notably Parts Unknown on CNN, which explored the intersection of food, culture, and politics around the world. He died by suicide in 2018 while filming in France, leaving a profound legacy in food journalism and television.",
        "known_for": "Kitchen Confidential, Parts Unknown, food and travel journalism, candid storytelling",
    },
    "Julia Child": {
        "name": "Julia Child",
        "profession": "cookbook author",
        "bio": "An American cooking teacher, author, and television personality who introduced French cuisine to American audiences through her landmark cookbook and long-running TV series The French Chef. She didn't begin her culinary career until her late 30s, after studying at Le Cordon Bleu in Paris. Her enthusiastic, unstuffy approach to cooking made her one of the most beloved figures in American food culture.",
        "known_for": "Mastering the Art of French Cooking, The French Chef, introducing French cuisine to America, infectious enthusiasm",
    },
    "Martha Stewart": {
        "name": "Martha Stewart",
        "profession": "lifestyle entrepreneur",
        "bio": "An American businesswoman, writer, and television personality who built a media empire around home cooking, entertaining, and decorating. She parlayed her expertise into a multimedia lifestyle brand that at its peak was worth over a billion dollars. After serving five months in prison for insider trading in 2004, she successfully rehabilitated her public image and continued expanding her brand.",
        "known_for": "Martha Stewart Living brand, homemaking and entertaining empire, prison and comeback, lifestyle TV",
    },
    "Tim Cook": {
        "name": "Tim Cook",
        "profession": "tech executive",
        "bio": "An American business executive who has served as CEO of Apple Inc. since 2011, following the death of co-founder Steve Jobs. Under his leadership, Apple became the first company to reach market capitalizations of $1 trillion, $2 trillion, and then $3 trillion. He has been an outspoken advocate for privacy, climate change, and LGBTQ+ rights.",
        "known_for": "CEO of Apple, expanding Apple to $3 trillion valuation, LGBTQ+ advocacy, supply chain innovation",
    },
    "Satya Nadella": {
        "name": "Satya Nadella",
        "profession": "tech executive",
        "bio": "An Indian-American business executive who has served as CEO of Microsoft since 2014, overseeing a dramatic transformation of the company's culture and strategy. Under his leadership, Microsoft pivoted to cloud computing with Azure, became a major investor in OpenAI, and saw its market capitalization rise from around $300 billion to over $3 trillion. He is widely praised for reshaping Microsoft from a siloed competitive culture into a more collaborative and innovative organization.",
        "known_for": "CEO of Microsoft, Azure cloud growth, OpenAI investment, Microsoft cultural transformation",
    },
    "Sundar Pichai": {
        "name": "Sundar Pichai",
        "profession": "tech executive",
        "bio": "An Indian-American business executive who has served as CEO of Alphabet Inc. and its subsidiary Google since 2019 and 2015 respectively. He oversaw the development of major products including Chrome and Google Drive before rising to the top role. He has guided the company's push into artificial intelligence with products including the Gemini AI model.",
        "known_for": "CEO of Google/Alphabet, Google Chrome development, AI initiatives, Gemini model",
    },
    "Jack Dorsey": {
        "name": "Jack Dorsey",
        "profession": "tech entrepreneur",
        "bio": "An American technology entrepreneur and philanthropist who co-founded Twitter and later founded the mobile payments company Square (now Block). He served two separate stints as CEO of Twitter, most notably returning in 2015 to help stabilize the platform, and stepped down as Twitter CEO in 2021. He is known for his unconventional lifestyle including meditation retreats and extreme intermittent fasting.",
        "known_for": "co-founding Twitter, founding Square/Block, two-time Twitter CEO, unconventional lifestyle",
    },
    "Travis Kalanick": {
        "name": "Travis Kalanick",
        "profession": "tech entrepreneur",
        "bio": "An American entrepreneur who co-founded Uber and served as its CEO, growing it from a small car service startup into one of the most valuable private companies in history. His aggressive, rule-breaking growth strategy reshaped the global transportation industry and spawned a wave of gig economy companies. He was forced out as CEO in 2017 amid a series of scandals involving company culture and his own conduct.",
        "known_for": "co-founding Uber, disrupting transportation industry, gig economy pioneer, forced CEO resignation",
    },
    "Brian Chesky": {
        "name": "Brian Chesky",
        "profession": "tech entrepreneur",
        "bio": "An American entrepreneur and co-founder and CEO of Airbnb, the online marketplace that transformed the global hospitality industry by allowing ordinary people to rent out their homes to travelers. He and his co-founders famously funded the company's early days by selling novelty cereal boxes. Despite the COVID-19 pandemic devastating the travel industry, he led Airbnb to a successful IPO in December 2020.",
        "known_for": "co-founding Airbnb, disrupting hotel industry, cereal box funding story, COVID-era IPO",
    },
    "Evan Spiegel": {
        "name": "Evan Spiegel",
        "profession": "tech entrepreneur",
        "bio": "An American entrepreneur who co-founded Snapchat while at Stanford University and became one of the youngest billionaires in history. He famously turned down a $3 billion acquisition offer from Facebook, a decision widely criticized at the time but ultimately validated by Snapchat's continued growth. His company pioneered the ephemeral messaging format and the Stories feature later copied by Instagram and other platforms.",
        "known_for": "co-founding Snapchat, Stories format originator, rejecting Facebook's $3B offer, youngest billionaire",
    },
    "Sheryl Sandberg": {
        "name": "Sheryl Sandberg",
        "profession": "tech executive",
        "bio": "An American technology executive who served as the Chief Operating Officer of Meta (Facebook) from 2008 to 2022, helping transform it into one of the most profitable companies in the world. She authored the bestselling book Lean In, which sparked a worldwide conversation about women in leadership and workplace equality. She left Meta following controversy over her handling of various crises at the company.",
        "known_for": "COO of Meta/Facebook, Lean In book, women in leadership advocacy, advertising business model",
    },
    "Indra Nooyi": {
        "name": "Indra Nooyi",
        "profession": "business executive",
        "bio": "An Indian-American business executive who served as Chairman and CEO of PepsiCo from 2006 to 2018, overseeing the company's expansion into healthier products and international markets. She was consistently ranked among the most powerful women in business and credited with fundamentally reshaping PepsiCo's strategic vision. She immigrated to the United States from India to attend Yale School of Management.",
        "known_for": "CEO of PepsiCo, Performance with Purpose strategy, Yale education, most powerful women in business lists",
    },
    "Bono": {
        "name": "Bono",
        "profession": "rock musician",
        "bio": "An Irish rock singer who has been the lead vocalist and co-lyricist of U2, one of the world's best-selling rock bands, since the group's formation in Dublin in 1976. Beyond music, he is a prominent political activist and philanthropist, co-founding ONE, an organization that campaigns against extreme poverty and preventable disease. He is one of a small number of individuals nominated for both a Nobel Peace Prize and an Academy Award.",
        "known_for": "U2, 'With or Without You', debt relief campaigning, ONE and (RED) organizations",
    },
    "Suleiman the Magnificent": {
        "name": "Suleiman the Magnificent",
        "profession": "Ottoman sultan",
        "bio": "The longest-reigning sultan of the Ottoman Empire, ruling from 1520 to 1566, during which time the empire reached the peak of its political, economic, and cultural power. He led military campaigns that expanded the empire across three continents, conquering Belgrade, Rhodes, and much of Hungary and North Africa. Known to his own people as 'the Lawgiver', he oversaw the codification of Ottoman law and was a noted poet and patron of the arts.",
        "known_for": "Ottoman Empire at its peak, conquest of Belgrade and Rhodes, Ottoman legal code, Suleymaniye Mosque",
    },
    "Catherine the Great": {
        "name": "Catherine the Great",
        "profession": "Russian empress",
        "bio": "A German-born princess who became Empress of Russia after orchestrating a coup against her husband Peter III in 1762, then ruled for 34 years as one of the most powerful monarchs in European history. She expanded Russia's territory through successful wars with the Ottoman Empire and the partition of Poland, and modernized Russia through the adoption of Enlightenment ideas. She was a prolific writer, patron of the arts, and one of the most educated rulers of her era.",
        "known_for": "34-year reign over Russia, Russian expansion and modernization, Enlightenment patronage, coup against Peter III",
    },
    "Ivan the Terrible": {
        "name": "Ivan the Terrible",
        "profession": "Russian tsar",
        "bio": "The first ruler to be crowned Tsar of all Russia, he reigned from 1547 to 1584 and oversaw a dramatic expansion of Russian territory and the centralization of royal power. His reign included significant military achievements and cultural advancements, but is equally remembered for periods of extreme paranoia and violence, most infamously the massacre of Novgorod and the murder of his own son. His epithet 'Terrible' derives from the Russian word 'Grozny', meaning awe-inspiring or formidable.",
        "known_for": "first Tsar of Russia, Russian territorial expansion, Oprichnina terror campaign, Saint Basil's Cathedral",
    },
    "Saladin": {
        "name": "Saladin",
        "profession": "military leader",
        "bio": "A Kurdish Muslim leader who became the first Sultan of Egypt and Syria and founded the Ayyubid dynasty. He is best known in the Western world for leading Muslim military forces against the Crusader states and recapturing Jerusalem in 1187, effectively ending the Kingdom of Jerusalem. Respected by both his adversaries and his own people for his chivalry, generosity, and military genius, he became a celebrated figure in both Islamic and European traditions.",
        "known_for": "recapture of Jerusalem 1187, founding the Ayyubid dynasty, chivalric reputation, Third Crusade",
    },
    "Ramses II": {
        "name": "Ramses II",
        "profession": "Egyptian pharaoh",
        "bio": "An ancient Egyptian pharaoh of the Nineteenth Dynasty who reigned from 1279 to 1213 BCE and is often regarded as the greatest and most celebrated ruler of the Egyptian Empire. He led military campaigns into Canaan and Nubia and is believed by many scholars to be the pharaoh of the biblical Exodus. He built more monuments, statues, and temples than any other pharaoh, including the iconic temples at Abu Simbel.",
        "known_for": "Battle of Kadesh, Abu Simbel temples, 66-year reign, believed pharaoh of the Exodus",
    },
    "Tutankhamun": {
        "name": "Tutankhamun",
        "profession": "Egyptian pharaoh",
        "bio": "An ancient Egyptian pharaoh of the Eighteenth Dynasty who ruled for approximately 10 years before dying around the age of 18 or 19. Although relatively minor during his lifetime, he became one of the most famous figures in history when archaeologist Howard Carter discovered his virtually intact tomb in the Valley of the Kings in 1922. The treasures found in the tomb, including a golden funerary mask, are among the most recognized objects of ancient Egyptian civilization.",
        "known_for": "discovery of tomb by Howard Carter 1922, golden funerary mask, Valley of the Kings, 'King Tut'",
    },
    "Cleopatra": {
        "name": "Cleopatra",
        "profession": "Egyptian queen",
        "bio": "The last active ruler of the Ptolemaic Kingdom of Egypt, she was the first of the Ptolemaic dynasty to learn the Egyptian language. She formed powerful political and romantic alliances with Julius Caesar and later Mark Antony, making her one of the most politically significant figures of the ancient world. Her death by suicide in 30 BCE following the defeat of Mark Antony marked the end of Egyptian independence and the beginning of Roman Egypt.",
        "known_for": "last pharaoh of Egypt, alliances with Caesar and Mark Antony, Ptolemaic dynasty, end of ancient Egyptian independence",
    },
    "Joan of Arc": {
        "name": "Joan of Arc",
        "profession": "military leader",
        "bio": "A French peasant girl who, claiming to be guided by divine visions, led the French army to several key victories during the Hundred Years' War that helped secure the coronation of Charles VII as King of France. She was captured by Burgundian forces, tried by a pro-English church court, and burned at the stake for heresy at age 19 in 1431. She was canonized as a Catholic saint in 1920 and is considered one of France's greatest national heroes.",
        "known_for": "leading French forces in Hundred Years' War, coronation of Charles VII, martyrdom at 19, Catholic sainthood",
    },
    "Eleanor Roosevelt": {
        "name": "Eleanor Roosevelt",
        "profession": "first lady and activist",
        "bio": "An American political figure, diplomat, and activist who served as the longest-serving First Lady of the United States, holding the role during a presidency that spanned the Great Depression and World War II. After her husband's death, she continued her public service, chairing the United Nations Human Rights Commission that drafted the Universal Declaration of Human Rights in 1948. She was called 'First Lady of the World' by President Truman for her human rights work.",
        "known_for": "Universal Declaration of Human Rights, UN Human Rights Commission, 'First Lady of the World', political activism",
    },
    "Coco Chanel": {
        "name": "Coco Chanel",
        "profession": "fashion designer",
        "bio": "A French fashion designer and businesswoman credited with liberating women from the corset era and defining modern women's fashion in the 20th century. She rose from poverty and an orphanage to found a global fashion empire, introducing revolutionary designs including the little black dress and a distinctive boxy suit. Her iconic perfume No. 5, launched in 1921, remains one of the best-selling fragrances in the world.",
        "known_for": "Chanel fashion house, No. 5 perfume, little black dress, liberating women's fashion",
    },
    "Henry Ford": {
        "name": "Henry Ford",
        "profession": "industrialist",
        "bio": "An American industrialist and business magnate who founded an automobile company that transformed the car from a luxury item into an affordable product for ordinary Americans. He introduced the moving assembly line into automobile manufacturing in 1913, dramatically reducing production costs and pioneering the era of mass production. His introduction of the $5 workday, double the prevailing wage, created a working class that could afford the products they were making.",
        "known_for": "Ford Motor Company, Model T, moving assembly line, $5 workday",
    },
    "Wright Brothers": {
        "name": "Wright Brothers",
        "profession": "aviation pioneers",
        "bio": "American brothers and aviation pioneers who made the first sustained, controlled, powered heavier-than-air flight at Kitty Hawk, North Carolina on December 17, 1903. They were self-educated engineers who built and repaired bicycles, using their mechanical expertise to solve the fundamental challenges of flight including lift, propulsion, and control. Their invention of the airplane transformed the world more profoundly than almost any other single technological advance in history.",
        "known_for": "first powered airplane flight, Kitty Hawk 1903, aviation pioneers, self-taught engineering",
    },
    "Amelia Earhart": {
        "name": "Amelia Earhart",
        "profession": "aviator",
        "bio": "An American aviation pioneer who became the first woman to fly solo across the Atlantic Ocean in 1932 and set numerous other aviation records. She was a prominent feminist who encouraged women to pursue careers in aviation and other male-dominated fields. She disappeared over the central Pacific Ocean in 1937 during an attempt to circumnavigate the globe, and her fate remains one of the great mysteries of the 20th century.",
        "known_for": "first woman to fly solo Atlantic, 1937 disappearance mystery, aviation records, feminist icon",
    },
    "Neil Armstrong": {
        "name": "Neil Armstrong",
        "profession": "astronaut",
        "bio": "An American astronaut and aeronautical engineer who became the first human being to set foot on the Moon on July 20, 1969, during the Apollo 11 mission. His words upon stepping onto the lunar surface — 'That's one small step for man, one giant leap for mankind' — became one of the most famous quotes of the 20th century. He was a decorated Navy pilot and test pilot before joining NASA, and later became a professor of engineering.",
        "known_for": "first human on the Moon, Apollo 11, 'one small step' quote, test pilot career",
    },
    "Buzz Aldrin": {
        "name": "Buzz Aldrin",
        "profession": "astronaut",
        "bio": "An American astronaut and fighter pilot who was the second human to walk on the Moon as part of the Apollo 11 mission in 1969. He earned a doctorate from MIT in astronautics and was known as 'Dr. Rendezvous' for his pioneering work on space docking techniques. After returning from space he struggled with depression and alcoholism but became a tireless advocate for Mars exploration and continued human spaceflight.",
        "known_for": "Apollo 11 Moon landing, second human on the Moon, space docking techniques, Mars exploration advocacy",
    },
    "Yuri Gagarin": {
        "name": "Yuri Gagarin",
        "profession": "cosmonaut",
        "bio": "A Soviet cosmonaut who became the first human being to travel into outer space, completing one orbit of the Earth on April 12, 1961, aboard the Vostok 1 spacecraft. His flight lasted 108 minutes and made him one of the most celebrated figures of the Cold War era and a global symbol of human achievement. He died in a training jet crash in 1968 at age 34, never having flown in space again after his historic mission.",
        "known_for": "first human in space, Vostok 1, April 12 1961, Cold War space race symbol",
    },
    "Alan Shepard": {
        "name": "Alan Shepard",
        "profession": "astronaut",
        "bio": "An American astronaut and naval aviator who became the first American in space on May 5, 1961, aboard the Freedom 7 capsule. He later commanded the Apollo 14 mission in 1971 and became the fifth person to walk on the Moon — and the only one to play golf there, hitting two balls across the lunar surface. He was one of the Mercury Seven, the original group of astronauts selected by NASA.",
        "known_for": "first American in space, Apollo 14, golf shot on the Moon, Mercury Seven astronaut",
    },
    "John Glenn": {
        "name": "John Glenn",
        "profession": "astronaut and senator",
        "bio": "An American Marine Corps aviator, astronaut, and politician who became the first American to orbit the Earth on February 20, 1962, aboard Friendship 7. He later served as a Democratic U.S. Senator from Ohio for 24 years. In 1998, at age 77, he returned to space aboard the Space Shuttle Discovery, becoming the oldest person ever to fly in space.",
        "known_for": "first American to orbit Earth, Friendship 7, U.S. Senator from Ohio, oldest person in space",
    },
    "Katharine Hepburn": {
        "name": "Katharine Hepburn",
        "profession": "actress",
        "bio": "An American actress of film, stage, and television who had a career spanning over 60 years and was known for playing strong-willed, independent characters. She won four Academy Awards for Best Actress — more than any other performer in history — for Morning Glory, Guess Who's Coming to Dinner, The Lion in Winter, and On Golden Pond. Her unconventional personal style, including her trademark trousers, made her a fashion icon as well as a cinematic legend.",
        "known_for": "four Academy Awards for Best Actress, Morning Glory, The Lion in Winter, On Golden Pond",
    },
    "Audrey Hepburn": {
        "name": "Audrey Hepburn",
        "profession": "actress",
        "bio": "A British-American actress and humanitarian widely regarded as a major fashion icon and one of the greatest actresses in Hollywood history. She is one of the few entertainers to achieve the EGOT — winning an Academy Award, an Emmy, a Grammy, and a Tony Award. After her acting career, she devoted much of her time to humanitarian work with UNICEF in Africa, South America, and Asia.",
        "known_for": "Breakfast at Tiffany's, Roman Holiday, EGOT winner, UNICEF humanitarian work",
    },
    "Greta Garbo": {
        "name": "Greta Garbo",
        "profession": "actress",
        "bio": "A Swedish-American actress and international star of the silent and sound film eras, regarded as one of the greatest screen actresses in film history. She was known for her enigmatic persona and her fierce desire for privacy, famously expressing a wish to be left alone. She retired from acting in 1941 at the age of 36 and was posthumously awarded an honorary Academy Award for her luminous and unforgettable screen performances.",
        "known_for": "silent film era icon, enigmatic persona, Grand Hotel, honorary Academy Award",
    },
}
