# ~500 popular 7–10 letter words used as anagram source words.
# Every entry is verified to be 7, 8, 9, or 10 characters.

SOURCE_WORDS: list = [

    # ── 7 letters ─────────────────────────────────────────────────────────────
    "blanket", "captain", "climate", "compass", "concert", "culture",
    "diamond", "distant", "eastern", "element", "emperor", "fantasy",
    "fashion", "fiction", "fortune", "freedom", "glacier", "gravity",
    "harvest", "history", "holiday", "inferno", "justice", "kingdom",
    "mystery", "network", "package", "perfect", "phantom", "picture",
    "prevent", "problem", "primary", "promise", "quality", "quantum",
    "rainbow", "reality", "reserve", "respect", "triumph", "trouble",
    "typical", "unusual", "various", "village", "volcano", "warrior",
    "western", "whisper", "kitchen", "flowers", "dragons", "planets",
    "fingers", "bottles", "animals", "pirates", "numbers", "letters",
    "muscles", "gardens", "stories", "knights", "bridges", "shadows",
    "chicken", "windows", "players", "cartoon", "cabinet", "ceiling",
    "chapter", "circuit", "classic", "closure", "company", "context",
    "courage", "crystal", "curtain", "destiny", "extreme", "fighter",
    "foreign", "formula", "forward", "general", "graphic", "journey",
    "landing", "lasting", "limited", "message", "million", "missing",
    "mixture", "monitor", "opinion", "outside", "painter", "parents",
    "pattern", "payment", "popular", "pottery", "prepare", "routine",
    "sailing", "science", "section", "service", "setting", "several",
    "shelter", "singing", "skating", "sorting", "species", "staying",
    "storage", "streams", "student", "success", "surface", "teacher",
    "testing", "texture", "tonight", "totally", "trading", "trained",
    "travels", "turning", "uniform", "updated", "viewing", "waiting",
    "warning", "working", "writing", "younger", "drawing", "camping",
    "jumping", "dancing", "reading", "playing", "smiling", "fishing",
    "surgeon", "workout", "outlook", "bedroom", "desktop", "highway",
    "popcorn", "seaside", "sunrise", "sunsets", "toolkit", "upstairs",

    # ── 8 letters ─────────────────────────────────────────────────────────────
    "absolute", "backward", "birthday", "calendar", "campaign", "computer",
    "darkness", "daughter", "elephant", "entrance", "finished", "football",
    "grateful", "hardware", "hospital", "innocent", "keyboard", "language",
    "laughing", "marriage", "mountain", "negative", "notebook", "obstacle",
    "overflow", "painting", "powerful", "question", "railroad", "religion",
    "sandwich", "shoulder", "skeleton", "teaching", "thousand", "together",
    "umbrella", "universe", "vacation", "whenever", "yourself", "building",
    "cleaning", "climbing", "counting", "covering", "cracking", "creating",
    "crossing", "crushing", "deciding", "delivery", "describe", "designer",
    "discover", "distance", "dressing", "drinking", "enjoying", "exciting",
    "fighting", "focusing", "gathered", "glorious", "goodness", "greatest",
    "greeting", "guidance", "handling", "headline", "horrible", "imagined",
    "infamous", "inspired", "jealousy", "kindness", "knockout", "learning",
    "lifetime", "likewise", "lockdown", "managing", "matching", "material",
    "medicine", "memories", "momentum", "movement", "mystical", "national",
    "necklace", "offering", "official", "organize", "original", "peaceful",
    "planning", "platform", "possible", "practice", "pressure", "printing",
    "progress", "purchase", "reaching", "register", "relative", "research",
    "revealed", "romantic", "schedule", "soldiers", "solution", "speaking",
    "spinning", "standard", "standing", "starting", "stepping", "stopping",
    "strength", "studying", "swimming", "thinking", "throwing", "touching",
    "tracking", "training", "treasure", "troubled", "ultimate", "unlikely",
    "watching", "weakness", "wildlife", "workshop", "blessing", "blooming",
    "breaking", "breeding", "bringing", "browsing", "changing", "charging",
    "checking", "choosing", "climbing", "clipping", "dropping", "floating",
    "flipping", "freezing", "grabbing", "grinding", "grouping", "guarding",
    "heatwave", "homework", "internet", "laughing", "layering", "lighting",
    "limiting", "loading", "looping", "matching", "planting", "polished",
    "printers", "questing", "reaching", "relaxing", "removing", "replaced",
    "replying", "reported", "requires", "resisted", "response", "rewarded",
    "rotating", "screamed", "shooting", "shopping", "shouting", "shutting",
    "slipping", "smashing", "sneaking", "software", "stabbing", "sticking",
    "stunning", "swinging", "throwing", "training", "traveled", "trending",
    "unstable", "vacation", "vibrated", "visiting", "wounding",

    # ── 9 letters ─────────────────────────────────────────────────────────────
    "adventure", "afternoon", "alongside", "ambitious", "apartment",
    "available", "beautiful", "blindfold", "broadcast", "butterfly",
    "calculate", "carefully", "certainly", "challenge", "character",
    "childhood", "chocolate", "christmas", "combining", "community",
    "companion", "completed", "confident", "connected", "continent",
    "crossword", "currently", "customers", "dangerous", "dedicated",
    "departure", "detective", "developer", "direction", "discovery",
    "education", "emergency", "enchanted", "energetic", "enjoyable",
    "essential", "everybody", "excellent", "fantastic", "financial",
    "forbidden", "fortunate", "generally", "geography", "halloween",
    "happening", "heartbeat", "highlight", "horrified", "hurricane",
    "identical", "imaginary", "immediate", "improving", "including",
    "influence", "inspiring", "inventory", "launching", "libraries",
    "lightning", "literally", "listening", "magnitude", "meanwhile",
    "measuring", "memorable", "microwave", "motivated", "necessary",
    "nightmare", "objective", "obviously", "occurring", "operating",
    "operation", "orchestra", "ourselves", "passenger", "permanent",
    "permitted", "pineapple", "principal", "providing", "quicksand",
    "realistic", "reasoning", "rectangle", "renewable", "reporting",
    "returning", "satellite", "secretary", "sensitive", "separated",
    "september", "situation", "something", "somewhere", "structure",
    "submarine", "superhero", "supported", "surprised", "surviving",
    "technical", "telephone", "temporary", "territory", "tradition",
    "transport", "typically", "uncovered", "unlimited", "vegetable",
    "volunteer", "wednesday", "wonderful", "worldwide", "gymnasium",
    "accepting", "achieving", "attacking", "attracting", "believing",
    "breathing", "capturing", "caretaker", "celebrate", "centrally",
    "competing", "computing", "conquering", "construct", "converted",
    "convinced", "copyright", "craftsman", "defeating", "defending",
    "depending", "deserving", "designing", "destroyed", "discharge",
    "displayed", "dominated", "doubtless", "elsewhere", "employing",
    "enforcing", "enlarging", "equipping", "exploring", "expressed",
    "extending", "filtering", "following", "framework", "gathering",
    "governing", "graduated", "hardcover", "headlines", "impacting",
    "increased", "indicated", "installed", "intending", "mentioned",
    "milestone", "miserable", "narrative", "organized", "otherwise",
    "ownership", "paragraph", "partially", "protected", "published",
    "qualified", "recovered", "refreshed", "remaining", "rendering",
    "repeating", "replacing", "reshaping", "resolving", "resulting",
    "rewarding", "selecting", "shortened", "simulated", "solutions",
    "specified", "suffering", "suggested", "teachings", "thousands",
    "triggered", "validated", "variation", "varieties", "virtually",

    # ── 10 letters ────────────────────────────────────────────────────────────
    "strawberry", "basketball", "background", "birthplace", "blackboard",
    "brainstorm", "brightness", "chalkboard", "checkpoint", "collecting",
    "complexity", "conclusion", "connecting", "creativity", "crossroads",
    "determined", "developing", "dictionary", "difficulty", "discipline",
    "discussion", "earthquake", "elementary", "everywhere", "experience",
    "flashlight", "foundation", "friendship", "goalkeeper", "government",
    "gravestone", "greenhouse", "groundwork", "hamburgers", "highlights",
    "impression", "increasing", "invitation", "journalism", "leadership",
    "lighthouse", "management", "motorcycle", "mysterious", "navigation",
    "networking", "newsletter", "nightstand", "occupation", "operations",
    "percentage", "permission", "philosophy", "playground", "politician",
    "popularity", "population", "prediction", "prevention", "production",
    "psychology", "publishing", "punishment", "rainforest", "reasonable",
    "regulation", "relaxation", "remarkable", "renovation", "reputation",
    "resolution", "revolution", "skateboard", "smartphone", "soundtrack",
    "spacecraft", "stargazing", "statistics", "storyboard", "strengthen",
    "submission", "successful", "suggestion", "sunglasses", "superhuman",
    "suspension", "technology", "television", "tournament", "transition",
    "underscore", "underwater", "university", "validation", "volleyball",
    "vocabulary", "watermelon", "wavelength", "wilderness", "wonderland",
    "absolutely", "accelerate", "accounting", "achievement", "algorithms",
    "annotation", "anticipate", "automation", "boundaries", "calculated",
    "categorize", "charitable", "citizenship", "comparison", "compatible",
    "compelling", "completion", "components", "compromise", "conditions",
    "convenient", "conversion", "convincing", "coordinate", "correction",
    "dedication", "deployment", "depression", "describing", "discovered",
    "discretion", "documented", "dominating", "encryption", "escalating",
    "eventually", "excitement", "exhausting", "exhibition", "expedition",
    "explaining", "exploiting", "expression", "filtration", "frequently",
    "frustrated", "generating", "headphones", "horoscopes", "illustrate",
    "impressing", "infections", "innovative", "inspecting", "installing",
    "integrated", "interfered", "investment", "kilometers", "laboratory",
    "lawnmower", "liberating", "livelihood", "marketing", "memorizing",
    "mentioning", "motivation", "motorcycle", "multiplied", "nationally",
    "observable", "organizing", "overlooked", "overcoming", "performing",
    "positioned", "predicting", "presenting", "preventing", "processing",
    "programmed", "protecting", "questioned", "recovering", "recruiting",
    "redesigned", "reflecting", "refraining", "regulating", "reinforced",
    "remembering", "reshuffled", "restrained", "retrieving", "revealing",
    "scheduling", "scratching", "separation", "shortening", "simplistic",
    "simulating", "skateboard", "skyscraper", "smoothness", "socializing",
    "specifying", "strategize", "structured", "surrounded", "sustaining",
    "thundering", "timestamps", "tolerating", "toothbrush", "triggering",
    "turbulence", "unimagined", "unplugged", "unraveling", "validating",
    "vibrations", "victorious", "wavelength", "worldclass",
]
