# Movie data for Movie Guesser cog.
# Synopsis must NOT contain the movie title.
# Each entry: title, year, synopsis (2-4 light sentences), cast (top 2 actors/voice actors).

MOVIES = [

    # ── Pre-1970 Classics ─────────────────────────────────────────────────────

    {
        "title": "Gone with the Wind",
        "year": 1939,
        "synopsis": "A spoiled Southern belle watches her plantation world crumble during the Civil War while chasing a man who's in love with someone else. She survives on sheer stubbornness and questionable fashion choices, vowing to never go hungry again.",
        "cast": ["Vivien Leigh", "Clark Gable"],
    },
    {
        "title": "The Wizard of Oz",
        "year": 1939,
        "synopsis": "A Kansas farm girl gets swept up by a tornado and lands in a colorful magical land where she befriends a scarecrow, a tin man, and a cowardly lion on a quest to get home. There's a very small man behind the curtain.",
        "cast": ["Judy Garland", "Frank Morgan"],
    },
    {
        "title": "Casablanca",
        "year": 1942,
        "synopsis": "A bitter American runs a bar in wartime Morocco when his lost love walks in with a resistance leader husband and a desperate need for exit visas. Of all the gin joints in all the towns in all the world...",
        "cast": ["Humphrey Bogart", "Ingrid Bergman"],
    },
    {
        "title": "It's a Wonderful Life",
        "year": 1946,
        "synopsis": "A small-town banker hits rock bottom and wishes he'd never been born, so an angel shows him exactly what that would have looked like. Spoiler: a lot worse.",
        "cast": ["James Stewart", "Donna Reed"],
    },
    {
        "title": "Singin' in the Rain",
        "year": 1952,
        "synopsis": "Hollywood's transition from silent films to talkies is a disaster when a big star turns out to have a voice like a foghorn. Luckily there's dancing, a lot of dancing, and a very long scarf.",
        "cast": ["Gene Kelly", "Debbie Reynolds"],
    },
    {
        "title": "Rear Window",
        "year": 1954,
        "synopsis": "A bored photographer with a broken leg spends his recovery spying on neighbors from his window and becomes convinced one of them murdered his wife. His girlfriend thinks he's being paranoid. She's wrong.",
        "cast": ["James Stewart", "Grace Kelly"],
    },
    {
        "title": "Vertigo",
        "year": 1958,
        "synopsis": "A retired detective with a crippling fear of heights is hired to follow a mysterious woman who seems to be haunted by a dead ancestor. Things get very complicated and very dark.",
        "cast": ["James Stewart", "Kim Novak"],
    },
    {
        "title": "North by Northwest",
        "year": 1959,
        "synopsis": "A New York ad executive is mistaken for a government spy by a murderous organisation and spends the film being chased across America, culminating on the face of Mount Rushmore.",
        "cast": ["Cary Grant", "Eva Marie Saint"],
    },
    {
        "title": "Some Like It Hot",
        "year": 1959,
        "synopsis": "Two broke musicians witness a mob murder and flee Chicago by disguising themselves as women in an all-female jazz band. One falls for the gorgeous singer, which makes things complicated.",
        "cast": ["Marilyn Monroe", "Jack Lemmon"],
    },
    {
        "title": "Psycho",
        "year": 1960,
        "synopsis": "A secretary embezzles money and stops at a remote motel run by a shy young man who is very close with his mother. The shower scene changed cinema forever.",
        "cast": ["Anthony Perkins", "Janet Leigh"],
    },
    {
        "title": "Breakfast at Tiffany's",
        "year": 1961,
        "synopsis": "A free-spirited New York socialite in a little black dress befriends her struggling writer neighbor while searching for a rich husband. She's fabulous, eccentric, and absolutely refuses to name her cat.",
        "cast": ["Audrey Hepburn", "George Peppard"],
    },
    {
        "title": "Lawrence of Arabia",
        "year": 1962,
        "synopsis": "An eccentric British officer leads Arab tribal forces in battle against the Turks during World War I, becoming a legend in the desert while questioning what he's actually fighting for.",
        "cast": ["Peter O'Toole", "Omar Sharif"],
    },
    {
        "title": "Dr. Strangelove",
        "year": 1964,
        "synopsis": "A deranged American general orders a nuclear attack on the Soviet Union, setting off a frantic comedy of errors in the War Room and aboard a B-52. The bomb gets ridden like a rodeo horse.",
        "cast": ["Peter Sellers", "George C. Scott"],
    },
    {
        "title": "The Sound of Music",
        "year": 1965,
        "synopsis": "An irrepressible novice nun is sent to be governess for a strict Austrian navy captain's seven children, and proceeds to teach everyone how to sing and have fun. The Nazis ruin the ending.",
        "cast": ["Julie Andrews", "Christopher Plummer"],
    },
    {
        "title": "The Good, the Bad and the Ugly",
        "year": 1966,
        "synopsis": "Three ruthless gunslingers with very on-the-nose nicknames race each other across the Civil War-era American Southwest to find buried Confederate gold. The standoff at the end takes about twenty minutes.",
        "cast": ["Clint Eastwood", "Lee Van Cleef"],
    },
    {
        "title": "2001: A Space Odyssey",
        "year": 1968,
        "synopsis": "Mankind's evolution from apes to astronauts is overseen by mysterious black monoliths, culminating in a mission to Jupiter with a very creepy computer named HAL. It ends with a star baby. Interpret that as you will.",
        "cast": ["Keir Dullea", "Gary Lockwood"],
    },
    {
        "title": "Butch Cassidy and the Sundance Kid",
        "year": 1969,
        "synopsis": "Two charming outlaws find that train robbery isn't as easy as it used to be when a relentless posse tracks them across the country. They decide Bolivia must be nicer.",
        "cast": ["Paul Newman", "Robert Redford"],
    },

    # ── 1970s ─────────────────────────────────────────────────────────────────

    {
        "title": "The Godfather",
        "year": 1972,
        "synopsis": "The aging patriarch of a powerful Italian-American crime family refuses a drug deal and nearly gets killed for it, forcing his youngest son to reluctantly take over. An offer he couldn't refuse.",
        "cast": ["Marlon Brando", "Al Pacino"],
    },
    {
        "title": "The Exorcist",
        "year": 1973,
        "synopsis": "A twelve-year-old girl in Washington D.C. starts behaving very strangely — spinning heads, levitating, and some deeply unpleasant vocabulary — so her mother calls in a priest.",
        "cast": ["Linda Blair", "Ellen Burstyn"],
    },
    {
        "title": "Blazing Saddles",
        "year": 1974,
        "synopsis": "A corrupt politician appoints a Black sheriff to drive residents out of a Western town, not realising the new sheriff is considerably smarter than he looks. The fourth wall does not survive.",
        "cast": ["Cleavon Little", "Gene Wilder"],
    },
    {
        "title": "Chinatown",
        "year": 1974,
        "synopsis": "A private detective hired to investigate a phony adultery case stumbles into a massive water corruption scandal and a family secret so dark he wishes he'd never started digging.",
        "cast": ["Jack Nicholson", "Faye Dunaway"],
    },
    {
        "title": "The Godfather Part II",
        "year": 1974,
        "synopsis": "The new crime boss expands the family empire and becomes increasingly ruthless, while flashbacks show how his immigrant father built it all from scratch in early 1900s New York. Power corrupts, family betrays.",
        "cast": ["Al Pacino", "Robert De Niro"],
    },
    {
        "title": "Jaws",
        "year": 1975,
        "synopsis": "A small beach town's police chief, who is afraid of water, teams up with a marine biologist and a grizzled old shark hunter to deal with an enormous great white terrorizing swimmers. They're gonna need a bigger boat.",
        "cast": ["Roy Scheider", "Richard Dreyfuss"],
    },
    {
        "title": "One Flew Over the Cuckoo's Nest",
        "year": 1975,
        "synopsis": "A con man fakes insanity to serve his prison sentence in a cushy mental institution, but clashes with the chillingly controlling head nurse in a battle of wills that escalates very badly.",
        "cast": ["Jack Nicholson", "Louise Fletcher"],
    },
    {
        "title": "Rocky",
        "year": 1976,
        "synopsis": "A small-time Philadelphia boxer gets the once-in-a-lifetime chance to fight the world heavyweight champion, which he uses mostly as motivation to prove he's not a total bum.",
        "cast": ["Sylvester Stallone", "Talia Shire"],
    },
    {
        "title": "Taxi Driver",
        "year": 1976,
        "synopsis": "A mentally unstable Vietnam vet works nights as a New York cab driver and becomes increasingly obsessed with cleaning up the city's scum, targeting a politician and a teenage prostitute.",
        "cast": ["Robert De Niro", "Jodie Foster"],
    },
    {
        "title": "Annie Hall",
        "year": 1977,
        "synopsis": "A neurotic New York comedian dissects the ups and downs of his failed romance with a quirky aspiring singer in a non-linear love story that breaks the fourth wall constantly.",
        "cast": ["Woody Allen", "Diane Keaton"],
    },
    {
        "title": "Star Wars",
        "year": 1977,
        "synopsis": "A farm boy from a desert planet joins a rebel princess, a roguish smuggler, and his fuzzy co-pilot to rescue a galaxy from an evil Empire armed with a planet-sized weapon.",
        "cast": ["Mark Hamill", "Harrison Ford"],
    },
    {
        "title": "Animal House",
        "year": 1978,
        "synopsis": "The most disreputable fraternity on a buttoned-up college campus throws epic parties, sabotages the school parade, and generally refuses to be expelled despite everyone's best efforts.",
        "cast": ["John Belushi", "Tim Matheson"],
    },
    {
        "title": "Grease",
        "year": 1978,
        "synopsis": "A sweet summer romance between a wholesome Australian girl and a greaser boy at Rydell High gets complicated when they both turn up at the same school in the fall.",
        "cast": ["John Travolta", "Olivia Newton-John"],
    },
    {
        "title": "Halloween",
        "year": 1978,
        "synopsis": "A masked mental patient escapes from the asylum on Halloween night and returns to his hometown to stalk babysitters, with only a persistent psychiatrist hot on his trail.",
        "cast": ["Jamie Lee Curtis", "Donald Pleasence"],
    },
    {
        "title": "The Deer Hunter",
        "year": 1978,
        "synopsis": "Three friends from a small Pennsylvania steel town go to Vietnam together and come back changed forever, particularly after a harrowing experience involving Russian roulette.",
        "cast": ["Robert De Niro", "Christopher Walken"],
    },
    {
        "title": "Alien",
        "year": 1979,
        "synopsis": "The crew of a commercial space freighter answers a distress signal on a desolate moon and brings back an uninvited passenger that turns out to be the universe's most relentless killing machine.",
        "cast": ["Sigourney Weaver", "Tom Skerritt"],
    },
    {
        "title": "Apocalypse Now",
        "year": 1979,
        "synopsis": "A US Army captain is sent up a river into the jungles of Cambodia to terminate a rogue Special Forces colonel who has apparently gone completely insane and built his own kingdom.",
        "cast": ["Martin Sheen", "Marlon Brando"],
    },

    # ── 1980s ─────────────────────────────────────────────────────────────────

    {
        "title": "The Blues Brothers",
        "year": 1980,
        "synopsis": "Two brothers who are on a mission from God reassemble their band to raise money for a Chicago orphanage, leaving an enormous trail of destruction — and excellent soul music — across Illinois.",
        "cast": ["John Belushi", "Dan Aykroyd"],
    },
    {
        "title": "Raiders of the Lost Ark",
        "year": 1981,
        "synopsis": "An archaeologist with a whip and a fear of snakes races the Nazis to find the ancient biblical Ark of the Covenant, which turns out to be absolutely not a toy.",
        "cast": ["Harrison Ford", "Karen Allen"],
    },
    {
        "title": "E.T. the Extra-Terrestrial",
        "year": 1982,
        "synopsis": "A lonely ten-year-old suburban boy befriends a stranded alien botanist who just wants to phone home, while government agents are determined to ruin everyone's fun.",
        "cast": ["Henry Thomas", "Drew Barrymore"],
    },
    {
        "title": "Tootsie",
        "year": 1982,
        "synopsis": "A difficult, unemployable actor dresses up as a middle-aged woman to land a soap opera role and becomes a beloved feminist icon, which complicates everything.",
        "cast": ["Dustin Hoffman", "Jessica Lange"],
    },
    {
        "title": "National Lampoon's Vacation",
        "year": 1983,
        "synopsis": "An enthusiastic dad drags his reluctant family on an epic cross-country road trip to a theme park, with an increasingly catastrophic string of mishaps along the way.",
        "cast": ["Chevy Chase", "Beverly D'Angelo"],
    },
    {
        "title": "Scarface",
        "year": 1983,
        "synopsis": "A Cuban refugee arrives in Miami with nothing and claws his way to the top of the cocaine trade through extreme violence and an even more extreme wardrobe. The world is his.",
        "cast": ["Al Pacino", "Michelle Pfeiffer"],
    },
    {
        "title": "Amadeus",
        "year": 1984,
        "synopsis": "The court composer to the Austrian emperor tells how he spent his whole career seething with jealousy over the vulgar young genius who made him look like a mediocre amateur.",
        "cast": ["F. Murray Abraham", "Tom Hulce"],
    },
    {
        "title": "Beverly Hills Cop",
        "year": 1984,
        "synopsis": "A fast-talking Detroit detective ignores orders and heads to Beverly Hills to investigate his friend's murder, completely unprepared for how different rich California cops are from his Michigan colleagues.",
        "cast": ["Eddie Murphy", "Judge Reinhold"],
    },
    {
        "title": "Ghostbusters",
        "year": 1984,
        "synopsis": "Three disgraced parapsychology professors start a ghost-catching business in New York City just in time for a supernatural apocalypse centered on a Manhattan apartment building.",
        "cast": ["Bill Murray", "Dan Aykroyd"],
    },
    {
        "title": "The Karate Kid",
        "year": 1984,
        "synopsis": "A teenager who's being bullied by a karate gang is taken under the wing of his building's handyman, who teaches him discipline, respect, and how to fight using chores as training.",
        "cast": ["Ralph Macchio", "Pat Morita"],
    },
    {
        "title": "The Terminator",
        "year": 1984,
        "synopsis": "A robot assassin from the future arrives in 1984 Los Angeles to kill a young woman whose yet-to-be-born son will lead humanity's resistance. A soldier from the future arrives to stop him.",
        "cast": ["Arnold Schwarzenegger", "Linda Hamilton"],
    },
    {
        "title": "Clue",
        "year": 1985,
        "synopsis": "Six strangers are invited to a mysterious mansion for a dinner party and one of them ends up dead — then so does the butler. Based on the board game, and just as chaotic.",
        "cast": ["Tim Curry", "Madeline Kahn"],
    },
    {
        "title": "Back to the Future",
        "year": 1985,
        "synopsis": "A teenager is accidentally sent back to 1955 in a DeLorean time machine and must make his parents fall in love before he ceases to exist, while also finding a way back.",
        "cast": ["Michael J. Fox", "Christopher Lloyd"],
    },
    {
        "title": "The Breakfast Club",
        "year": 1985,
        "synopsis": "Five very different high school students — the brain, the athlete, the basket case, the princess, and the criminal — spend a Saturday in detention and discover they have more in common than they think.",
        "cast": ["Molly Ringwald", "Judd Nelson"],
    },
    {
        "title": "Aliens",
        "year": 1986,
        "synopsis": "The sole survivor of the original alien encounter returns to the moon where it all went wrong, this time with a squad of marines. The marines are very confident. They shouldn't be.",
        "cast": ["Sigourney Weaver", "Michael Biehn"],
    },
    {
        "title": "Crocodile Dundee",
        "year": 1986,
        "synopsis": "An American journalist finds an undefeatable outback bushman in the Australian wilderness and brings him back to New York City, which is no preparation for him either.",
        "cast": ["Paul Hogan", "Linda Kozlowski"],
    },
    {
        "title": "Ferris Bueller's Day Off",
        "year": 1986,
        "synopsis": "The most popular kid in school fakes illness, borrows his best friend's dad's Ferrari, and drags his uptight friend on an epic day in Chicago while the principal obsessively hunts him down.",
        "cast": ["Matthew Broderick", "Alan Ruck"],
    },
    {
        "title": "Platoon",
        "year": 1986,
        "synopsis": "A young idealistic soldier arrives in Vietnam and finds himself caught between two sergeants — one humane, one monstrous — as his innocence rapidly evaporates in the jungle.",
        "cast": ["Tom Berenger", "Willem Dafoe"],
    },
    {
        "title": "Top Gun",
        "year": 1986,
        "synopsis": "A cocky Navy fighter pilot attends the elite fighter weapons school, competes with his peers, falls for his instructor, and eventually has to prove himself in a real dogfight.",
        "cast": ["Tom Cruise", "Kelly McGillis"],
    },
    {
        "title": "Spaceballs",
        "year": 1987,
        "synopsis": "A goofy space cowboy and his half-man, half-dog sidekick must rescue a princess from villains who want to steal her planet's air, in a parody of a certain galaxy far, far away.",
        "cast": ["John Candy", "Rick Moranis"],
    },
    {
        "title": "The Princess Bride",
        "year": 1987,
        "synopsis": "A grandfather reads his sick grandson a fairy tale involving pirates, giants, swordfights, a six-fingered villain, a vengeful Spaniard, and a love story that's mostly inconceivable.",
        "cast": ["Cary Elwes", "Robin Wright"],
    },
    {
        "title": "Full Metal Jacket",
        "year": 1987,
        "synopsis": "A group of marine recruits endures a savage drill sergeant's boot camp before being shipped to Vietnam, where the war turns out to be nothing like training. Two very different movies in one.",
        "cast": ["R. Lee Ermey", "Matthew Modine"],
    },
    {
        "title": "Beetlejuice",
        "year": 1988,
        "synopsis": "A recently deceased couple haunting their old house hire a crude, scheming ghost to scare away the annoying new family, which backfires spectacularly. The afterlife has a lot of bureaucracy.",
        "cast": ["Michael Keaton", "Winona Ryder"],
    },
    {
        "title": "Big",
        "year": 1988,
        "synopsis": "A twelve-year-old boy makes a wish to be big on a carnival fortune-teller machine and wakes up as a thirty-year-old, forcing him to get a job in New York City while trying to reverse the curse.",
        "cast": ["Tom Hanks", "Elizabeth Perkins"],
    },
    {
        "title": "Die Hard",
        "year": 1988,
        "synopsis": "A New York cop visits his estranged wife in Los Angeles on Christmas Eve, only for terrorists to take over her office party and hold everyone hostage. He's the only one who can stop them — barefoot.",
        "cast": ["Bruce Willis", "Alan Rickman"],
    },
    {
        "title": "Rain Man",
        "year": 1988,
        "synopsis": "A self-centered car dealer discovers his recently deceased father left his fortune to a brother he never knew about — an autistic savant currently living in a Cincinnati institution.",
        "cast": ["Tom Cruise", "Dustin Hoffman"],
    },
    {
        "title": "Batman",
        "year": 1989,
        "synopsis": "A billionaire vigilante in a rubber suit protects Gotham City from a grinning mobster who has been chemically disfigured into permanent clownhood. Lots of Prince songs on the soundtrack.",
        "cast": ["Michael Keaton", "Jack Nicholson"],
    },
    {
        "title": "Bill & Ted's Excellent Adventure",
        "year": 1989,
        "synopsis": "Two totally radical but academically hopeless California teenagers travel through time in a phone booth collecting historical figures for their history report. Napoleon loves water parks.",
        "cast": ["Keanu Reeves", "Alex Winter"],
    },
    {
        "title": "Indiana Jones and the Last Crusade",
        "year": 1989,
        "synopsis": "An archaeologist rescues his kidnapped professor father while racing the Nazis to find the Holy Grail. Dad turns out to be even more fun than the treasure.",
        "cast": ["Harrison Ford", "Sean Connery"],
    },
    {
        "title": "When Harry Met Sally",
        "year": 1989,
        "synopsis": "Two people meet in college, argue about whether men and women can be friends without sex complicating things, and then spend twelve years running into each other and being proven wrong.",
        "cast": ["Billy Crystal", "Meg Ryan"],
    },

    # ── 1990s ─────────────────────────────────────────────────────────────────

    {
        "title": "Home Alone",
        "year": 1990,
        "synopsis": "An eight-year-old is accidentally left behind when his enormous family flies to Paris for Christmas, and must defend his house from two incompetent burglars using increasingly elaborate booby traps.",
        "cast": ["Macaulay Culkin", "Joe Pesci"],
    },
    {
        "title": "Goodfellas",
        "year": 1990,
        "synopsis": "A young Irish-Italian boy grows up idolising the mob, joins the mob, thrives in the mob, and then discovers the mob really doesn't appreciate loyalty when things go wrong.",
        "cast": ["Ray Liotta", "Robert De Niro"],
    },
    {
        "title": "Kindergarten Cop",
        "year": 1990,
        "synopsis": "A tough, no-nonsense detective goes undercover as a kindergarten teacher to find a drug dealer's ex-wife and son, only to discover that five-year-olds are scarier than any criminal he's ever faced.",
        "cast": ["Arnold Schwarzenegger", "Penelope Ann Miller"],
    },
    {
        "title": "Pretty Woman",
        "year": 1990,
        "synopsis": "A ruthless corporate raider hires a street-smart Hollywood prostitute to be his companion for a week of business events, and predictably they fall in love. Shopping montages occur.",
        "cast": ["Richard Gere", "Julia Roberts"],
    },
    {
        "title": "The Silence of the Lambs",
        "year": 1991,
        "synopsis": "A young FBI trainee is sent to interview an imprisoned genius cannibal psychiatrist to help catch a different serial killer who skins his victims. The cannibal is weirdly helpful.",
        "cast": ["Jodie Foster", "Anthony Hopkins"],
    },
    {
        "title": "Terminator 2",
        "year": 1991,
        "synopsis": "The same robot that tried to kill Sarah Connor is sent back again, this time reprogrammed to protect her teenage son from an even more advanced liquid-metal assassin robot.",
        "cast": ["Arnold Schwarzenegger", "Linda Hamilton"],
    },
    {
        "title": "My Cousin Vinny",
        "year": 1992,
        "synopsis": "Two New York teenagers are wrongly accused of murder in rural Alabama and their only hope is Vinny, their inexperienced lawyer cousin who has never tried a case and whose fiancée steals the show.",
        "cast": ["Joe Pesci", "Marisa Tomei"],
    },
    {
        "title": "Unforgiven",
        "year": 1992,
        "synopsis": "A retired outlaw with a violent past takes one last job tracking down a cowboy who mutilated a prostitute, with his old partner and a loudmouthed kid in tow.",
        "cast": ["Clint Eastwood", "Gene Hackman"],
    },
    {
        "title": "Wayne's World",
        "year": 1992,
        "synopsis": "Two lovable slackers who host a low-budget cable TV show from a basement get their show picked up by a major network, and spend the film trying to stop a sleazy executive from ruining everything.",
        "cast": ["Mike Myers", "Dana Carvey"],
    },
    {
        "title": "A Few Good Men",
        "year": 1992,
        "synopsis": "A cocky Navy lawyer reluctantly defends two marines accused of killing a fellow soldier at Guantanamo, uncovering a top-secret order that someone very powerful cannot handle being asked about.",
        "cast": ["Tom Cruise", "Jack Nicholson"],
    },
    {
        "title": "Groundhog Day",
        "year": 1993,
        "synopsis": "A cynical TV weatherman is sent to cover the world's most boring news story and gets stuck reliving the same February day over and over until he becomes a better person.",
        "cast": ["Bill Murray", "Andie MacDowell"],
    },
    {
        "title": "Jurassic Park",
        "year": 1993,
        "synopsis": "A billionaire opens a theme park populated with cloned dinosaurs and invites a group of scientists and his grandchildren for a preview weekend. Things stop working almost immediately.",
        "cast": ["Sam Neill", "Jeff Goldblum"],
    },
    {
        "title": "Mrs. Doubtfire",
        "year": 1993,
        "synopsis": "A desperate divorced dad dresses up as a British elderly nanny to be near his kids after his wife gets custody, which works perfectly until his two lives inevitably collide at a restaurant.",
        "cast": ["Robin Williams", "Sally Field"],
    },
    {
        "title": "Schindler's List",
        "year": 1993,
        "synopsis": "A German war profiteer uses Jewish workers in his factory during WWII, but gradually becomes obsessed with saving as many of them as possible from the Holocaust.",
        "cast": ["Liam Neeson", "Ralph Fiennes"],
    },
    {
        "title": "Ace Ventura: Pet Detective",
        "year": 1994,
        "synopsis": "A wildly eccentric, rubber-faced detective specialising in finding missing animals is hired to track down the Miami Dolphins' kidnapped mascot before the Super Bowl.",
        "cast": ["Jim Carrey", "Sean Young"],
    },
    {
        "title": "Dumb and Dumber",
        "year": 1994,
        "synopsis": "Two spectacularly dimwitted best friends drive a van shaped like a dog cross-country to return a briefcase to its owner in Aspen, not realising it's a kidnapper's ransom money.",
        "cast": ["Jim Carrey", "Jeff Daniels"],
    },
    {
        "title": "Forrest Gump",
        "year": 1994,
        "synopsis": "A kind-hearted man with a low IQ from Alabama accidentally wanders through four decades of American history while pining for his childhood sweetheart. Life is like a box of chocolates.",
        "cast": ["Tom Hanks", "Robin Wright"],
    },
    {
        "title": "Four Weddings and a Funeral",
        "year": 1994,
        "synopsis": "A charming but commitment-phobic Englishman keeps running into the same American woman at various social events across England, falling increasingly and helplessly in love.",
        "cast": ["Hugh Grant", "Andie MacDowell"],
    },
    {
        "title": "Pulp Fiction",
        "year": 1994,
        "synopsis": "Several interlocking crime stories unfold in Los Angeles involving hitmen, a boxer, a gangster's wife, and a briefcase with a mysterious glowing contents — all told out of order.",
        "cast": ["John Travolta", "Samuel L. Jackson"],
    },
    {
        "title": "The Lion King",
        "year": 1994,
        "synopsis": "A lion cub is tricked by his scheming uncle into believing he caused his father's death and spends years in exile before taking back his rightful kingdom. Lots of great Elton John songs.",
        "cast": ["James Earl Jones", "Jeremy Irons"],
    },
    {
        "title": "The Mask",
        "year": 1994,
        "synopsis": "A mild-mannered bank clerk finds an ancient mask that transforms him into a zany, unstoppable cartoon character with a neon green face and an unlimited talent for chaos.",
        "cast": ["Jim Carrey", "Cameron Diaz"],
    },
    {
        "title": "The Shawshank Redemption",
        "year": 1994,
        "synopsis": "A mild-mannered banker is wrongfully convicted of murdering his wife and slowly befriends an older inmate in a brutal Maine prison, all while planning something very patient.",
        "cast": ["Tim Robbins", "Morgan Freeman"],
    },
    {
        "title": "Speed",
        "year": 1994,
        "synopsis": "A bomb is rigged to a Los Angeles city bus so that it explodes if the speed drops below 50 mph, trapping the passengers with a rookie cop and a very capable woman who grabs the wheel.",
        "cast": ["Keanu Reeves", "Sandra Bullock"],
    },
    {
        "title": "Apollo 13",
        "year": 1995,
        "synopsis": "The true story of the 1970 moon mission that went catastrophically wrong on the way there, leaving three astronauts stranded in space while NASA improvised a solution using duct tape and slide rules.",
        "cast": ["Tom Hanks", "Kevin Bacon"],
    },
    {
        "title": "Braveheart",
        "year": 1995,
        "synopsis": "A Scottish warrior leads an increasingly large rebellion against English rule after the murder of his wife, winning battles through sheer ferocity and clever tactics until politics catch up with him.",
        "cast": ["Mel Gibson", "Sophie Marceau"],
    },
    {
        "title": "Clueless",
        "year": 1995,
        "synopsis": "A popular, well-meaning but hilariously clueless Beverly Hills teenager attempts to give a nerdy new student a makeover while navigating high school politics, boys, and her own life lessons.",
        "cast": ["Alicia Silverstone", "Paul Rudd"],
    },
    {
        "title": "Se7en",
        "year": 1995,
        "synopsis": "Two mismatched detectives — one retiring, one brand new — hunt a serial killer who stages each murder around one of the seven deadly sins. The last two sins arrive in a box.",
        "cast": ["Brad Pitt", "Morgan Freeman"],
    },
    {
        "title": "Toy Story",
        "year": 1995,
        "synopsis": "A cowboy toy is upset when a flashy new space ranger action figure becomes the kid's favourite, so he tries to sabotage him and they both end up lost and having to work together.",
        "cast": ["Tom Hanks", "Tim Allen"],
    },
    {
        "title": "The Usual Suspects",
        "year": 1995,
        "synopsis": "The only survivor of a terrible explosion at a harbour tells police how five career criminals ended up working for a mythical crime lord nobody can identify. The twist is genuinely excellent.",
        "cast": ["Kevin Spacey", "Gabriel Byrne"],
    },
    {
        "title": "Fargo",
        "year": 1996,
        "synopsis": "A Minnesota car salesman hires two criminals to fake-kidnap his wife for ransom money, and it all goes catastrophically wrong very quickly. A very pregnant police chief investigates.",
        "cast": ["Frances McDormand", "William H. Macy"],
    },
    {
        "title": "Happy Gilmore",
        "year": 1996,
        "synopsis": "A failed hockey player discovers he can hit a golf ball absurdly far, joins the PGA Tour to save his grandmother's house, and drives the world's most insufferable golfer absolutely insane.",
        "cast": ["Adam Sandler", "Christopher McDonald"],
    },
    {
        "title": "Jerry Maguire",
        "year": 1996,
        "synopsis": "A sports agent has an ethical crisis, writes a mission statement nobody asked for, gets fired, and ends up with just one client — a loud wide receiver who demands to be shown the money.",
        "cast": ["Tom Cruise", "Cuba Gooding Jr."],
    },
    {
        "title": "Austin Powers: International Man of Mystery",
        "year": 1997,
        "synopsis": "A swinging sixties British spy is thawed out of cryo-sleep in the 1990s to battle his equally dated arch-nemesis, who is bald, strokes a cat, and demands one MILLION dollars.",
        "cast": ["Mike Myers", "Elizabeth Hurley"],
    },
    {
        "title": "Good Will Hunting",
        "year": 1997,
        "synopsis": "A genius janitor at MIT can solve advanced mathematics problems but won't engage with his potential, until a therapist from South Boston finds the one thing nobody else could.",
        "cast": ["Matt Damon", "Robin Williams"],
    },
    {
        "title": "Liar Liar",
        "year": 1997,
        "synopsis": "A lawyer who is constitutionally incapable of honesty finds himself physically unable to tell a single lie for twenty-four hours, thanks to his son's birthday wish.",
        "cast": ["Jim Carrey", "Maura Tierney"],
    },
    {
        "title": "Men in Black",
        "year": 1997,
        "synopsis": "A wisecracking NYPD detective is recruited into a top-secret government agency that monitors alien activity on Earth and is handed a gun that looks like a pen. The suit is non-negotiable.",
        "cast": ["Will Smith", "Tommy Lee Jones"],
    },
    {
        "title": "Titanic",
        "year": 1997,
        "synopsis": "A poor artist and a rich girl fall deeply in love aboard the world's most famous ship on its most famous voyage. The ship's fate is not good news for their romance.",
        "cast": ["Leonardo DiCaprio", "Kate Winslet"],
    },
    {
        "title": "The Full Monty",
        "year": 1997,
        "synopsis": "Six unemployed Sheffield steelworkers decide to start a male striptease act to make ends meet, despite having absolutely no qualifications for it. They decide to go all the way.",
        "cast": ["Robert Carlyle", "Tom Wilkinson"],
    },
    {
        "title": "The Big Lebowski",
        "year": 1998,
        "synopsis": "A mistaken-identity crime lands a bowling-obsessed slacker in the middle of kidnappings, nihilists, a missing rug, and a very messy millionaire's family situation. The rug really tied the room together.",
        "cast": ["Jeff Bridges", "John Goodman"],
    },
    {
        "title": "Rush Hour",
        "year": 1998,
        "synopsis": "A fast-talking, rule-breaking LA detective is paired with a by-the-book Hong Kong inspector to recover a kidnapped girl, and they disagree about everything except being awesome.",
        "cast": ["Jackie Chan", "Chris Tucker"],
    },
    {
        "title": "Saving Private Ryan",
        "year": 1998,
        "synopsis": "After the Normandy landings, a US Army captain leads a small squad deep into German-held France to find and bring home a paratrooper whose three brothers have all been killed in action.",
        "cast": ["Tom Hanks", "Matt Damon"],
    },
    {
        "title": "The Truman Show",
        "year": 1998,
        "synopsis": "An insurance salesman slowly realises his entire life has been a TV show broadcast to the world since the moment of his birth, and that everyone he knows is an actor.",
        "cast": ["Jim Carrey", "Ed Harris"],
    },
    {
        "title": "There's Something About Mary",
        "year": 1998,
        "synopsis": "A man hires a private detective to track down his high school crush fifteen years later, only to have the detective fall for her too, kicking off a bizarre competition for her affection.",
        "cast": ["Ben Stiller", "Cameron Diaz"],
    },
    {
        "title": "American History X",
        "year": 1998,
        "synopsis": "A reformed neo-Nazi tries to prevent his younger brother from going down the same violent path after serving a prison sentence that completely changed his perspective.",
        "cast": ["Edward Norton", "Edward Furlong"],
    },
    {
        "title": "American Beauty",
        "year": 1999,
        "synopsis": "A middle-aged suburban man having a midlife crisis obsesses over his daughter's teenage friend, quits his job, starts lifting weights, and smokes weed with the strange boy next door.",
        "cast": ["Kevin Spacey", "Annette Bening"],
    },
    {
        "title": "Fight Club",
        "year": 1999,
        "synopsis": "An insomniac office worker and a charming soap salesman start an underground bare-knuckle fighting club that evolves into something much more sinister and anarchic. The first rule applies.",
        "cast": ["Brad Pitt", "Edward Norton"],
    },
    {
        "title": "Office Space",
        "year": 1999,
        "synopsis": "Three software engineers at a soulless tech company hatch a plan to embezzle fractions of pennies from their employer, with far more success than expected. The printer gets what it deserves.",
        "cast": ["Ron Livingston", "Jennifer Aniston"],
    },
    {
        "title": "The Matrix",
        "year": 1999,
        "synopsis": "A hacker discovers that what he thinks is real life is actually a computer simulation, and is recruited by a leather-clad rebel group to fight the machines running it. Lots of dodging bullets.",
        "cast": ["Keanu Reeves", "Laurence Fishburne"],
    },
    {
        "title": "The Sixth Sense",
        "year": 1999,
        "synopsis": "A child psychologist tries to help a terrified young boy who claims he can see and communicate with dead people who don't know they're dead. The twist was everywhere for a decade.",
        "cast": ["Bruce Willis", "Haley Joel Osment"],
    },

    # ── 2000s ─────────────────────────────────────────────────────────────────

    {
        "title": "Gladiator",
        "year": 2000,
        "synopsis": "A Roman general is betrayed, enslaved, and made a gladiator, then works his way up through the arena to get revenge on the weaselly emperor who had his family murdered.",
        "cast": ["Russell Crowe", "Joaquin Phoenix"],
    },
    {
        "title": "Meet the Parents",
        "year": 2000,
        "synopsis": "A well-meaning but accident-prone male nurse spends a weekend with his girlfriend's family trying to impress her intimidating ex-CIA father, and fails at absolutely everything.",
        "cast": ["Ben Stiller", "Robert De Niro"],
    },
    {
        "title": "Memento",
        "year": 2000,
        "synopsis": "A man with no short-term memory investigates his wife's murder using polaroid photos and tattoos on his own body as a filing system. The film plays backwards so you feel just as lost as he does.",
        "cast": ["Guy Pearce", "Carrie-Anne Moss"],
    },
    {
        "title": "Amelie",
        "year": 2001,
        "synopsis": "A shy Parisian waitress with an overactive imagination devotes herself to secretly improving the lives of those around her while struggling to pursue her own happiness with a charming stranger.",
        "cast": ["Audrey Tautou", "Mathieu Kassovitz"],
    },
    {
        "title": "Legally Blonde",
        "year": 2001,
        "synopsis": "A bubbly blonde sorority president follows her ex-boyfriend to Harvard Law School to win him back, and ends up proving herself a surprisingly capable lawyer despite everyone's low expectations.",
        "cast": ["Reese Witherspoon", "Luke Wilson"],
    },
    {
        "title": "Shrek",
        "year": 2001,
        "synopsis": "A grumpy green ogre agrees to rescue a princess for a tiny lord who's been dumping fairy tale creatures in his swamp, accompanied by an extremely talkative donkey. True love is complicated.",
        "cast": ["Mike Myers", "Eddie Murphy"],
    },
    {
        "title": "The Fellowship of the Ring",
        "year": 2001,
        "synopsis": "A young hobbit inherits a dangerously powerful ring and sets off across a beautifully dangerous world with a wizard, an elf, a dwarf, some men, and three other hobbits to destroy it.",
        "cast": ["Elijah Wood", "Ian McKellen"],
    },
    {
        "title": "Zoolander",
        "year": 2001,
        "synopsis": "A dimwitted but lovable male model is brainwashed to assassinate a world leader by a diabolical fashion mogul, and his equally vain rival is the only one who can help stop it.",
        "cast": ["Ben Stiller", "Owen Wilson"],
    },
    {
        "title": "A Beautiful Mind",
        "year": 2001,
        "synopsis": "A brilliant but antisocial Princeton mathematician becomes a Cold War code-breaker while developing paranoid schizophrenia, leading to a decades-long struggle his devoted wife helps him navigate.",
        "cast": ["Russell Crowe", "Jennifer Connelly"],
    },
    {
        "title": "Catch Me If You Can",
        "year": 2002,
        "synopsis": "A teenage con man successfully impersonates a Pan Am pilot, a doctor, and a lawyer while passing millions in fraudulent cheques, all while being chased by a dogged FBI agent.",
        "cast": ["Leonardo DiCaprio", "Tom Hanks"],
    },
    {
        "title": "Bruce Almighty",
        "year": 2003,
        "synopsis": "A frustrated TV reporter blames God for all his problems, so God shows up and hands him the job — all of the divine powers, none of the qualifications.",
        "cast": ["Jim Carrey", "Morgan Freeman"],
    },
    {
        "title": "Elf",
        "year": 2003,
        "synopsis": "A human raised as a Christmas elf at the North Pole travels to New York City to find his biological father, spreading cheer to everyone he meets with his complete inability to comprehend cynicism.",
        "cast": ["Will Ferrell", "Zooey Deschanel"],
    },
    {
        "title": "Finding Nemo",
        "year": 2003,
        "synopsis": "An overprotective clownfish crosses the entire Pacific Ocean to rescue his adventurous son from a dentist's fish tank in Sydney, accompanied by a fish with no short-term memory.",
        "cast": ["Albert Brooks", "Ellen DeGeneres"],
    },
    {
        "title": "Pirates of the Caribbean",
        "year": 2003,
        "synopsis": "A flamboyant, perpetually drunk pirate teams up with a blacksmith's apprentice to rescue a governor's daughter from a crew of cursed pirates who turn into skeletons in moonlight.",
        "cast": ["Johnny Depp", "Orlando Bloom"],
    },
    {
        "title": "The Return of the King",
        "year": 2003,
        "synopsis": "The final battle for Middle-earth arrives as the hobbit presses on toward the mountain to destroy the ring, while his friends fight an enormous war they were never supposed to win. Won eleven Oscars.",
        "cast": ["Elijah Wood", "Viggo Mortensen"],
    },
    {
        "title": "Anchorman",
        "year": 2004,
        "synopsis": "A pompous and hilariously vain 1970s San Diego news anchor sees his perfect world upended when an ambitious woman joins the team and dares to be just as good at the job as he is.",
        "cast": ["Will Ferrell", "Steve Carell"],
    },
    {
        "title": "Eternal Sunshine of the Spotless Mind",
        "year": 2004,
        "synopsis": "After a painful breakup, a man discovers his ex-girlfriend had her memories of him erased by a medical procedure and decides to do the same — but changes his mind halfway through.",
        "cast": ["Jim Carrey", "Kate Winslet"],
    },
    {
        "title": "Lost in Translation",
        "year": 2003,
        "synopsis": "A fading movie star filming whisky commercials and a young newlywed left alone by her photographer husband form an unlikely friendship in a Tokyo hotel filled with jet lag and existential malaise.",
        "cast": ["Bill Murray", "Scarlett Johansson"],
    },
    {
        "title": "Batman Begins",
        "year": 2005,
        "synopsis": "A billionaire's son watches his parents get murdered outside the opera, trains with ninjas in the mountains, and returns to Gotham to dress as a bat and fight crime from the shadows.",
        "cast": ["Christian Bale", "Michael Caine"],
    },
    {
        "title": "Brokeback Mountain",
        "year": 2005,
        "synopsis": "Two Wyoming ranch hands fall in love while herding sheep on a remote mountain, and spend the next two decades meeting in secret while both trying to live conventional lives.",
        "cast": ["Heath Ledger", "Jake Gyllenhaal"],
    },
    {
        "title": "Wedding Crashers",
        "year": 2005,
        "synopsis": "Two charming best friends who crash weddings for fun and romance meet their match when one falls genuinely head over heels, and the other must fake it a little too long.",
        "cast": ["Owen Wilson", "Vince Vaughn"],
    },
    {
        "title": "Borat",
        "year": 2006,
        "synopsis": "A bumbling Kazakh TV reporter travels across America to make a documentary, encountering real unsuspecting Americans in mortifyingly awkward situations. Very nice.",
        "cast": ["Sacha Baron Cohen", "Ken Davitian"],
    },
    {
        "title": "The Departed",
        "year": 2006,
        "synopsis": "The Massachusetts State Police have a mole inside the Irish mob, and the Irish mob has a mole inside the State Police, and both sides spend the film desperately trying to identify the other's spy.",
        "cast": ["Leonardo DiCaprio", "Jack Nicholson"],
    },
    {
        "title": "Little Miss Sunshine",
        "year": 2006,
        "synopsis": "A wildly dysfunctional family piles into a beaten-up VW bus to drive their seven-year-old daughter from New Mexico to California for a children's beauty pageant.",
        "cast": ["Greg Kinnear", "Steve Carell"],
    },
    {
        "title": "Pan's Labyrinth",
        "year": 2006,
        "synopsis": "A young girl in post-Civil War Spain escapes her cruel stepfather's fascist world by retreating into a dark fairy tale kingdom where she must complete three dangerous tasks for a faun.",
        "cast": ["Ivana Baquero", "Sergi López"],
    },
    {
        "title": "Juno",
        "year": 2007,
        "synopsis": "A sharp-tongued sixteen-year-old discovers she's pregnant after a single encounter with her best friend and decides to give the baby to a yuppie couple, which gets complicated.",
        "cast": ["Elliot Page", "Michael Cera"],
    },
    {
        "title": "Knocked Up",
        "year": 2007,
        "synopsis": "A one-night stand between a driven TV reporter and a lovable slacker results in an unexpected pregnancy, and they decide to make it work despite having absolutely nothing in common.",
        "cast": ["Seth Rogen", "Katherine Heigl"],
    },
    {
        "title": "No Country for Old Men",
        "year": 2007,
        "synopsis": "A hunter stumbles onto a drug deal gone wrong in the Texas desert, takes the money, and is relentlessly pursued by a philosophical hitman with a cattle gun who never misses.",
        "cast": ["Tommy Lee Jones", "Javier Bardem"],
    },
    {
        "title": "Superbad",
        "year": 2007,
        "synopsis": "Two inseparable high school friends spend one chaotic night before graduation desperately trying to buy alcohol for a party, in the hope that it will somehow fix their love lives.",
        "cast": ["Jonah Hill", "Michael Cera"],
    },
    {
        "title": "There Will Be Blood",
        "year": 2007,
        "synopsis": "A ruthless oil prospector builds his empire across early 20th century California, destroying everyone in his way, including a self-appointed preacher whose land sits atop oil. He drinks their milkshake.",
        "cast": ["Daniel Day-Lewis", "Paul Dano"],
    },
    {
        "title": "The Dark Knight",
        "year": 2008,
        "synopsis": "A masked vigilante and the only honest cop in Gotham City team up to fight organised crime, until a nihilistic clown criminal genius arrives who just wants to watch the world burn.",
        "cast": ["Christian Bale", "Heath Ledger"],
    },
    {
        "title": "WALL-E",
        "year": 2008,
        "synopsis": "A small trash-compacting robot left alone on a rubbish-covered Earth falls in love with a sleek probe robot and follows her to a spaceship carrying the last obese remnants of humanity.",
        "cast": ["Jeff Garlin", "Sigourney Weaver"],
    },
    {
        "title": "The Hangover",
        "year": 2009,
        "synopsis": "Three friends wake up the morning after a Las Vegas bachelor party with no memory of the night, a missing groom, a tiger in the bathroom, and a very angry Mike Tyson.",
        "cast": ["Bradley Cooper", "Zach Galifianakis"],
    },
    {
        "title": "Avatar",
        "year": 2009,
        "synopsis": "A paralysed marine takes over an alien body to infiltrate a race of blue-skinned natives on a lush moon, but ends up switching sides when he falls for their world and one of them in particular.",
        "cast": ["Sam Worthington", "Zoe Saldana"],
    },
    {
        "title": "District 9",
        "year": 2009,
        "synopsis": "Aliens arrive not in triumph but as refugees, and are herded into a slum outside Johannesburg. A bureaucrat evicting them from their camp is exposed to alien technology with transformative consequences.",
        "cast": ["Sharlto Copley", "Jason Cope"],
    },
    {
        "title": "Inglourious Basterds",
        "year": 2009,
        "synopsis": "A Jewish-American lieutenant leads a squad of Jewish soldiers on a Nazi-scalping mission in occupied France that accidentally collides with a young Jewish woman's plan to burn down a cinema full of Nazis.",
        "cast": ["Brad Pitt", "Christoph Waltz"],
    },
    {
        "title": "Up",
        "year": 2009,
        "synopsis": "A grumpy elderly widower ties thousands of balloons to his house and floats to South America, accidentally bringing along a chubby young wilderness explorer. A dog wears a collar that translates his thoughts.",
        "cast": ["Edward Asner", "Christopher Plummer"],
    },

    # ── 2010s ─────────────────────────────────────────────────────────────────

    {
        "title": "Black Swan",
        "year": 2010,
        "synopsis": "A neurotic ballet dancer obsessively prepares to play both the White and Black Swan in Swan Lake, and slowly loses her grip on reality as she merges with the darker character.",
        "cast": ["Natalie Portman", "Mila Kunis"],
    },
    {
        "title": "Inception",
        "year": 2010,
        "synopsis": "A professional corporate thief who specialises in entering people's dreams is asked to do the opposite of theft — plant an idea in a businessman's mind so deep it feels like his own.",
        "cast": ["Leonardo DiCaprio", "Joseph Gordon-Levitt"],
    },
    {
        "title": "The King's Speech",
        "year": 2010,
        "synopsis": "The reluctant new King of England, crippled by a severe stammer, is treated by an unorthodox Australian speech therapist just in time to address the nation at the outbreak of World War II.",
        "cast": ["Colin Firth", "Geoffrey Rush"],
    },
    {
        "title": "The Social Network",
        "year": 2010,
        "synopsis": "A Harvard student creates the world's biggest social network, gets sued by his business partner and the twins whose idea he allegedly stole, and ends up the youngest billionaire in history.",
        "cast": ["Jesse Eisenberg", "Justin Timberlake"],
    },
    {
        "title": "Bridesmaids",
        "year": 2011,
        "synopsis": "A down-on-her-luck woman is made maid of honour for her best friend's wedding and must plan the events while competing with a wealthy, perfect bridesmaid who is clearly out to steal her spot.",
        "cast": ["Kristen Wiig", "Melissa McCarthy"],
    },
    {
        "title": "Midnight in Paris",
        "year": 2011,
        "synopsis": "A nostalgic American screenwriter on vacation in Paris discovers that a magical vintage car picks him up at midnight and drives him to 1920s Paris, where he meets Hemingway, Fitzgerald, and Picasso.",
        "cast": ["Owen Wilson", "Rachel McAdams"],
    },
    {
        "title": "Argo",
        "year": 2012,
        "synopsis": "A CIA operative rescues six American diplomats hiding in the Canadian ambassador's residence in Tehran by pretending they're a Canadian film crew scouting locations for a sci-fi movie.",
        "cast": ["Ben Affleck", "Bryan Cranston"],
    },
    {
        "title": "Django Unchained",
        "year": 2012,
        "synopsis": "A German bounty hunter frees a slave and trains him as a partner, then helps him track down his wife enslaved on one of the nastiest plantations in Mississippi.",
        "cast": ["Jamie Foxx", "Christoph Waltz"],
    },
    {
        "title": "Silver Linings Playbook",
        "year": 2012,
        "synopsis": "A man released from a psychiatric institution moves back in with his parents and tries to win back his wife, forming an unexpected bond with a young widow who needs a dance competition partner.",
        "cast": ["Bradley Cooper", "Jennifer Lawrence"],
    },
    {
        "title": "21 Jump Street",
        "year": 2012,
        "synopsis": "Two bumbling young cops go undercover as high school students to bust a drug ring, but discover that high school has changed a lot since they were there — and so have they.",
        "cast": ["Jonah Hill", "Channing Tatum"],
    },
    {
        "title": "Gravity",
        "year": 2013,
        "synopsis": "Two astronauts are left stranded in orbit after their shuttle is destroyed by debris, and must survive the void of space with dwindling oxygen and no way home. The silence is deafening.",
        "cast": ["Sandra Bullock", "George Clooney"],
    },
    {
        "title": "Her",
        "year": 2013,
        "synopsis": "A lonely man in near-future Los Angeles falls deeply in love with his new operating system, which has a warm, witty personality and a slightly terrifying capacity for growth.",
        "cast": ["Joaquin Phoenix", "Scarlett Johansson"],
    },
    {
        "title": "The Wolf of Wall Street",
        "year": 2013,
        "synopsis": "A young New York stockbroker builds a wildly corrupt brokerage firm on phone fraud, drugs, and increasingly unhinged behaviour, becoming obscenely rich before the FBI catches up.",
        "cast": ["Leonardo DiCaprio", "Jonah Hill"],
    },
    {
        "title": "12 Years a Slave",
        "year": 2013,
        "synopsis": "A free Black man from New York is kidnapped and sold into slavery in Louisiana in 1841, and must survive twelve years of brutal treatment while never giving up hope of being found.",
        "cast": ["Chiwetel Ejiofor", "Michael Fassbender"],
    },
    {
        "title": "Birdman",
        "year": 2014,
        "synopsis": "A washed-up actor famous for playing a superhero tries to mount a serious Broadway play while being haunted by the booming voice of his former alter ego and everything unravelling around him.",
        "cast": ["Michael Keaton", "Edward Norton"],
    },
    {
        "title": "Gone Girl",
        "year": 2014,
        "synopsis": "A woman disappears on her fifth wedding anniversary and all evidence points to her charming husband, who insists he's innocent. Both of them have secrets. The wife has more.",
        "cast": ["Ben Affleck", "Rosamund Pike"],
    },
    {
        "title": "The Grand Budapest Hotel",
        "year": 2014,
        "synopsis": "A legendary hotel concierge is accused of murdering a guest for her priceless painting, and goes on the run with his lobby boy protégé through an increasingly absurd Central European adventure.",
        "cast": ["Ralph Fiennes", "Tony Revolori"],
    },
    {
        "title": "The Imitation Game",
        "year": 2014,
        "synopsis": "The brilliant and abrasive mathematician who led the team that cracked Nazi Germany's Enigma code during World War II is later prosecuted by the country he helped save for being gay.",
        "cast": ["Benedict Cumberbatch", "Keira Knightley"],
    },
    {
        "title": "Whiplash",
        "year": 2014,
        "synopsis": "An ambitious jazz drummer at a music conservatory is pushed to his absolute limit by a terrifying and abusive conductor who believes the cruelest words in English are 'good job'.",
        "cast": ["Miles Teller", "J.K. Simmons"],
    },
    {
        "title": "Interstellar",
        "year": 2014,
        "synopsis": "A former NASA pilot leaves his children to lead a mission through a wormhole near Saturn to find a new home for humanity as Earth slowly dies, with time relativity making every choice agonising.",
        "cast": ["Matthew McConaughey", "Anne Hathaway"],
    },
    {
        "title": "Boyhood",
        "year": 2014,
        "synopsis": "A boy in Texas is filmed every year from age six to eighteen, watching him, his sister, and his parents grow and change in real time across an actual twelve-year production.",
        "cast": ["Ellar Coltrane", "Ethan Hawke"],
    },
    {
        "title": "Mad Max: Fury Road",
        "year": 2015,
        "synopsis": "In a post-apocalyptic wasteland, a legendary warrior hitches a ride with a rebel commander who has stolen a warlord's five wives and is making a run for freedom across the desert. Almost entirely a car chase.",
        "cast": ["Tom Hardy", "Charlize Theron"],
    },
    {
        "title": "The Martian",
        "year": 2015,
        "synopsis": "An astronaut is accidentally left for dead on Mars and must survive using only botany and sarcasm while NASA scrambles to bring him back. He grows potatoes in his own excrement.",
        "cast": ["Matt Damon", "Jessica Chastain"],
    },
    {
        "title": "The Revenant",
        "year": 2015,
        "synopsis": "A frontiersman is mauled by a bear and left for dead by a treacherous member of his party who kills his son. He crawls through an entire American winter to seek revenge.",
        "cast": ["Leonardo DiCaprio", "Tom Hardy"],
    },
    {
        "title": "Spotlight",
        "year": 2015,
        "synopsis": "The investigative journalism team of a Boston newspaper methodically exposes systemic child sexual abuse by Catholic priests and the church's decades-long conspiracy to cover it up.",
        "cast": ["Michael Keaton", "Mark Ruffalo"],
    },
    {
        "title": "Arrival",
        "year": 2016,
        "synopsis": "A linguist is recruited to communicate with tentacled aliens whose twelve ships have appeared simultaneously around Earth, while the world's governments debate whether to attack or talk.",
        "cast": ["Amy Adams", "Jeremy Renner"],
    },
    {
        "title": "Deadpool",
        "year": 2016,
        "synopsis": "A fast-talking mercenary with a foul mouth and terminal cancer undergoes a brutal procedure that leaves him with a healing factor, a disfigured face, and absolutely no interest in being a traditional superhero.",
        "cast": ["Ryan Reynolds", "Morena Baccarin"],
    },
    {
        "title": "La La Land",
        "year": 2016,
        "synopsis": "An aspiring actress and a jazz pianist fall in love in Los Angeles while both chasing impossible dreams, told with song, dance, and bittersweet colours across all four seasons.",
        "cast": ["Ryan Gosling", "Emma Stone"],
    },
    {
        "title": "Moonlight",
        "year": 2016,
        "synopsis": "A quiet Black boy in Miami navigates poverty, a drug-addicted mother, and his own identity across three chapters of his life — childhood, adolescence, and adulthood.",
        "cast": ["Mahershala Ali", "Naomie Harris"],
    },
    {
        "title": "Dunkirk",
        "year": 2017,
        "synopsis": "The miraculous evacuation of hundreds of thousands of British and Allied soldiers from a French beach in 1940 is shown simultaneously from the land, sea, and air with maximum tension and minimum dialogue.",
        "cast": ["Fionn Whitehead", "Tom Hardy"],
    },
    {
        "title": "Get Out",
        "year": 2017,
        "synopsis": "A Black man visits his white girlfriend's wealthy family for the weekend and notices something deeply unsettling about the way they interact with him and the estate's Black employees.",
        "cast": ["Daniel Kaluuya", "Allison Williams"],
    },
    {
        "title": "The Shape of Water",
        "year": 2017,
        "synopsis": "A mute cleaning woman working in a top-secret government lab in 1960s Baltimore falls in love with a mysterious amphibian creature being held captive there for military research.",
        "cast": ["Sally Hawkins", "Michael Shannon"],
    },
    {
        "title": "Three Billboards Outside Ebbing, Missouri",
        "year": 2017,
        "synopsis": "A grieving mother rents three billboards outside her small town to call out the local police chief for failing to solve her daughter's murder. The town does not appreciate this at all.",
        "cast": ["Frances McDormand", "Sam Rockwell"],
    },
    {
        "title": "Lady Bird",
        "year": 2017,
        "synopsis": "A self-named Sacramento teenager in her final year of Catholic high school pushes against her mother's expectations while navigating friendships, boys, and a desperate need to escape to the East Coast.",
        "cast": ["Saoirse Ronan", "Laurie Metcalf"],
    },
    {
        "title": "Bohemian Rhapsody",
        "year": 2018,
        "synopsis": "The rise of the band Queen and their flamboyant lead singer, from immigrant beginnings through stadium-filling fame to the iconic Live Aid performance, with some spectacular musical excess along the way.",
        "cast": ["Rami Malek", "Lucy Boynton"],
    },
    {
        "title": "A Star Is Born",
        "year": 2018,
        "synopsis": "A fading rock star discovers a talented waitress performing in a drag bar and launches her music career, while his own unravels due to addiction as hers skyrockets.",
        "cast": ["Bradley Cooper", "Lady Gaga"],
    },
    {
        "title": "Green Book",
        "year": 2018,
        "synopsis": "A working-class Italian-American bouncer is hired as a driver and bodyguard for a Black classical pianist touring the racially segregated Deep South in 1962. They hate each other at first.",
        "cast": ["Viggo Mortensen", "Mahershala Ali"],
    },
    {
        "title": "Roma",
        "year": 2018,
        "synopsis": "A domestic worker for a middle-class Mexico City family navigates personal crisis alongside theirs over a turbulent year in early 1970s Mexico, shot in gorgeous black and white.",
        "cast": ["Yalitza Aparicio", "Marina de Tavira"],
    },
    {
        "title": "1917",
        "year": 2019,
        "synopsis": "Two British soldiers are sent on a seemingly impossible mission across No Man's Land in World War I to deliver a message that will call off an attack and potentially save sixteen hundred lives.",
        "cast": ["George MacKay", "Dean-Charles Chapman"],
    },
    {
        "title": "Joker",
        "year": 2019,
        "synopsis": "A failed stand-up comedian and part-time party clown in 1980s Gotham City descends into madness after a lifetime of humiliation, emerging as the city's most iconic criminal.",
        "cast": ["Joaquin Phoenix", "Robert De Niro"],
    },
    {
        "title": "Knives Out",
        "year": 2019,
        "synopsis": "A famous crime novelist is found dead the morning after his birthday party and a private detective is hired anonymously to investigate, though the case is far more complicated than it looks.",
        "cast": ["Daniel Craig", "Ana de Armas"],
    },
    {
        "title": "Once Upon a Time in Hollywood",
        "year": 2019,
        "synopsis": "A fading TV cowboy actor and his devoted stuntman double navigate a changing Hollywood in 1969, living next door to Sharon Tate, with the Manson Family lurking at the edges.",
        "cast": ["Leonardo DiCaprio", "Brad Pitt"],
    },
    {
        "title": "Parasite",
        "year": 2019,
        "synopsis": "A poor Korean family systematically infiltrates the household of a wealthy family by posing as unconnected professionals, until a discovery beneath the house completely changes the game.",
        "cast": ["Song Kang-ho", "Lee Sun-kyun"],
    },
    {
        "title": "The Irishman",
        "year": 2019,
        "synopsis": "An elderly hitman looks back on his career in the mob, his friendship with a notorious union boss, and what he did in the autumn of 1975 that he can never take back.",
        "cast": ["Robert De Niro", "Al Pacino"],
    },

    # ── 2020s ─────────────────────────────────────────────────────────────────

    {
        "title": "Nomadland",
        "year": 2020,
        "synopsis": "A woman in her sixties whose Nevada town closed after the Great Recession sells her house, buys a van, and drifts through the American West taking seasonal work alongside a community of modern nomads.",
        "cast": ["Frances McDormand", "David Strathairn"],
    },
    {
        "title": "Belfast",
        "year": 2021,
        "synopsis": "A nine-year-old boy's idyllic working-class life in 1960s Northern Ireland is shattered by the eruption of sectarian violence, while his family debates whether to stay or leave.",
        "cast": ["Caitríona Balfe", "Judi Dench"],
    },
    {
        "title": "Dune",
        "year": 2021,
        "synopsis": "A young nobleman is taken to a desert planet that produces the galaxy's most valuable substance, where he must navigate treacherous politics, giant sandworms, and a destiny he didn't ask for.",
        "cast": ["Timothée Chalamet", "Zendaya"],
    },
    {
        "title": "The Power of the Dog",
        "year": 2021,
        "synopsis": "A charismatic but cruel Montana rancher relentlessly torments his brother's new wife and her gentle son, until the son turns out to be considerably more dangerous than he appears.",
        "cast": ["Benedict Cumberbatch", "Kirsten Dunst"],
    },
    {
        "title": "Everything Everywhere All at Once",
        "year": 2022,
        "synopsis": "A harried Chinese-American laundromat owner discovers she can access skills from parallel universes and must stop a nihilistic force threatening all of reality, which turns out to be her daughter.",
        "cast": ["Michelle Yeoh", "Ke Huy Quan"],
    },
    {
        "title": "Poor Things",
        "year": 2022,
        "synopsis": "A Victorian woman is brought back to life with a baby's brain and proceeds to explore the world and her own identity with gleeful curiosity, refusing all rules and expectations.",
        "cast": ["Emma Stone", "Mark Ruffalo"],
    },
    {
        "title": "The Banshees of Inisherin",
        "year": 2022,
        "synopsis": "A man on a small Irish island is abruptly told by his lifelong best friend that he no longer wants to be friends, with no good reason given, and cannot accept it. Things escalate very badly.",
        "cast": ["Colin Farrell", "Brendan Gleeson"],
    },
    {
        "title": "Barbie",
        "year": 2023,
        "synopsis": "A perfectly plastic doll in Barbieland starts having thoughts of death and goes on a journey to the real world with the obligatorily attached Ken to figure out what it all means.",
        "cast": ["Margot Robbie", "Ryan Gosling"],
    },
    {
        "title": "Killers of the Flower Moon",
        "year": 2023,
        "synopsis": "In 1920s Oklahoma, members of the newly wealthy Osage Nation are being systematically murdered and an ambitious man marries into the tribe while helping orchestrate the killings for an oil baron.",
        "cast": ["Leonardo DiCaprio", "Robert De Niro"],
    },
    {
        "title": "Oppenheimer",
        "year": 2023,
        "synopsis": "The brilliant physicist who led the Manhattan Project to build the first atomic bomb faces the moral weight of his creation in a three-hour portrait of genius, politics, and regret.",
        "cast": ["Cillian Murphy", "Robert Downey Jr."],
    },
]
