# Word and definition pairs for Word Guesser.
# Definitions do not contain the answer word.
# 580+ entries spanning nouns, verbs, adjectives, and abstract concepts.

WORD_DEFINITIONS: list = [

    # ── Fruits ─────────────────────────────────────────────────────────────────
    ("papaya", "a tropical fruit shaped like an elongated melon, with edible orange flesh and small black seeds"),
    ("mango", "a sweet tropical fruit with juicy yellow-orange flesh surrounding a large flat seed"),
    ("avocado", "a pear-shaped tropical fruit with smooth, creamy green flesh and a large central pit"),
    ("guava", "a tropical fruit with thin green or yellow skin and sweet pink or white flesh, used in juices and jams"),
    ("lychee", "a small tropical fruit with a bumpy reddish shell, translucent white flesh, and a large dark seed"),
    ("persimmon", "a bright orange autumn fruit that is astringently bitter when unripe but honeyed when fully ripe"),
    ("quince", "a hard, fragrant, golden-yellow fruit related to apples and pears, almost always cooked before eating"),
    ("tamarind", "a tropical pod with sticky, sour-sweet brown pulp widely used in sauces, candy, and drinks"),
    ("pomegranate", "a round red fruit with tough skin containing hundreds of small seeds encased in juicy ruby-red arils"),
    ("kumquat", "a tiny oval citrus fruit eaten whole, skin and all, with a sweet peel and tart inner flesh"),
    ("fig", "a soft, pear-shaped fruit with purple or green skin and a sweet interior full of tiny crunchy seeds"),
    ("plantain", "a large starchy relative of the banana that must be cooked before eating"),
    ("starfruit", "a waxy yellow tropical fruit that forms a perfect five-pointed star shape when sliced crosswise"),
    ("feijoa", "an oval green fruit with gritty white flesh and a distinctive flavor blending guava, pineapple, and mint"),
    ("rambutan", "a tropical fruit covered in soft, hair-like red spines, with juicy white flesh similar to lychee"),
    ("jackfruit", "the world's largest tree-borne fruit, with a bumpy green exterior and many sweet yellow pods inside"),
    ("dragonfruit", "a tropical cactus fruit with vivid pink or yellow scaly skin and white or red speckled flesh"),
    ("durian", "a large spiky Southeast Asian fruit notorious for its powerful odor but prized for its rich, custardy taste"),
    ("cherimoya", "a green heart-shaped tropical fruit with creamy white flesh and rows of large black seeds"),
    ("sapodilla", "a small brown tropical fruit with a grainy texture and an intensely sweet, caramel-like flavor"),
    ("breadfruit", "a large round tropical fruit whose starchy white flesh resembles freshly baked bread when cooked"),
    ("jujube", "a small oval fruit with red or dark brown skin, resembling a date, eaten fresh or dried"),
    ("ackee", "a Caribbean fruit used as a vegetable in cooking, toxic and harmful if eaten before fully ripe"),
    ("soursop", "a large spiky tropical fruit with white fibrous flesh and a tart flavor used in smoothies"),
    ("longan", "a small tropical fruit closely related to lychee, with transparent sweet flesh around a dark seed"),
    ("mangosteen", "a purple tropical fruit with a thick rind and sweet-tart white segments inside, called the queen of fruits"),
    ("loquat", "a small yellow-orange fruit with a pleasantly tart flavor, grown in warm Mediterranean and Asian climates"),
    ("pawpaw", "a North American fruit with smooth greenish-yellow skin and soft, custardy yellow flesh"),

    # ── Vegetables ─────────────────────────────────────────────────────────────
    ("artichoke", "a thistle vegetable with layers of tough, spiny bracts whose fleshy bases and heart are edible"),
    ("fennel", "a plant with feathery fronds and a bulbous white base that has a distinctive mild licorice flavor"),
    ("kohlrabi", "a vegetable of the cabbage family with a swollen globe-shaped stem that is eaten raw or cooked"),
    ("celeriac", "a knobbly root vegetable with crisp, creamy flesh that tastes strongly of celery"),
    ("rutabaga", "a large, round root vegetable that is a natural hybrid of a turnip and a cabbage"),
    ("parsnip", "a creamy-white root vegetable shaped like a carrot, with a sweet, nutty flavor when roasted"),
    ("taro", "a tropical root vegetable with starchy, white, purple-flecked flesh, widely used in Pacific and Asian cooking"),
    ("jicama", "a crunchy, white-fleshed root vegetable with a mild, slightly sweet flavor, often eaten raw"),
    ("radicchio", "a red Italian leafy vegetable resembling cabbage, with a characteristically sharp, bitter flavor"),
    ("endive", "a leafy vegetable with pale, tightly packed, crisp leaves and a pleasantly bitter taste"),
    ("leek", "a vegetable related to the onion with a long cylindrical white stalk and flat, dark green leaves"),
    ("shallot", "a small, mild-flavored bulb related to the onion, with a subtly sweet and complex taste"),
    ("edamame", "young green soybeans served in their pods, typically steamed or boiled and salted as a snack"),
    ("cassava", "a starchy tropical root used to make tapioca and many staple foods in Africa and Asia"),
    ("chard", "a leafy vegetable with large, dark green leaves and often vividly colored red or yellow stems"),
    ("okra", "a long, green, ridged vegetable pod known for its mucilaginous texture, essential in gumbo"),
    ("chayote", "a pale green, pear-shaped vegetable related to squash, with mild, crisp white flesh"),
    ("daikon", "a long white Asian radish with a mild, slightly sweet flavor, used raw, pickled, or cooked"),
    ("watercress", "a semi-aquatic leafy plant with small dark green leaves and a sharp, peppery taste"),
    ("arugula", "a leafy green salad plant with a distinctive peppery, slightly bitter flavor"),
    ("rapini", "an Italian vegetable similar to broccoli, with thin stalks and small florets, notably bitter in taste"),
    ("salsify", "a root vegetable with long, thin skin and a delicate flavor sometimes likened to oysters"),
    ("purslane", "a succulent leafy plant with small oval leaves and a mild, slightly sour flavor, used in salads"),
    ("fiddlehead", "the tightly coiled young frond of a fern, harvested and eaten as a spring vegetable"),
    ("lovage", "a tall herb with a bold celery-like flavor, used in soups and stews"),

    # ── Animals ────────────────────────────────────────────────────────────────
    ("platypus", "a semi-aquatic Australian mammal with a duck-like bill, webbed feet, and a beaver-like tail that lays eggs"),
    ("echidna", "a spiny, egg-laying Australian mammal with a long toothless snout and a sticky tongue for eating ants"),
    ("capybara", "the world's largest rodent, native to South America, resembling a giant semi-aquatic guinea pig"),
    ("pangolin", "a scaly mammal that rolls into a tight ball when threatened, the most trafficked animal in the world"),
    ("axolotl", "a Mexican salamander that retains its feathery external gills and larval features throughout its entire life"),
    ("narwhal", "an Arctic whale whose male has a single long, spiraling tusk projecting from its head"),
    ("tapir", "a large, shy tropical forest mammal with a short flexible prehensile snout, distantly related to horses"),
    ("okapi", "a secretive African forest animal related to the giraffe, with a brown body and zebra-striped legs"),
    ("wolverine", "a stocky, ferocious member of the weasel family known for its tremendous strength relative to its size"),
    ("quokka", "a small, friendly-looking Australian marsupial famous for appearing to smile in photographs"),
    ("manatee", "a large, slow-moving aquatic mammal that grazes on seagrass in shallow tropical coastal waters"),
    ("wombat", "a stocky, burrowing Australian marsupial notable for producing cube-shaped droppings"),
    ("mandrill", "a large Old World monkey with a strikingly colorful red and blue face, found in African rainforests"),
    ("meerkat", "a small mongoose that lives in southern African groups and stands upright to scan for predators"),
    ("lemur", "a primate found only in Madagascar with large, reflective eyes and a long, often striped tail"),
    ("fossa", "the largest carnivore endemic to Madagascar, resembling a cross between a puma and a mongoose"),
    ("ocelot", "a small, graceful wild cat with spotted and striped fur, native to the forests of the Americas"),
    ("serval", "a slender African wild cat with exceptionally long legs, large upright ears, and a spotted coat"),
    ("numbat", "a small, striped Australian marsupial that feeds exclusively on termites using a long sticky tongue"),
    ("cassowary", "a large, flightless bird with a bony head crest and powerful legs, native to Australian rainforests"),
    ("lyrebird", "an Australian ground bird celebrated for its extraordinary ability to mimic almost any sound"),
    ("kakapo", "a large, nocturnal, flightless parrot from New Zealand that is critically endangered"),
    ("kookaburra", "an Australian kingfisher bird instantly recognized by its loud, rolling call that resembles human laughter"),
    ("gharial", "a critically endangered crocodilian from South Asia with an extremely long, narrow snout for catching fish"),
    ("mudskipper", "a fish that breathes atmospheric air through its skin and moves across mudflats using its fins"),
    ("hagfish", "a primitive, eel-like sea creature that produces enormous quantities of sticky slime as a defense"),
    ("lamprey", "a jawless fish that latches onto other fish with a circular sucker mouth lined with rasping teeth"),
    ("tardigrade", "a microscopic, eight-legged animal capable of surviving extreme heat, cold, radiation, and the vacuum of space"),
    ("olm", "a blind, cave-dwelling salamander from European karst systems that can live over a century without food"),
    ("shoebill", "a large, prehistoric-looking African bird with a massive clog-shaped bill, specialized for hunting lungfish"),
    ("potoo", "a nocturnal South American bird that disguises itself as a broken tree stump during the day"),
    ("blobfish", "a deep-sea fish that appears gelatinous and drooping at the surface due to extreme pressure change"),
    ("archerfish", "a tropical fish that hunts by shooting accurate jets of water to knock insects off branches above the water"),
    ("dugong", "a large, gentle marine mammal closely related to the manatee, found in warm coastal waters"),
    ("dingo", "a wild dog native to Australia, descended from domesticated Asian dogs brought thousands of years ago"),
    ("wallaby", "an Australian marsupial closely related to the kangaroo but considerably smaller in size"),
    ("bilby", "an endangered Australian marsupial with large rabbit-like ears, a pointed snout, and silky blue-grey fur"),
    ("quoll", "a spotted, carnivorous Australian marsupial with a pointed face and sharp teeth"),
    ("pronghorn", "a North American hoofed mammal resembling an antelope, capable of remarkable sustained speeds"),
    ("caracal", "a wild cat with distinctive long, tufted black ears, native to Africa and southwestern Asia"),
    ("binturong", "a shaggy Southeast Asian mammal with a prehensile tail whose scent is often described as popcorn"),
    ("aardvark", "a nocturnal African mammal with a pig-like snout, large ears, and a tongue adapted for licking up ants"),
    ("kudu", "a large African antelope with dramatic corkscrew horns and white vertical stripes on its sides"),
    ("oryx", "a large antelope with very long, straight horns and a pale coat, adapted to survive in desert conditions"),
    ("impala", "a medium-sized African antelope known for its spectacular leaps of up to three meters high"),
    ("kinkajou", "a nocturnal rainforest mammal related to raccoons with a prehensile tail, also called a honey bear"),
    ("coati", "a South American mammal with a long, flexible snout and a banded tail, related to the raccoon"),
    ("caiman", "a crocodilian reptile related to alligators, found throughout Central and South America"),
    ("chameleon", "a slow-moving lizard that can change its skin color and move each eye independently"),
    ("skink", "a type of lizard with a smooth, shiny body, small limbs, and a tendency to burrow"),
    ("tuatara", "a reptile from New Zealand that is the last survivor of an ancient order that lived alongside the dinosaurs"),
    ("tarsier", "a tiny nocturnal primate with enormous eyes fixed in its skull, found in Southeast Asian forests"),
    ("loris", "a small, slow-moving nocturnal primate with a powerful grip and, uniquely among primates, a toxic bite"),
    ("uakari", "a South American monkey with a bald, bright red face and a very short tail"),
    ("sifaka", "a Malagasy lemur that moves across the ground by hopping sideways upright on its hind legs"),
    ("mamba", "a fast-moving and highly venomous African snake, some species of which are among the deadliest in the world"),
    ("taipan", "a large, extremely venomous snake native to Australia, considered among the world's most dangerous"),
    ("anaconda", "the world's heaviest snake, a nonvenomous constrictor found near water in South American rainforests"),
    ("piranha", "a South American freshwater fish with powerful jaws and razor-sharp teeth"),
    ("barracuda", "a large, swift predatory fish with a long body, sharp teeth, and an intimidating appearance"),
    ("moray", "a large, often vividly colored eel that hides in reef crevices and ambushes passing prey"),
    ("nautilus", "a marine mollusk with a beautiful spiral shell divided into air-filled chambers used for buoyancy"),
    ("cuttlefish", "a marine cephalopod that can change color instantly and possesses a unique internal calcified structure"),
    ("remora", "a fish with a sucker disc on its head that attaches itself to sharks and other large marine animals"),
    ("salamander", "a moist-skinned amphibian resembling a lizard that typically breathes partly through its skin"),
    ("gecko", "a small, nocturnal lizard with adhesive toe pads allowing it to cling effortlessly to vertical surfaces"),
    ("iguana", "a large herbivorous lizard with a crest of spines along its back, native to tropical American forests"),
    ("warthog", "an African wild pig with a large head, upward-curving tusks, and distinctive facial warts"),
    ("porcupine", "a large rodent whose body is covered in sharp, detachable quills used as protection from predators"),
    ("anteater", "a toothless mammal with a long tubular snout and a sticky tongue for eating ants and termites"),
    ("armadillo", "a small American mammal encased in an armor of bony, jointed plates, able to roll into a ball"),
    ("quetzal", "a brilliantly colored Central American bird with iridescent green plumage and very long tail feathers"),
    ("roadrunner", "a fast-running ground bird of the American Southwest, famous for sprinting rather than flying"),
    ("hornbill", "a large tropical bird with a massive, often brightly colored bill and a bony casque on top"),
    ("toucan", "a tropical bird with a large, brightly colored beak that is lightweight despite its size"),
    ("ibis", "a long-legged wading bird with a long downward-curving bill, sacred in ancient Egypt"),
    ("pelican", "a large waterbird with a distinctive throat pouch used for catching and temporarily storing fish"),
    ("flamingo", "a wading bird with pink plumage, a bent bill, and a habit of standing on one leg in shallow water"),

    # ── Nature / Geography ─────────────────────────────────────────────────────
    ("sequoia", "one of the world's tallest and most massive living trees, native to the Sierra Nevada mountains"),
    ("mangrove", "a tropical coastal tree growing in saltwater with a tangle of exposed prop roots above the mudflat"),
    ("tundra", "a vast, flat, treeless biome in Arctic regions where the subsoil is permanently frozen"),
    ("savanna", "a tropical grassland with scattered trees, found across large parts of sub-Saharan Africa"),
    ("monsoon", "a seasonal reversal of wind direction that brings heavy rainfall to South and Southeast Asia"),
    ("glacier", "a large, slow-moving river of compacted ice formed from accumulated snowfall over centuries"),
    ("geyser", "a hot spring that periodically erupts, shooting a column of boiling water and steam into the air"),
    ("fjord", "a long, narrow coastal inlet with steep cliffs, formed by glacial erosion, common in Norway"),
    ("atoll", "a ring-shaped coral reef or chain of coral islands enclosing a shallow central lagoon"),
    ("archipelago", "a group or chain of islands scattered across a body of water"),
    ("lagoon", "a shallow body of water separated from the sea by a reef, sandbank, or narrow strip of land"),
    ("estuary", "a partly enclosed coastal body of water where a river meets the sea, mixing fresh and salt water"),
    ("delta", "a fan-shaped landform built up from sediment deposited at the mouth of a river"),
    ("gorge", "a narrow valley with steep, rocky walls, usually carved out by a river over time"),
    ("ravine", "a small, narrow, steep-sided valley typically formed by a stream"),
    ("plateau", "a large, elevated, flat-topped area of land that rises sharply above the surrounding terrain"),
    ("canyon", "a deep, narrow valley with steep sides, carved by a river or other geological forces over time"),
    ("caldera", "a large volcanic crater formed by the collapse of a volcano into its emptied magma chamber"),
    ("moraine", "a ridge of rock debris deposited at the edge or end of a glacier"),
    ("permafrost", "ground that remains frozen throughout the year, found in polar and alpine regions"),
    ("taiga", "the world's largest terrestrial biome, a vast belt of coniferous forest across the Northern Hemisphere"),
    ("steppe", "a large, flat, treeless grassland found across the interior of Eurasia"),
    ("mesa", "a flat-topped hill or mountain with steep, cliff-like sides, common in the American Southwest"),
    ("butte", "a steep-sided, flat-topped hill narrower than a mesa, rising abruptly from flat surrounding land"),
    ("sinkhole", "a depression in the ground caused by the collapse of a surface layer into an underground void"),
    ("stalactite", "a tapering mineral formation hanging from the ceiling of a cave, formed by dripping mineral-rich water"),
    ("stalagmite", "a tapering mineral column rising from the floor of a cave, formed by mineral deposits from dripping water"),
    ("aquifer", "an underground layer of permeable rock that holds and transmits groundwater"),
    ("tributary", "a river or stream that flows into a larger river or lake"),
    ("isthmus", "a narrow strip of land connecting two larger landmasses, with water on either side"),
    ("peninsula", "a piece of land almost entirely surrounded by water but connected to the mainland"),
    ("strait", "a narrow passage of water connecting two larger bodies of water"),
    ("bayou", "a slow-moving, marshy waterway found in the Gulf Coast region of the United States"),
    ("tidepool", "a shallow pool of seawater left in a rocky coastal area when the tide recedes"),
    ("rainforest", "a dense, humid forest with very high rainfall, found in tropical regions and containing exceptional biodiversity"),

    # ── Foods and Dishes ───────────────────────────────────────────────────────
    ("tiramisu", "an Italian dessert of layers of coffee-soaked ladyfinger biscuits and mascarpone cream"),
    ("baklava", "a Middle Eastern pastry of layers of filo filled with chopped nuts and sweetened with honey or syrup"),
    ("croissant", "a flaky, buttery, crescent-shaped pastry made from laminated dough"),
    ("brioche", "a rich, soft French bread made with eggs and butter, with a tender, golden crumb"),
    ("soufflé", "a baked French dish made with egg yolks and beaten egg whites that puff up dramatically in the oven"),
    ("mousse", "a light, airy dessert or savory dish made by folding whipped cream or egg whites into a flavored base"),
    ("ganache", "a smooth mixture of melted chocolate and warm cream used as a filling, frosting, or glaze"),
    ("truffle", "a prized subterranean fungus with an intensely earthy, aromatic flavor, used in luxury cooking"),
    ("praline", "a confection of nuts coated in caramelized sugar, originating in France"),
    ("madeleine", "a small, shell-shaped French sponge cake baked in a distinctive ridged mold"),
    ("eclair", "a long, finger-shaped French pastry filled with cream and topped with chocolate icing"),
    ("macaron", "a delicate French sandwich cookie made from almond meringue shells with a ganache or buttercream filling"),
    ("profiterole", "a small, round choux pastry puff filled with cream and usually drizzled with chocolate sauce"),
    ("cannoli", "a Sicilian pastry tube filled with sweetened ricotta cream, often studded with chocolate chips"),
    ("semifreddo", "an Italian semi-frozen dessert made with whipped cream, eggs, and sugar, firmer than mousse but softer than gelato"),
    ("gelato", "an Italian frozen dessert made with more milk than cream, churned more slowly than ice cream"),
    ("sorbet", "a frozen dessert made from sweetened water and fruit juice or puree, containing no dairy"),
    ("granita", "a coarsely textured Sicilian frozen dessert made from water, sugar, and flavoring"),
    ("parfait", "a layered dessert of ice cream, fruit, syrup, and whipped cream, served in a tall glass"),
    ("cobbler", "a baked American dessert of fruit topped with a thick, scone-like batter crust"),
    ("clafoutis", "a French baked dessert made by pouring a thick egg batter over fruit, traditionally cherries"),
    ("galette", "a flat, free-form French pastry or savory buckwheat crepe from Brittany"),
    ("pavlova", "a meringue-based dessert with a crisp shell and soft marshmallow interior, topped with cream and fruit"),
    ("meringue", "a sweet dessert topping or shell made by whipping egg whites with sugar until stiff and glossy"),
    ("mochi", "a soft, sticky Japanese confection made from glutinous rice, often filled with sweet bean paste"),
    ("gyoza", "a Japanese pan-fried dumpling with a thin wrapper and a filling of minced meat and vegetables"),
    ("tempura", "a Japanese technique of lightly batter-coating seafood or vegetables and deep-frying until crisp"),
    ("bibimbap", "a Korean rice bowl topped with vegetables, meat, egg, and spicy chili paste, mixed together before eating"),
    ("pho", "a Vietnamese noodle soup with a rich, clear broth, rice noodles, herbs, and sliced meat"),
    ("satay", "a Southeast Asian dish of seasoned, skewered, grilled meat served with a spiced peanut sauce"),
    ("rendang", "a rich, slow-cooked Indonesian dry curry made with beef and coconut milk with complex spices"),
    ("tagine", "a slow-cooked North African stew of meat and vegetables, named after the conical clay pot it cooks in"),
    ("moussaka", "a Greek baked casserole of layered eggplant, spiced ground meat, and béchamel sauce"),
    ("paella", "a Spanish rice dish cooked in a wide, shallow pan with saffron, seafood, chicken, or vegetables"),
    ("gazpacho", "a cold Spanish soup made from raw blended tomatoes, peppers, cucumber, and olive oil"),
    ("ratatouille", "a Provençal French stew of eggplant, zucchini, peppers, tomatoes, and herbs"),
    ("bouillabaisse", "a traditional Provençal seafood stew from Marseille, made with multiple types of fish and shellfish"),
    ("cassoulet", "a slow-cooked French casserole of white beans, sausage, and duck or pork confit"),
    ("fondue", "a Swiss dish of melted cheese kept warm in a communal pot, into which pieces of bread are dipped"),
    ("risotto", "a creamy Italian rice dish made by slowly adding hot broth and stirring continuously"),
    ("polenta", "an Italian dish of boiled ground cornmeal, served soft like porridge or set and then fried or baked"),
    ("gnocchi", "small Italian dumplings made from potato, semolina, or flour, served with sauce"),
    ("hummus", "a Middle Eastern dip made from blended chickpeas, tahini, lemon juice, and garlic"),
    ("falafel", "a deep-fried ball made from ground chickpeas or fava beans, seasoned with herbs and spices"),
    ("tzatziki", "a Greek sauce or dip made from strained yogurt, cucumber, garlic, and olive oil"),
    ("kimchi", "a traditional Korean side dish of salted, fermented vegetables, typically cabbage, seasoned with chili"),
    ("ceviche", "a raw seafood dish cured in citrus juice and mixed with onions, chili, and herbs"),
    ("empanada", "a baked or fried pastry filled with savory meat, cheese, or vegetables, popular in Latin America"),
    ("tamale", "a traditional Mesoamerican dish of masa dough filled with meat or cheese, wrapped and steamed in corn husks"),

    # ── Drinks ─────────────────────────────────────────────────────────────────
    ("espresso", "a concentrated coffee brewed by forcing hot water under pressure through finely ground coffee beans"),
    ("cappuccino", "an Italian coffee drink of espresso topped with equal parts steamed and foamed milk"),
    ("macchiato", "an espresso drink stained or marked with a small amount of foamed milk"),
    ("affogato", "an Italian dessert of a shot of hot espresso poured over a scoop of vanilla ice cream"),
    ("chai", "a spiced tea beverage originating in India, made with black tea, milk, and aromatic spices"),
    ("matcha", "a finely ground powder of specially grown Japanese green tea, whisked with hot water into a frothy drink"),
    ("kombucha", "a fermented, slightly fizzy drink made from sweetened tea using a live culture of bacteria and yeast"),
    ("kefir", "a fermented milk drink with a tart, slightly effervescent flavor, made using special grain cultures"),
    ("lassi", "a yogurt-based drink from India, served sweet with fruit or savory with salt and spices"),
    ("horchata", "a sweet, milky drink made from ground rice or tiger nuts, popular in Spain and Latin America"),
    ("kvass", "a lightly fermented Slavic beverage made from bread, with a sour, slightly yeasty flavor"),
    ("mead", "an alcoholic drink made by fermenting honey with water, sometimes with added fruits or spices"),
    ("absinthe", "a highly alcoholic, anise-flavored spirit made from herbs including wormwood, known for its green color"),
    ("vermouth", "a fortified wine flavored with botanicals, used as an ingredient in cocktails"),
    ("amaretto", "a sweet Italian liqueur with an almond flavor, made from almonds or apricot pits"),
    ("grenadine", "a sweet, bright red syrup made from pomegranate juice, used in cocktails and mocktails"),
    ("limoncello", "an Italian lemon liqueur from the Amalfi Coast, made by steeping lemon zest in grain alcohol"),
    ("calvados", "a French apple brandy distilled from cider, produced in the Normandy region"),

    # ── Verbs ──────────────────────────────────────────────────────────────────
    ("simmer", "to cook gently in liquid kept just below boiling point, with small bubbles slowly rising"),
    ("sauté", "to cook food quickly in a small amount of hot fat over relatively high heat"),
    ("marinate", "to soak food in a seasoned liquid mixture before cooking, to add flavor or tenderize it"),
    ("caramelize", "to heat sugar or natural sugars in food until they turn brown and develop a rich, complex flavor"),
    ("ferment", "to undergo a chemical change caused by microorganisms that turn sugars into alcohol or acids"),
    ("distill", "to purify a liquid or extract its essence by heating it to vapor and then condensing it back to liquid"),
    ("braise", "to cook food slowly in a small amount of liquid in a sealed pot, usually after browning it first"),
    ("poach", "to cook food gently by submerging it in barely simmering liquid"),
    ("meander", "to follow a winding and turning course with no clear destination or purpose"),
    ("trudge", "to walk with heavy, slow steps, typically because of exhaustion or difficult terrain"),
    ("saunter", "to walk in a slow, relaxed manner with an air of casual confidence"),
    ("scamper", "to run with quick, light steps, typically from excitement or to escape"),
    ("lumber", "to move in a slow, heavy, awkward manner"),
    ("waddle", "to walk with short steps and a swaying, side-to-side motion"),
    ("swagger", "to walk or behave with an exaggerated air of confidence and self-importance"),
    ("prance", "to move with high, springy, showy steps"),
    ("hobble", "to walk with difficulty, typically because of injury to the foot or leg"),
    ("gallop", "to run at the fastest pace, with a bounding stride in which all four feet are briefly off the ground"),
    ("hibernate", "to spend the winter in a dormant state with lowered body temperature and reduced metabolism"),
    ("migrate", "to move seasonally from one region or climate to another, especially of birds or other animals"),
    ("molt", "to shed old feathers, skin, or hair, making way for new growth"),
    ("forage", "to search widely for food or provisions"),
    ("stalk", "to pursue quietly and persistently, approaching prey without being detected"),
    ("ponder", "to think deeply and carefully about something, weighing it in the mind"),
    ("contemplate", "to think about something intently and at length, or to consider an action seriously"),
    ("deliberate", "to engage in long, careful consideration before making a decision"),
    ("speculate", "to form a theory or conjecture about something without firm evidence"),
    ("deduce", "to reach a conclusion by reasoning from general principles to a specific case"),
    ("infer", "to draw a conclusion from evidence and reasoning rather than explicit statement"),
    ("scrutinize", "to examine or inspect something very closely and thoroughly"),
    ("oscillate", "to move back and forth in a regular, rhythmic pattern"),
    ("vibrate", "to move continuously and rapidly to and fro; to quiver"),
    ("undulate", "to move with a smooth, wave-like rising and falling motion"),
    ("cascade", "to fall or pour down in large quantities rapidly, like a waterfall"),
    ("percolate", "to filter gradually through a porous surface or substance"),
    ("evaporate", "to turn from liquid into vapor, typically because of applied heat"),
    ("condense", "to change from a gaseous or vapor state back into liquid, typically through cooling"),
    ("crystallize", "to form into crystals, or to cause something abstract to take a definite shape"),
    ("corrode", "to gradually weaken or destroy something, especially a metal, through chemical action"),
    ("erode", "to gradually wear away the surface of something through the long action of wind, water, or other forces"),
    ("wither", "to become dry and shriveled, especially of a plant; to lose vitality and strength"),
    ("flourish", "to grow or develop in a healthy and vigorous way; to thrive"),
    ("germinate", "to begin to grow and put out shoots from a seed or spore"),
    ("blossom", "to produce flowers; to develop in a healthy or promising way"),
    ("swindle", "to use deception to deprive someone of money or possessions"),
    ("haggle", "to dispute or bargain persistently over the cost of something"),
    ("barter", "to exchange goods or services for other goods or services without using money"),
    ("pilfer", "to steal items of small value, especially on an ongoing basis"),
    ("hoard", "to accumulate and hide away a large stock of something, often secretly"),
    ("squander", "to waste money, time, or resources carelessly or foolishly"),
    ("covet", "to intensely desire something that belongs to someone else"),
    ("seethe", "to feel or show intense, barely controlled anger"),
    ("recoil", "to suddenly move back in fear, horror, or disgust"),
    ("flinch", "to make a slight involuntary movement in response to anticipated pain or a blow"),
    ("wince", "to make a slight grimace or shrinking movement as an expression of pain or distress"),
    ("writhe", "to twist or squirm in pain or extreme distress"),
    ("fumble", "to do something clumsily or unsurely, especially with one's hands"),
    ("bungle", "to carry out a task clumsily or incompetently"),
    ("flounder", "to struggle or stagger helplessly; to be in serious difficulty"),
    ("exacerbate", "to make something that is already bad worse"),
    ("mitigate", "to make something less severe, serious, or painful"),
    ("alleviate", "to partially remove or reduce the intensity of something painful or difficult"),
    ("procrastinate", "to delay or postpone doing something repeatedly, often out of habit"),
    ("prevaricate", "to speak or act evasively to avoid telling the truth"),
    ("equivocate", "to use ambiguous language to conceal the truth or avoid committing to a clear position"),
    ("improvise", "to create or perform something without preparation, using whatever is available"),
    ("extrapolate", "to extend or project known data or trends into an unknown area to predict or estimate"),
    ("vacillate", "to waver between different opinions or actions; to be indecisive"),
    ("gesticulate", "to use gestures, especially dramatic ones, instead of or in addition to speech"),
    ("illuminate", "to light up a space; or to clarify or explain something by shedding light on it"),
    ("corroborate", "to confirm or give support to a statement, theory, or finding"),
    ("exonerate", "to officially declare that someone is free from blame or criminal charges"),
    ("incarcerate", "to imprison or confine someone"),

    # ── Adjectives ─────────────────────────────────────────────────────────────
    ("translucent", "allowing light to pass through but not forming a clear image; semi-transparent"),
    ("iridescent", "showing luminous colors that change when seen from different angles"),
    ("luminescent", "emitting light not caused by heat, such as fluorescent or bioluminescent light"),
    ("phosphorescent", "emitting a faint glow in the dark after exposure to light, continuing after the light source is removed"),
    ("porous", "having tiny holes or pores through which liquids or gases may pass"),
    ("malleable", "easily shaped or molded without breaking; adaptable and capable of change"),
    ("brittle", "hard but easily broken or shattered when subjected to a sharp impact"),
    ("viscous", "having a thick, sticky consistency that resists flow"),
    ("buoyant", "able to float in water; cheerful and optimistic in disposition"),
    ("elastic", "able to stretch significantly and return to its original shape when released"),
    ("serene", "calm, peaceful, and untroubled; tranquil and at ease"),
    ("turbulent", "characterized by chaotic, unsteady movement; disturbed and unsettled"),
    ("tempestuous", "characterized by strong, conflicting emotion; very stormy"),
    ("placid", "not easily upset or excited; calm and peaceful in nature"),
    ("frenetic", "fast-moving and energetic in a rather wild and uncontrolled way"),
    ("lethargic", "affected by lethargy; sluggish, drowsy, and lacking in energy or enthusiasm"),
    ("euphoric", "feeling or expressing intense happiness and a sense of well-being"),
    ("melancholy", "a feeling of pensive sadness; gloomy and dejected"),
    ("parched", "extremely dry and thirsty; dried out from a severe lack of moisture"),
    ("arid", "excessively dry due to insufficient rainfall; lacking natural moisture"),
    ("verdant", "green with grass or other rich vegetation; fresh and flourishing"),
    ("lush", "growing richly and abundantly; luxuriously rich in vegetation"),
    ("frigid", "very cold in temperature; intensely chilly and lacking any warmth"),
    ("sweltering", "oppressively hot and humid; uncomfortably and suffocatingly warm"),
    ("balmy", "pleasantly warm and mild in temperature; gentle and refreshing"),
    ("tepid", "only slightly warm; lukewarm in temperature or in enthusiasm"),
    ("scalding", "very hot to the touch; hot enough to cause burns"),
    ("murky", "dark, dirty, and hard to see through, especially of water"),
    ("pellucid", "translucently clear; expressed or understood with great clarity"),
    ("brackish", "slightly salty, as is water in estuaries where rivers meet the sea"),
    ("saline", "containing or impregnated with salt; relating to a salt solution"),
    ("caustic", "able to burn or corrode organic tissue by chemical action; sarcastic and harsh"),
    ("volatile", "liable to change rapidly and unpredictably; also evaporating quickly at room temperature"),
    ("inert", "lacking the ability to move or act; chemically inactive"),
    ("dormant", "temporarily inactive; in a state of rest or sleep"),
    ("nascent", "just coming into existence; beginning to develop and not yet fully formed"),
    ("pristine", "in its original condition; unspoiled and free from contamination"),
    ("decrepit", "worn out or ruined because of age or neglect; elderly and weakened"),
    ("desolate", "empty, bare, and bleak; uninhabited and giving an impression of abandonment"),
    ("barren", "producing little or no vegetation; too poor in quality to support life"),
    ("gaunt", "lean and haggard from hunger, illness, or suffering; looking very thin and bony"),
    ("svelte", "slender and elegantly thin in build or outline"),
    ("rotund", "round and plump; fat or chubby in shape"),
    ("haggard", "looking exhausted and unwell from fatigue, worry, or prolonged suffering"),
    ("radiant", "sending out light; shining or glowing brightly; showing obvious happiness"),
    ("sallow", "having an unhealthy yellow or pale brown complexion"),
    ("ruddy", "having a healthy red color in the face, typically from outdoor activity"),
    ("lithe", "thin, supple, and graceful in movement"),
    ("sinewy", "lean and muscular; having tough, strong, well-developed muscles"),
    ("wizened", "shriveled or wrinkled with age"),
    ("maudlin", "self-pityingly or tearfully sentimental, often in an exaggerated way"),
    ("lachrymose", "tending to cause tears; tearful or weepy"),
    ("ebullient", "cheerful and full of energy; overflowing with enthusiasm"),
    ("effervescent", "vivacious and enthusiastic; also of liquids, containing bubbles of gas"),
    ("vivacious", "attractively lively and animated in manner or personality"),
    ("languid", "having a disinclination for physical or mental exertion; pleasantly relaxed"),
    ("torpid", "mentally or physically inactive; having lost the power of motion"),
    ("indolent", "wanting to avoid activity or exertion; habitually lazy"),
    ("diligent", "having or showing care and conscientiousness in one's work or duties"),
    ("assiduous", "showing great care, attention, and effort applied over a long period"),
    ("punctilious", "showing great attention to detail and correct behavior"),
    ("fastidious", "very attentive to accuracy and detail; difficult to please"),
    ("tenacious", "tending to keep a firm hold of something; persistent and determined"),
    ("vociferous", "expressing opinions in a loud or forceful manner"),
    ("audacious", "showing a willingness to take surprisingly bold risks"),
    ("magnanimous", "generous or forgiving, especially toward a rival or someone less powerful"),
    ("obsequious", "excessively willing to serve or please others in a way that seems insincere"),

    # ── Abstract Nouns ─────────────────────────────────────────────────────────
    ("empathy", "the ability to understand and share the feelings of another person"),
    ("altruism", "unselfish concern for the well-being of others; selfless benevolence"),
    ("narcissism", "excessive admiration of oneself and one's own physical appearance or qualities"),
    ("stoicism", "the endurance of pain or hardship without showing feelings or complaining"),
    ("cynicism", "an inclination to believe that people are motivated purely by self-interest"),
    ("pragmatism", "an approach that deals with practical facts and results rather than abstract theories"),
    ("nihilism", "the rejection of all religious and moral principles, in the belief that life is meaningless"),
    ("sovereignty", "supreme power or authority, especially of a state over its own affairs"),
    ("anarchy", "a state of disorder due to the absence or nonrecognition of authority"),
    ("oligarchy", "a system of government in which a small group of people holds power"),
    ("nostalgia", "a sentimental longing for or idealization of a past time or situation"),
    ("euphoria", "an intense feeling of happiness and self-confidence, often without a clear cause"),
    ("wanderlust", "a strong desire to travel and explore the world"),
    ("schadenfreude", "pleasure derived by someone from another person's misfortune"),
    ("zeitgeist", "the defining spirit or mood of a particular period in history as shown by its ideas"),
    ("angst", "a feeling of deep anxiety or dread, often about the state of the world"),
    ("malaise", "a general feeling of discomfort, illness, or unease whose exact cause is difficult to identify"),
    ("catharsis", "the process of releasing and providing relief from strong emotions, often through art or drama"),
    ("paradox", "a statement that seems contradictory or absurd but may actually be true"),
    ("allegory", "a story with a symbolic meaning beneath the literal one, representing deeper moral truths"),
    ("hyperbole", "an exaggerated statement not meant to be taken literally, used for emphasis or effect"),
    ("irony", "expressing meaning through language that signifies the opposite of what is stated"),
    ("sarcasm", "the use of irony to mock or convey contempt, often with a bitter or cutting tone"),
    ("alliteration", "the repetition of the same initial consonant sound in closely connected words"),
    ("onomatopoeia", "the use of a word that phonetically imitates or suggests the sound it describes"),
    ("oxymoron", "a figure of speech in which apparently contradictory terms are used in conjunction"),
    ("euphemism", "a mild or indirect word used in place of a harsh or blunt expression"),
    ("motif", "a recurring theme, pattern, or symbol in art, literature, or music"),
    ("archetype", "an original model or pattern from which copies are made; a universal symbol or character type"),
    ("soliloquy", "a speech made to oneself or to no one in particular, especially in a dramatic work"),
    ("elegy", "a poem of serious reflection, typically lamenting the death of a person"),
    ("epitaph", "a phrase or statement written in memory of a person, often inscribed on a tombstone"),
    ("requiem", "a mass for the souls of the dead; a musical composition for this"),
    ("anecdote", "a short, amusing, or interesting story about a real incident or person"),
    ("aphorism", "a pithy observation that contains a general truth"),

    # ── Objects and Tools ──────────────────────────────────────────────────────
    ("abacus", "an ancient counting frame with beads on rods, used for arithmetic calculations"),
    ("sundial", "a device that tells the time by the position of a shadow cast by the sun onto a marked dial"),
    ("sextant", "a navigational instrument used to measure the angle between two visible objects, especially stars"),
    ("periscope", "an optical instrument using mirrors to allow the user to see things otherwise out of direct sight"),
    ("kaleidoscope", "a tube-shaped toy with mirrors and colored glass that creates symmetrical patterns when rotated"),
    ("prism", "a transparent solid with flat surfaces that refracts and separates white light into its spectrum of colors"),
    ("hammock", "a hanging bed made of canvas or rope mesh, suspended between two supports"),
    ("pergola", "an outdoor garden structure with a framework of vertical posts and cross-beams, often supporting vines"),
    ("gazebo", "a freestanding roofed structure in a garden or park, open on all sides"),
    ("turret", "a small tower at the corner of a castle or building, often containing a staircase"),
    ("parapet", "a low protective wall along the edge of a roof, bridge, or balcony"),
    ("drawbridge", "a bridge over a moat that can be raised to prevent access or lowered to allow it"),
    ("catapult", "an ancient siege weapon for hurling large stones or heavy projectiles at fortifications"),
    ("trebuchet", "a type of catapult that uses a swinging counterweight to hurl large projectiles"),
    ("silo", "a tall cylindrical tower for storing grain, or an underground housing for missiles"),
    ("cistern", "a tank for storing water, especially one built underground or as part of a toilet system"),
    ("aqueduct", "a bridge-like structure carrying water across a valley or uneven ground over long distances"),
    ("portico", "a porch or covered walkway with a roof supported by columns forming an entrance to a building"),
    ("atrium", "the central courtyard of a Roman house, or a high central hall in a modern building"),
    ("alcove", "a recess or small section set back from the main area of a room"),
    ("rotunda", "a round building or room with a dome-shaped or circular roof"),
    ("obelisk", "a tapering, four-sided stone pillar with a pyramid-shaped apex, used as a monument"),
    ("sarcophagus", "a stone coffin, typically adorned with a sculpture or inscription and left above ground"),
    ("cenotaph", "a memorial built to honor a person whose remains are buried elsewhere"),
    ("reliquary", "an ornate container used to hold and display sacred relics"),
    ("amphora", "a tall ancient jar with two handles and a narrow neck, used for storing wine or olive oil"),
    ("brazier", "a portable heater containing burning coals or charcoal, used indoors or outdoors"),
    ("talisman", "an object believed to have magical properties that protect or bring good fortune to its wearer"),
    ("amulet", "an ornament or piece of jewelry worn as a charm against evil, illness, or harm"),
    ("totem", "a natural object or animal serving as an emblem of a clan, revered in many indigenous cultures"),
    ("labyrinth", "a complex network of paths or passages in which it is difficult to find one's way"),
    ("catacombs", "a network of underground tunnels and galleries used for burial"),
    ("ossuary", "a container or room into which the bones of many dead people are placed"),
    ("portcullis", "a heavy iron-grated gate that slides vertically in grooves to block the gateway of a castle"),
    ("moat", "a deep ditch filled with water surrounding a castle or fortress as a defensive measure"),

    # ── Science ────────────────────────────────────────────────────────────────
    ("catalyst", "a substance that increases the rate of a chemical reaction without being consumed in the process"),
    ("polymer", "a large molecule made up of many repeating smaller units bonded together, such as plastics or DNA"),
    ("isotope", "one of two or more forms of the same chemical element, differing only in the number of neutrons"),
    ("photon", "a particle representing a quantum of light or other electromagnetic radiation"),
    ("quark", "one of the fundamental particles that combine to make up hadrons such as protons and neutrons"),
    ("synapse", "the tiny gap between two nerve cells across which chemical or electrical signals pass"),
    ("mitosis", "the type of cell division producing two cells with the same number of chromosomes as the parent"),
    ("osmosis", "the passage of a solvent through a membrane from a dilute solution into a more concentrated one"),
    ("entropy", "a measure of disorder or randomness in a system, which tends to increase over time"),
    ("inertia", "the tendency of an object to remain at rest or keep moving unless acted on by an external force"),
    ("momentum", "the quantity of motion in a moving body, equal to the product of its mass and velocity"),
    ("trajectory", "the curved path followed by a projectile or other moving object through space"),
    ("parabola", "a symmetrical open curve formed when a cone is cut by a plane parallel to its side"),
    ("asymptote", "a line that a curve approaches but never actually reaches as it extends toward infinity"),
    ("algorithm", "a set of rules or instructions for solving a problem or performing a calculation"),
    ("recursion", "a method where a function calls itself as part of its own definition"),
    ("transistor", "a semiconductor device used to amplify or switch electronic signals"),
    ("fluorescence", "the emission of light by a substance that has absorbed light or other electromagnetic radiation"),
    ("bioluminescence", "the production and emission of light by a living organism"),
    ("photosynthesis", "the process by which plants use sunlight, water, and carbon dioxide to produce food and oxygen"),
    ("chlorophyll", "the green pigment in plants that absorbs sunlight to power the process of making food"),
    ("chromosome", "a threadlike structure in the cell nucleus carrying genetic information as sequences of genes"),
    ("phenotype", "the observable physical characteristics of an organism, as distinct from its genetic code"),
    ("genotype", "the complete set of genes or genetic makeup of an organism"),
    ("taxonomy", "the branch of science concerned with classifying organisms into named groups"),

    # ── Music ──────────────────────────────────────────────────────────────────
    ("crescendo", "a gradual increase in loudness in a piece of music"),
    ("staccato", "a musical direction to play each note in a short, sharply detached manner"),
    ("legato", "performed in a smooth, flowing manner without breaks between notes"),
    ("pizzicato", "a technique for stringed instruments where the strings are plucked with the fingers instead of bowed"),
    ("vibrato", "a rapid, slight variation in pitch in singing or playing, adding warmth and expressiveness"),
    ("tremolo", "a trembling or quavering effect in music, produced on an instrument or in singing"),
    ("cadence", "a sequence of chords providing a sense of ending or resolution in a musical phrase"),
    ("sonata", "a composition for one or two instruments, typically in several contrasting movements"),
    ("concerto", "a composition for a solo instrument accompanied by an orchestra"),
    ("fugue", "a contrapuntal composition in which a short theme is introduced and then repeated in overlapping voices"),
    ("cantata", "a vocal composition with instrumental accompaniment, typically in several movements"),
    ("nocturne", "a short composition of a pensive or dreamy character, especially for solo piano"),
    ("etude", "a short musical composition designed primarily for technical practice"),
    ("timbre", "the characteristic tone quality of a musical sound, apart from its pitch and volume"),
    ("portamento", "a smooth, continuous glide from one pitch to another in singing or on a stringed instrument"),
    ("glissando", "a continuous slide upward or downward between two notes"),
    ("syncopation", "a rhythmic effect placing emphasis on normally unaccented beats"),
    ("counterpoint", "the technique of combining two or more independent melodic lines simultaneously"),
    ("arpeggio", "the notes of a chord played in rapid succession rather than all at once"),
    ("ostinato", "a musical phrase or rhythm that is persistently repeated throughout a composition"),

    # ── Sports and Activities ──────────────────────────────────────────────────
    ("luge", "a sport in which a small sled is ridden feet-first at high speed down a specially built ice track"),
    ("biathlon", "a competitive event combining cross-country skiing and rifle marksmanship"),
    ("heptathlon", "a women's athletic contest consisting of seven track and field events"),
    ("decathlon", "a men's athletic contest consisting of ten track and field events over two days"),
    ("pentathlon", "an athletic contest comprising five disciplines, typically including running, jumping, and throwing"),
    ("velodrome", "a cycling track with steeply banked curves, designed for track racing"),
    ("regatta", "a series of boat or yacht races; a sporting event involving rowing or sailing"),
    ("steeplechase", "a race involving obstacles such as fences and water jumps, for horses or runners"),
    ("orienteering", "a competitive sport navigating between checkpoints across unfamiliar terrain using a map and compass"),
    ("parkour", "the activity of moving through an urban environment by running, jumping, and climbing over obstacles"),
    ("capoeira", "a Brazilian martial art that combines elements of dance, acrobatics, and music"),
    ("sumo", "a Japanese form of wrestling where a competitor wins by forcing their opponent out of the ring"),
    ("lacrosse", "a team sport played with a long-handled stick with a mesh basket and a small rubber ball"),
    ("curling", "a sport where players slide smooth stones across a sheet of ice toward a circular target area"),
    ("bobsled", "a sled with steering and braking mechanisms raced down an iced track at high speeds"),
    ("triathlon", "a race combining swimming, cycling, and running completed in immediate succession"),
    ("fencing", "the sport of fighting with thin swords, scoring points by touching the opponent with the blade"),
    ("archery", "the art and sport of shooting arrows with a bow at a target"),
    ("judo", "a Japanese martial art that uses throws and holds to overcome an opponent without striking"),
    ("motocross", "a form of motorcycle racing on a rough, closed off-road circuit"),

    # ── Miscellaneous ──────────────────────────────────────────────────────────
    ("amnesia", "a partial or total loss of memory, usually caused by brain injury, shock, or illness"),
    ("vertigo", "a sensation of dizziness in which the world appears to spin around the sufferer"),
    ("insomnia", "the persistent inability to fall asleep or stay asleep, leaving one tired during the day"),
    ("phobia", "an extreme or irrational fear of a particular object, class of objects, or situation"),
    ("paranoia", "a tendency to be excessively distrustful or suspicious of others without cause"),
    ("claustrophobia", "an extreme or irrational fear of confined or enclosed spaces"),
    ("agoraphobia", "an extreme fear of open or public places, often leading to avoidance of leaving home"),
    ("acrophobia", "an extreme or irrational fear of heights"),
    ("palindrome", "a word, phrase, or sequence that reads the same backward as forward"),
    ("anagram", "a word or phrase formed by rearranging all the letters of a different word or phrase"),
    ("acronym", "a word formed from the initial letters of a name or phrase and typically pronounced as a word"),
    ("mnemonic", "a pattern, rhyme, or phrase used to help remember something more easily"),
    ("cipher", "a secret code or method for writing messages in a way only readable with a key"),
    ("hieroglyph", "a picture used in a system of writing based on pictorial symbols, as used by the ancient Egyptians"),
    ("calligraphy", "the art of producing decorative or elegant handwriting with a pen or brush"),
    ("typography", "the art and technique of arranging type to make text legible and visually appealing"),
    ("graffiti", "writing or drawings scrawled illicitly on walls or other surfaces in public spaces"),
    ("collage", "an art form made by gluing various materials such as photographs and paper cuttings onto a surface"),
    ("mosaic", "a picture or decorative design made from small pieces of colored glass, stone, or tile"),
    ("fresco", "a method of mural painting done rapidly in watercolor on wet plaster"),
    ("chiaroscuro", "the use of strong contrasts between light and dark in drawing or painting"),
    ("silhouette", "the dark outline or shadow of an object, filled in with a single color against a light background"),
    ("caricature", "a picture in which someone's features are exaggerated for comic or critical effect"),
    ("filigree", "delicate ornamental work of fine silver, gold, or other wire, forming intricate patterns"),
    ("marquetry", "inlaid work of contrasting pieces of wood, metal, or other materials used for furniture decoration"),
    ("patina", "a green or brownish film that forms on bronze or copper; a sheen or gloss acquired by age"),
    ("porcelain", "a white, translucent ceramic produced by firing kaolin at very high temperatures"),
    ("terracotta", "a hard, brownish-red earthenware used for pottery, building tiles, and sculpture"),
    ("obsidian", "a hard, dark, glassy volcanic rock formed by the rapid solidification of lava"),
    ("onyx", "a gemstone consisting of layered bands of different colors, often black and white"),
    ("jasper", "an opaque variety of quartz, typically red, yellow, or brown, used as a gemstone"),
    ("turquoise", "a blue-green mineral used as a gemstone, prized in many cultures throughout history"),
    ("amber", "fossilized tree resin, typically yellow or orange, sometimes containing ancient preserved insects"),
    ("ivory", "the hard, creamy-white material forming elephant tusks, historically used in carvings"),
    ("ebony", "a very hard, dense black wood from a tropical tree, valued for fine furniture and musical instruments"),
    ("mahogany", "a straight-grained, reddish-brown tropical hardwood widely used in fine furniture"),
    ("velvet", "a closely woven fabric with a short, dense pile giving it a soft and luxurious feel"),
    ("satin", "a smooth, glossy fabric with a lustrous surface on one side, typically made from silk or synthetic fibers"),
    ("chiffon", "a light, very sheer fabric with a slightly rough texture, made from silk, nylon, or rayon"),
    ("tulle", "a fine, soft netting used for dresses, veils, and ballet costumes"),
    ("tweed", "a rough-surfaced woolen cloth in a heavy weave, traditionally worn for outdoor activities"),
    ("tartan", "a woolen cloth woven in a crisscross pattern of colored stripes, associated with Scottish clans"),
    ("gingham", "lightweight plain-woven cotton cloth, typically with a check or striped pattern"),
    ("damask", "a reversible patterned fabric with a design formed by contrasting glossy and matte surfaces"),
    ("brocade", "a rich fabric woven with a raised pattern, often incorporating metallic gold or silver thread"),
    ("boulevard", "a wide road in a town or city, typically one lined with trees"),
    ("promenade", "a paved public walk, typically alongside a seafront; or a leisurely stroll"),
    ("esplanade", "a long, open, level area beside the sea or a river, along which people walk for pleasure"),
    ("colonnade", "a row of evenly spaced columns supporting a roof or forming part of a building"),
    ("cloister", "a covered walk in a convent or monastery, with a wall on one side and an open colonnade on the other"),
    ("nave", "the central part of a church building intended to accommodate most of the congregation"),
    ("apse", "a large semicircular or polygonal recess at the east end of a church, typically with a domed roof"),
    ("buttress", "a projecting support built against a wall to strengthen or reinforce it"),
    ("rampart", "a defensive wall or mound of earth built around a castle or town for protection"),
    ("bastion", "a projecting part of a fortification that allows defensive fire in many directions"),
    ("battlement", "a parapet at the top of a wall with alternating raised sections and gaps, used in fortifications"),
]
