"""
All items for the In Common game.
Each item has a 'text' (what's shown to players) and a 'category' tag.
"""

ITEMS = [
    # ── FOOD & DRINK ──────────────────────────────────────────────────────────
    {"text": "cilantro on everything", "category": "food"},
    {"text": "pineapple on pizza", "category": "food"},
    {"text": "black licorice", "category": "food"},
    {"text": "blue cheese that smells like feet", "category": "food"},
    {"text": "oysters straight from the shell", "category": "food"},
    {"text": "eating food past the expiration date and not caring", "category": "food"},
    {"text": "very rare steak, still mooing", "category": "food"},
    {"text": "cooking with obscene amounts of butter", "category": "food"},
    {"text": "eating the same meal every single day", "category": "food"},
    {"text": "breakfast for dinner", "category": "food"},
    {"text": "cereal at midnight", "category": "food"},
    {"text": "extremely bitter coffee with absolutely nothing in it", "category": "food"},
    {"text": "decaf coffee (why even bother)", "category": "food"},
    {"text": "energy drinks as a personality trait", "category": "food"},
    {"text": "kombucha", "category": "food"},
    {"text": "green smoothies that look like pond water", "category": "food"},
    {"text": "vegan cheese", "category": "food"},
    {"text": "ranch dressing on everything, including pizza", "category": "food"},
    {"text": "hot sauce on everything, including scrambled eggs", "category": "food"},
    {"text": "very overripe bananas", "category": "food"},
    {"text": "candy corn", "category": "food"},
    {"text": "raisins in cookies (the great betrayal)", "category": "food"},
    {"text": "mushrooms (the texture, mostly)", "category": "food"},
    {"text": "mayonnaise in large quantities", "category": "food"},
    {"text": "anchovies", "category": "food"},
    {"text": "well-done steak, grey all the way through", "category": "food"},
    {"text": "ketchup on scrambled eggs", "category": "food"},
    {"text": "gas station sushi", "category": "food"},
    {"text": "food that is either scalding hot or ice cold, nothing in between", "category": "food"},
    {"text": "eating at chain restaurants, completely unironically", "category": "food"},
    {"text": "ordering the exact same thing every time at a restaurant", "category": "food"},
    {"text": "meal prepping on Sunday for the whole week", "category": "food"},
    {"text": "eating cereal dry, like an animal", "category": "food"},
    {"text": "dunking cookies in milk until they fall apart", "category": "food"},
    {"text": "marmite", "category": "food"},
    {"text": "durian fruit", "category": "food"},
    {"text": "natto (fermented soybeans)", "category": "food"},
    {"text": "fermented foods in general", "category": "food"},
    {"text": "fast food as comfort food, no shame", "category": "food"},
    {"text": "gas station hot dogs", "category": "food"},
    {"text": "putting sugar in grits", "category": "food"},
    {"text": "putting salt in oatmeal", "category": "food"},
    {"text": "spicy food that makes you cry and you love it", "category": "food"},
    {"text": "eating standing over the sink when alone", "category": "food"},
    {"text": "trying random foods from international grocery stores", "category": "food"},
    {"text": "cheap beer with no apologies", "category": "food"},
    {"text": "craft beer with extensive tasting notes", "category": "food"},
    {"text": "natural wine that tastes a little funky", "category": "food"},
    {"text": "drinking at brunch as a form of self-care", "category": "food"},
    {"text": "not drinking alcohol at all", "category": "food"},
    {"text": "sweet tea from the South", "category": "food"},
    {"text": "unsweetened iced tea (not the same thing as sweet tea)", "category": "food"},
    {"text": "bubble tea with the tapioca pearls", "category": "food"},
    {"text": "putting cream and sugar in tea", "category": "food"},
    {"text": "drinking multiple cups of coffee before 9am", "category": "food"},
    {"text": "room temperature beverages", "category": "food"},
    {"text": "ice in everything, even when it's cold outside", "category": "food"},
    {"text": "sparkling water as a personality type", "category": "food"},
    {"text": "protein shakes that taste like chalk", "category": "food"},
    {"text": "expensive juice cleanses", "category": "food"},
    {"text": "cold pizza for breakfast", "category": "food"},
    {"text": "leftover Chinese food straight from the container", "category": "food"},
    {"text": "eating with your hands whenever possible", "category": "food"},
    {"text": "food trucks as a lifestyle", "category": "food"},
    {"text": "deconstructed food at restaurants", "category": "food"},
    {"text": "tipping generously no matter what", "category": "food"},
    {"text": "splitting the bill to the exact penny", "category": "food"},
    {"text": "insisting on going to the same restaurant every time", "category": "food"},
    {"text": "taking photos of every meal before eating", "category": "food"},
    {"text": "eating in total silence and enjoying it", "category": "food"},
    {"text": "eating very slowly, savoring every bite", "category": "food"},
    {"text": "eating extremely fast, it's gone in four minutes", "category": "food"},
    {"text": "leaving a completely clean plate, not a crumb in sight", "category": "food"},
    {"text": "leaving food on the plate on principle", "category": "food"},
    {"text": "the burnt bits at the bottom of the pan", "category": "food"},
    {"text": "licking the bowl", "category": "food"},

    # ── SENSORY & PHYSICAL ────────────────────────────────────────────────────
    {"text": "the smell of musty old books", "category": "sensory"},
    {"text": "the smell of gasoline", "category": "sensory"},
    {"text": "the smell of petrichor (rain hitting dry earth)", "category": "sensory"},
    {"text": "the smell of old libraries", "category": "sensory"},
    {"text": "the smell of someone else's shampoo when they walk by", "category": "sensory"},
    {"text": "the feeling of sand between your toes", "category": "sensory"},
    {"text": "wet socks", "category": "sensory"},
    {"text": "the sound of rain at night", "category": "sensory"},
    {"text": "a thunderstorm while you're inside", "category": "sensory"},
    {"text": "very hot showers that are almost too hot", "category": "sensory"},
    {"text": "cold showers as a discipline thing", "category": "sensory"},
    {"text": "complete silence (some find it peaceful, others unsettling)", "category": "sensory"},
    {"text": "white noise machines or fans to sleep", "category": "sensory"},
    {"text": "sleeping with a window open even in winter", "category": "sensory"},
    {"text": "weighted blankets", "category": "sensory"},
    {"text": "the sound of crickets at night", "category": "sensory"},
    {"text": "silence so total you can hear your own heartbeat", "category": "sensory"},
    {"text": "popping bubble wrap", "category": "sensory"},
    {"text": "the crack of a really good back adjustment", "category": "sensory"},
    {"text": "cracking your own knuckles", "category": "sensory"},
    {"text": "peeling dried glue off your hands", "category": "sensory"},
    {"text": "the texture of velvet", "category": "sensory"},
    {"text": "corduroy (the sound it makes when your legs rub)", "category": "sensory"},
    {"text": "extra fluffy, impossibly soft towels", "category": "sensory"},
    {"text": "rough, scratchy towels", "category": "sensory"},
    {"text": "sleeping in a very cold room under a heavy blanket", "category": "sensory"},
    {"text": "the feeling of grass under bare feet", "category": "sensory"},
    {"text": "the smell of chlorine at a swimming pool", "category": "sensory"},
    {"text": "the smell of a hardware store", "category": "sensory"},
    {"text": "burning firewood smell", "category": "sensory"},
    {"text": "scented candles in every room", "category": "sensory"},
    {"text": "incense smoke", "category": "sensory"},
    {"text": "patchouli oil", "category": "sensory"},
    {"text": "the sound of vinyl records crackling", "category": "sensory"},
    {"text": "ASMR videos", "category": "sensory"},
    {"text": "the feeling of static electricity in the air before a storm", "category": "sensory"},
    {"text": "the smell of sunscreen", "category": "sensory"},
    {"text": "the smell of the season changing (specifically fall)", "category": "sensory"},
    {"text": "the specific smell of a library", "category": "sensory"},

    # ── ACTIVITIES & HOBBIES ──────────────────────────────────────────────────
    {"text": "going for long hikes with no destination in mind", "category": "hobbies"},
    {"text": "camping with absolutely zero electricity", "category": "hobbies"},
    {"text": "glamping (camping but make it bougie)", "category": "hobbies"},
    {"text": "gardening and talking to your plants", "category": "hobbies"},
    {"text": "staying in on Friday nights by choice", "category": "hobbies"},
    {"text": "going out every single weekend", "category": "hobbies"},
    {"text": "binge-watching entire seasons in one day", "category": "hobbies"},
    {"text": "rewatching the same comfort shows on a loop", "category": "hobbies"},
    {"text": "playing board games for four-plus hours", "category": "hobbies"},
    {"text": "escape rooms", "category": "hobbies"},
    {"text": "karaoke, completely sober", "category": "hobbies"},
    {"text": "thrift shopping as a competitive sport", "category": "hobbies"},
    {"text": "doing puzzles (1000 pieces minimum)", "category": "hobbies"},
    {"text": "crossword puzzles in pen", "category": "hobbies"},
    {"text": "Wikipedia rabbit holes at 2am", "category": "hobbies"},
    {"text": "journaling every single day", "category": "hobbies"},
    {"text": "reading multiple books at the same time", "category": "hobbies"},
    {"text": "buying physical books even though your shelf is already full", "category": "hobbies"},
    {"text": "e-readers only, never physical books", "category": "hobbies"},
    {"text": "going to movies alone", "category": "hobbies"},
    {"text": "going to restaurants alone", "category": "hobbies"},
    {"text": "traveling solo", "category": "hobbies"},
    {"text": "planning every detail of a trip months in advance", "category": "hobbies"},
    {"text": "winging it completely when traveling (no hotel booked)", "category": "hobbies"},
    {"text": "taking naps during the day without guilt", "category": "hobbies"},
    {"text": "waking up before 6am because you enjoy it", "category": "hobbies"},
    {"text": "staying up past 2am as a lifestyle", "category": "hobbies"},
    {"text": "meditation (the serious kind, 20 minutes daily)", "category": "hobbies"},
    {"text": "cold plunges and ice baths", "category": "hobbies"},
    {"text": "saunas", "category": "hobbies"},
    {"text": "going to farmers markets every weekend", "category": "hobbies"},
    {"text": "visiting museums alone and taking way too long", "category": "hobbies"},
    {"text": "birdwatching", "category": "hobbies"},
    {"text": "stargazing", "category": "hobbies"},
    {"text": "fishing", "category": "hobbies"},
    {"text": "hunting", "category": "hobbies"},
    {"text": "playing video games for entire days", "category": "hobbies"},
    {"text": "watching other people play video games (streamers)", "category": "hobbies"},
    {"text": "doomscrolling before bed", "category": "hobbies"},
    {"text": "doing nothing and calling it self-care", "category": "hobbies"},
    {"text": "pottery classes", "category": "hobbies"},
    {"text": "painting classes with wine", "category": "hobbies"},
    {"text": "taking cooking classes", "category": "hobbies"},
    {"text": "learning languages as a hobby", "category": "hobbies"},
    {"text": "playing an instrument alone in your room", "category": "hobbies"},
    {"text": "road trips with no particular destination", "category": "hobbies"},
    {"text": "taking the long way home on purpose", "category": "hobbies"},
    {"text": "collecting things (records, vintage stuff, etc.)", "category": "hobbies"},
    {"text": "going to thrift stores and buying strangers' old photographs", "category": "hobbies"},
    {"text": "attending Renaissance fairs", "category": "hobbies"},
    {"text": "comic-con and similar conventions", "category": "hobbies"},
    {"text": "antique shopping", "category": "hobbies"},
    {"text": "going to garage sales on Saturday mornings", "category": "hobbies"},
    {"text": "DIY everything instead of hiring someone", "category": "hobbies"},
    {"text": "never DIYing anything, immediately hiring someone", "category": "hobbies"},
    {"text": "extreme couponing", "category": "hobbies"},
    {"text": "skinny dipping", "category": "hobbies"},
    {"text": "hot tub parties", "category": "hobbies"},
    {"text": "running marathons", "category": "hobbies"},
    {"text": "doing obstacle course races (Tough Mudder, Spartan, etc.)", "category": "hobbies"},
    {"text": "hiking in silence, no talking allowed", "category": "hobbies"},
    {"text": "playing poker for money", "category": "hobbies"},
    {"text": "fantasy sports leagues", "category": "hobbies"},
    {"text": "making extremely detailed to-do lists", "category": "hobbies"},
    {"text": "never making lists, living in chaos", "category": "hobbies"},
    {"text": "tracking everything (steps, sleep, calories, water)", "category": "hobbies"},
    {"text": "not tracking anything and just vibing", "category": "hobbies"},
    {"text": "impulse buying things online at midnight", "category": "hobbies"},
    {"text": "researching every purchase for three weeks before buying", "category": "hobbies"},
    {"text": "returning things you bought", "category": "hobbies"},
    {"text": "never returning things (too much social anxiety)", "category": "hobbies"},
    {"text": "checking astrology charts seriously", "category": "hobbies"},
    {"text": "tarot card reading", "category": "hobbies"},
    {"text": "true crime podcasts as background noise", "category": "hobbies"},
    {"text": "self-help books (every single one)", "category": "hobbies"},
    {"text": "dismissing self-help entirely (just go to therapy)", "category": "hobbies"},
    {"text": "talking openly about being in therapy", "category": "hobbies"},
    {"text": "keeping a very clean car interior", "category": "hobbies"},
    {"text": "car that looks like a mobile garbage dump", "category": "hobbies"},

    # ── MUSIC ─────────────────────────────────────────────────────────────────
    {"text": "country music (the twangy, authentic kind)", "category": "music"},
    {"text": "modern country (pop country with cowboy hats)", "category": "music"},
    {"text": "heavy metal in general", "category": "music"},
    {"text": "death metal (guttural vocals as art form)", "category": "music"},
    {"text": "classical music as everyday listening", "category": "music"},
    {"text": "opera", "category": "music"},
    {"text": "jazz (either you get it or you don't)", "category": "music"},
    {"text": "smooth jazz (elevator or genius)", "category": "music"},
    {"text": "EDM and rave music", "category": "music"},
    {"text": "dubstep (the bass drop era)", "category": "music"},
    {"text": "K-pop", "category": "music"},
    {"text": "reggaeton", "category": "music"},
    {"text": "bluegrass", "category": "music"},
    {"text": "gospel music", "category": "music"},
    {"text": "emo music (the 2003-2008 era specifically)", "category": "music"},
    {"text": "screamo", "category": "music"},
    {"text": "lo-fi hip hop for studying", "category": "music"},
    {"text": "vaporwave", "category": "music"},
    {"text": "hyperpop (100 gecs, Charli XCX, that whole world)", "category": "music"},
    {"text": "folk music singer-songwriter stuff", "category": "music"},
    {"text": "indie music gatekeeping (you only like their popular stuff?)", "category": "music"},
    {"text": "musical theater songs in regular conversation", "category": "music"},
    {"text": "show tunes as a personality", "category": "music"},
    {"text": "disco", "category": "music"},
    {"text": "ska (everyone loves it then denies it)", "category": "music"},
    {"text": "polka", "category": "music"},
    {"text": "Nickelback (unironic appreciation)", "category": "music"},
    {"text": "Taylor Swift (Swifties vs. everyone else)", "category": "music"},
    {"text": "Kanye West (genius vs. spectacle vs. both)", "category": "music"},
    {"text": "Drake (talented or very corny)", "category": "music"},
    {"text": "Phish and jam band shows that go five hours", "category": "music"},
    {"text": "the Grateful Dead as a way of life", "category": "music"},
    {"text": "Bob Dylan (you have to really commit)", "category": "music"},
    {"text": "Celine Dion (unironically)", "category": "music"},
    {"text": "Creed (sincere appreciation)", "category": "music"},
    {"text": "Dave Matthews Band", "category": "music"},
    {"text": "Insane Clown Posse", "category": "music"},
    {"text": "Billie Eilish (the whisper-singing)", "category": "music"},
    {"text": "the Weeknd (dark, moody production)", "category": "music"},
    {"text": "Phoebe Bridgers (will make you cry)", "category": "music"},
    {"text": "Mitski (emotional devastation as a hobby)", "category": "music"},
    {"text": "ambient music (Brian Eno type stuff)", "category": "music"},
    {"text": "new age music (healing frequencies, singing bowls)", "category": "music"},
    {"text": "Gregorian chants", "category": "music"},
    {"text": "listening to music at full, probably too loud volume", "category": "music"},
    {"text": "listening to music at barely audible levels", "category": "music"},
    {"text": "having extremely niche music taste and needing people to know", "category": "music"},
    {"text": "only listening to one artist for months straight", "category": "music"},
    {"text": "needing music playing at all times", "category": "music"},

    # ── TV & MOVIES ───────────────────────────────────────────────────────────
    {"text": "reality TV (unironically invested)", "category": "media"},
    {"text": "the Bachelor franchise", "category": "media"},
    {"text": "soap operas", "category": "media"},
    {"text": "anime (art form vs. cringe)", "category": "media"},
    {"text": "horror movies", "category": "media"},
    {"text": "extremely slow, arthouse films", "category": "media"},
    {"text": "superhero movies (all of them, every one)", "category": "media"},
    {"text": "long fantasy epics", "category": "media"},
    {"text": "mockumentaries", "category": "media"},
    {"text": "true crime documentaries", "category": "media"},
    {"text": "Game of Thrones (complicated feelings about all of it)", "category": "media"},
    {"text": "The Office (British vs. American debate)", "category": "media"},
    {"text": "Friends (overrated or perfect)", "category": "media"},
    {"text": "Hallmark Christmas movies (unironically)", "category": "media"},
    {"text": "Lifetime movies (the melodrama)", "category": "media"},
    {"text": "WWE professional wrestling", "category": "media"},
    {"text": "infomercials at 3am", "category": "media"},
    {"text": "watching golf on television", "category": "media"},
    {"text": "watching movies with subtitles (even English ones)", "category": "media"},
    {"text": "talking during movies at home", "category": "media"},
    {"text": "complete silence during movies at home", "category": "media"},
    {"text": "watching a movie in multiple sittings", "category": "media"},
    {"text": "having the same movie on as background noise", "category": "media"},
    {"text": "rewatching movies you've seen 20 times", "category": "media"},
    {"text": "never rewatching anything, too much new content", "category": "media"},
    {"text": "falling asleep during movies and counting it as watched", "category": "media"},
    {"text": "pausing movies to discuss them extensively", "category": "media"},
    {"text": "watching things at 1.5x speed", "category": "media"},
    {"text": "buying physical DVDs and Blu-rays still", "category": "media"},
    {"text": "pirating things unashamedly", "category": "media"},

    # ── SOCIAL BEHAVIORS & QUIRKS ─────────────────────────────────────────────
    {"text": "talking to strangers everywhere you go", "category": "social"},
    {"text": "never making eye contact with strangers", "category": "social"},
    {"text": "smiling at strangers on the street", "category": "social"},
    {"text": "small talk with absolutely everyone", "category": "social"},
    {"text": "despising small talk and going deep immediately", "category": "social"},
    {"text": "leaving parties early without saying goodbye (the Irish exit)", "category": "social"},
    {"text": "being the last one to leave every party", "category": "social"},
    {"text": "hosting gatherings constantly", "category": "social"},
    {"text": "never hosting, always attending", "category": "social"},
    {"text": "being chronically early everywhere (15 minutes minimum)", "category": "social"},
    {"text": "being 10 minutes late to everything, always", "category": "social"},
    {"text": "forgetting you agreed to plans until 20 minutes before", "category": "social"},
    {"text": "canceling plans last minute via text", "category": "social"},
    {"text": "never canceling, always going even when you don't want to", "category": "social"},
    {"text": "ghosting (doing it and having it done to you)", "category": "social"},
    {"text": "sending voice messages instead of texts", "category": "social"},
    {"text": "calling people without texting first", "category": "social"},
    {"text": "refusing to call anyone, texts only", "category": "social"},
    {"text": "very long, detailed text messages (essays)", "category": "social"},
    {"text": "one-word text replies", "category": "social"},
    {"text": "using no punctuation in texts whatsoever", "category": "social"},
    {"text": "using full punctuation and grammar in all texts", "category": "social"},
    {"text": "ending every casual text with a period", "category": "social"},
    {"text": "LOL at the end of every single sentence", "category": "social"},
    {"text": "replying instantly to everything, always available", "category": "social"},
    {"text": "taking days to respond and seeing nothing wrong with it", "category": "social"},
    {"text": "leaving people on read and considering it neutral", "category": "social"},
    {"text": "read receipts on (transparency or anxiety-inducing)", "category": "social"},
    {"text": "emoji-heavy texting (three emojis per sentence)", "category": "social"},
    {"text": "zero emoji, pure text, always", "category": "social"},
    {"text": "double-texting when you don't hear back", "category": "social"},
    {"text": "oversharing on social media (every life update)", "category": "social"},
    {"text": "posting absolutely nothing on social media", "category": "social"},
    {"text": "LinkedIn inspirational posts (the hustle culture variety)", "category": "social"},
    {"text": "Twitter/X arguments with strangers", "category": "social"},
    {"text": "making your bed every single morning", "category": "social"},
    {"text": "never making your bed (I'm just going to get back in it)", "category": "social"},
    {"text": "organizing your fridge with labels", "category": "social"},
    {"text": "never looking at what's in the back of the fridge", "category": "social"},
    {"text": "keeping a very clean, minimal home", "category": "social"},
    {"text": "organized chaos home (looks messy but you know where everything is)", "category": "social"},
    {"text": "having plants everywhere and talking to them", "category": "social"},
    {"text": "having zero plants (can't keep them alive)", "category": "social"},
    {"text": "keeping the TV on even when not watching anything", "category": "social"},
    {"text": "not owning a TV at all", "category": "social"},
    {"text": "phones off during meals, strictly enforced", "category": "social"},
    {"text": "phone constantly at the table", "category": "social"},
    {"text": "checking your phone first thing in the morning", "category": "social"},
    {"text": "starting the day without touching your phone", "category": "social"},
    {"text": "taking extremely long showers", "category": "social"},
    {"text": "extremely quick showers (three minutes, done)", "category": "social"},
    {"text": "bathroom time as sacred alone time, extended edition", "category": "social"},

    # ── LIFESTYLE CHOICES ─────────────────────────────────────────────────────
    {"text": "being a morning person and needing everyone to know", "category": "lifestyle"},
    {"text": "being a night owl as a permanent state", "category": "lifestyle"},
    {"text": "working from home as a preference forever", "category": "lifestyle"},
    {"text": "needing to be in an office with people around", "category": "lifestyle"},
    {"text": "strict daily routines (same wake time, same breakfast, same everything)", "category": "lifestyle"},
    {"text": "zero routine, different every day, chaos preferred", "category": "lifestyle"},
    {"text": "living in a city (the noise, the energy)", "category": "lifestyle"},
    {"text": "living in the suburbs (by choice, not giving up)", "category": "lifestyle"},
    {"text": "living very rurally (intentionally isolated)", "category": "lifestyle"},
    {"text": "living alone and never wanting roommates again", "category": "lifestyle"},
    {"text": "having roommates as an adult (financial or social)", "category": "lifestyle"},
    {"text": "tiny homes (minimalism or poverty chic)", "category": "lifestyle"},
    {"text": "van life (freedom or glorified homelessness)", "category": "lifestyle"},
    {"text": "owning lots of stuff and being fine with it", "category": "lifestyle"},
    {"text": "minimalism (own fewer than 100 things)", "category": "lifestyle"},
    {"text": "thrifting everything, refusing to buy new", "category": "lifestyle"},
    {"text": "fast fashion with zero guilt", "category": "lifestyle"},
    {"text": "only buying designer, nothing else", "category": "lifestyle"},
    {"text": "wearing the same outfit repeatedly with no shame", "category": "lifestyle"},
    {"text": "never wearing the same outfit twice", "category": "lifestyle"},
    {"text": "wearing pajamas most of the day when home", "category": "lifestyle"},
    {"text": "getting fully dressed even when staying home all day", "category": "lifestyle"},
    {"text": "dressing up to go to the grocery store", "category": "lifestyle"},
    {"text": "grocery store in pajamas and slippers", "category": "lifestyle"},
    {"text": "smoking cigarettes (personal choice, everyone has opinions)", "category": "lifestyle"},
    {"text": "vaping", "category": "lifestyle"},
    {"text": "cannabis use as a regular thing", "category": "lifestyle"},
    {"text": "complete sobriety (by choice, not recovery)", "category": "lifestyle"},
    {"text": "drinking heavily on weekends, sober all week", "category": "lifestyle"},
    {"text": "staying in a job you hate for the benefits", "category": "lifestyle"},
    {"text": "quitting things that aren't working immediately", "category": "lifestyle"},
    {"text": "job-hopping every one to two years", "category": "lifestyle"},
    {"text": "staying at the same company for 15 years", "category": "lifestyle"},
    {"text": "work-life balance as non-negotiable", "category": "lifestyle"},
    {"text": "working constantly because you love it", "category": "lifestyle"},
    {"text": "being completely unreachable after work hours", "category": "lifestyle"},
    {"text": "answering emails at 11pm (just can't stop)", "category": "lifestyle"},
    {"text": "taking mental health days with no explanation needed", "category": "lifestyle"},
    {"text": "never taking sick days (martyrdom disguised as work ethic)", "category": "lifestyle"},
    {"text": "gym every day, no exceptions", "category": "lifestyle"},
    {"text": "never stepping foot in a gym", "category": "lifestyle"},
    {"text": "Peloton as a lifestyle choice", "category": "lifestyle"},
    {"text": "running outside in all weather conditions", "category": "lifestyle"},
    {"text": "hot yoga (90 minutes in 105-degree heat)", "category": "lifestyle"},
    {"text": "Pilates as your entire personality", "category": "lifestyle"},
    {"text": "tattoos visible in all situations", "category": "lifestyle"},
    {"text": "no tattoos, never, absolutely not", "category": "lifestyle"},
    {"text": "multiple facial piercings", "category": "lifestyle"},
    {"text": "face tattoos", "category": "lifestyle"},
    {"text": "owning a gun", "category": "lifestyle"},

    # ── ROMANTIC & INTIMATE ───────────────────────────────────────────────────
    {"text": "holding hands while walking everywhere", "category": "romantic"},
    {"text": "unexpected forehead kisses", "category": "romantic"},
    {"text": "having your hair played with while falling asleep", "category": "romantic"},
    {"text": "having your back scratched slowly", "category": "romantic"},
    {"text": "nose kisses", "category": "romantic"},
    {"text": "being picked up and carried", "category": "romantic"},
    {"text": "getting your ears nibbled", "category": "romantic"},
    {"text": "long, slow kisses that don't go anywhere", "category": "romantic"},
    {"text": "making out like teenagers, losing track of time completely", "category": "romantic"},
    {"text": "cuddling all night even though it gets too hot", "category": "romantic"},
    {"text": "being the little spoon specifically", "category": "romantic"},
    {"text": "being the big spoon specifically", "category": "romantic"},
    {"text": "falling asleep on someone's chest", "category": "romantic"},
    {"text": "having someone fall asleep on your chest", "category": "romantic"},
    {"text": "waking up to soft kisses on your face", "category": "romantic"},
    {"text": "good morning texts (the first thing every morning)", "category": "romantic"},
    {"text": "random 'I was thinking about you' texts mid-day", "category": "romantic"},
    {"text": "being cooked for (a full meal, just for you)", "category": "romantic"},
    {"text": "cooking together (the mess, the chaos, the fun)", "category": "romantic"},
    {"text": "hand-written love notes left in random places", "category": "romantic"},
    {"text": "being remembered exactly what you said you wanted weeks ago", "category": "romantic"},
    {"text": "slow dancing in the kitchen with no music", "category": "romantic"},
    {"text": "forehead touches (just resting foreheads together quietly)", "category": "romantic"},
    {"text": "having your face held while being kissed", "category": "romantic"},
    {"text": "playful biting (shoulder, neck, nothing alarming)", "category": "romantic"},
    {"text": "neck kisses specifically", "category": "romantic"},
    {"text": "kissing someone's shoulder blade", "category": "romantic"},
    {"text": "tracing patterns on someone's arm while watching TV", "category": "romantic"},
    {"text": "having someone play with your fingers absentmindedly", "category": "romantic"},
    {"text": "eye contact held just a beat too long", "category": "romantic"},
    {"text": "being stared at across a crowded room", "category": "romantic"},
    {"text": "things whispered directly into your ear", "category": "romantic"},
    {"text": "someone's hand on the small of your back", "category": "romantic"},
    {"text": "a hand on your knee when driving", "category": "romantic"},
    {"text": "sleeping in someone's oversized sweatshirt", "category": "romantic"},
    {"text": "stealing someone's jacket and keeping it indefinitely", "category": "romantic"},
    {"text": "someone brushing hair out of your face", "category": "romantic"},
    {"text": "being called by a nickname only they use for you", "category": "romantic"},
    {"text": "inside jokes that no one else would understand", "category": "romantic"},
    {"text": "doing absolutely nothing together but feeling completely full", "category": "romantic"},
    {"text": "comfortable silences (no need to fill every moment)", "category": "romantic"},
    {"text": "staying up all night just talking", "category": "romantic"},
    {"text": "falling asleep on the phone together", "category": "romantic"},
    {"text": "long goodbye kisses that keep restarting", "category": "romantic"},
    {"text": "someone noticing when you get a haircut", "category": "romantic"},
    {"text": "someone remembering your coffee order perfectly", "category": "romantic"},
    {"text": "being greeted with genuine excitement when you come home", "category": "romantic"},
    {"text": "the first moment of eye contact after time apart", "category": "romantic"},
    {"text": "skinny dipping together", "category": "romantic"},
    {"text": "taking baths together", "category": "romantic"},
    {"text": "the moment right before a first kiss when you both know it's coming", "category": "romantic"},
    {"text": "weeks of tension before anything happens (slow burn)", "category": "romantic"},
    {"text": "being pinned against a wall (in the fun way)", "category": "romantic"},
    {"text": "someone running their fingers through your hair", "category": "romantic"},
    {"text": "having your temples rubbed when you have a headache", "category": "romantic"},
    {"text": "foot massages given without being asked", "category": "romantic"},
    {"text": "full back massages that go on longer than expected", "category": "romantic"},
    {"text": "someone drawing letters on your back with their finger while you guess", "category": "romantic"},
    {"text": "surprise dates (get dressed, we're going somewhere)", "category": "romantic"},
    {"text": "being looked at like you're the most interesting person in the room", "category": "romantic"},
    {"text": "public displays of affection (full commitment, no shame)", "category": "romantic"},
    {"text": "absolutely no PDA (private people, private love)", "category": "romantic"},
    {"text": "sharing a bed and waking up tangled together", "category": "romantic"},
    {"text": "someone fixing your collar or adjusting your necklace without being asked", "category": "romantic"},
    {"text": "fingers interlocked, not just held (woven together)", "category": "romantic"},
    {"text": "being called baby or honey in a natural, unforced way", "category": "romantic"},
    {"text": "being told you smell good with no agenda attached", "category": "romantic"},
    {"text": "someone pressing their cold feet against you as an act of aggression", "category": "romantic"},
    {"text": "playful arguing that ends in laughter", "category": "romantic"},
    {"text": "being teased lovingly by someone who knows all your soft spots", "category": "romantic"},
    {"text": "laughing so hard together you can't breathe", "category": "romantic"},
    {"text": "the look partners exchange across a room that says everything", "category": "romantic"},
    {"text": "someone defending you without being asked to", "category": "romantic"},
    {"text": "being pulled back into bed when you try to get up", "category": "romantic"},
    {"text": "the weight of someone's arm around you while sleeping", "category": "romantic"},
    {"text": "cheek kisses as a hello", "category": "romantic"},
    {"text": "kissing someone's knuckles", "category": "romantic"},
    {"text": "being dipped during a dance", "category": "romantic"},
    {"text": "the moment someone says your name while making eye contact", "category": "romantic"},
    {"text": "being kissed in the rain", "category": "romantic"},
    {"text": "having someone's full, undivided attention", "category": "romantic"},
    {"text": "someone reading to you out loud from a book", "category": "romantic"},
    {"text": "sharing earbuds and listening to a song together", "category": "romantic"},
    {"text": "being remembered in a specific detail no one else noticed", "category": "romantic"},
    {"text": "someone seeing through your social face to the real one", "category": "romantic"},
    {"text": "the first time someone reaches for your hand", "category": "romantic"},
    {"text": "being held from behind while standing somewhere", "category": "romantic"},
    {"text": "someone resting their chin on your head", "category": "romantic"},
    {"text": "the feeling of someone's heartbeat under your ear", "category": "romantic"},
    {"text": "falling asleep while someone strokes your hair", "category": "romantic"},
    {"text": "waking up before your partner and just watching them sleep", "category": "romantic"},
    {"text": "someone knowing your order before you have to say it", "category": "romantic"},
    {"text": "being called beautiful when you didn't try at all", "category": "romantic"},
    {"text": "surprise physical contact (hand squeeze, random hug from behind)", "category": "romantic"},
    {"text": "being the one who texts first every time (the vulnerability of it)", "category": "romantic"},
    {"text": "being with someone who laughs at the same things", "category": "romantic"},
    {"text": "when someone's laugh makes you laugh before the joke even lands", "category": "romantic"},
    {"text": "having someone trace your features with their finger", "category": "romantic"},
    {"text": "very slow, intentional touch", "category": "romantic"},
    {"text": "quick, casual, habitual affection (kiss on the cheek passing by)", "category": "romantic"},
    {"text": "being chosen (over other things, other people)", "category": "romantic"},
    {"text": "the excitement of seeing someone's name appear on your phone", "category": "romantic"},
    {"text": "when someone's voice drops lower when talking only to you", "category": "romantic"},
    {"text": "someone learning your preferences without being asked", "category": "romantic"},
    {"text": "catching someone smiling at their phone because of you", "category": "romantic"},
    {"text": "being someone's first call with news (good or bad)", "category": "romantic"},
    {"text": "sleeping in and staying in bed all morning together", "category": "romantic"},
    {"text": "reading in bed together in comfortable silence", "category": "romantic"},
    {"text": "being pulled close in sleep without them waking up", "category": "romantic"},
    {"text": "long car rides where you talk about everything", "category": "romantic"},
    {"text": "being told something they've never told anyone else", "category": "romantic"},
    {"text": "someone who makes you feel completely calm", "category": "romantic"},
    {"text": "someone who gives you that specific nervous energy", "category": "romantic"},
    {"text": "being kissed on the top of the head", "category": "romantic"},
    {"text": "someone holding the back of your neck softly", "category": "romantic"},
    {"text": "being carried to bed when you fell asleep on the couch", "category": "romantic"},
    {"text": "being covered with a blanket when you fell asleep somewhere", "category": "romantic"},
    {"text": "someone turning off your light when you fell asleep reading", "category": "romantic"},
    {"text": "being held while crying, no words", "category": "romantic"},
    {"text": "the intimacy of brushing your teeth at the same time", "category": "romantic"},
    {"text": "sharing a mirror getting ready in the morning", "category": "romantic"},
    {"text": "always kissing before sleeping, without fail", "category": "romantic"},
    {"text": "the safety of being completely known by one person", "category": "romantic"},
    {"text": "when they remember the name of a person in a story you told once", "category": "romantic"},
    {"text": "someone who thinks your flaws are endearing", "category": "romantic"},

    # ── PERSONALITY TRAITS ────────────────────────────────────────────────────
    {"text": "being very loud and taking up a lot of space", "category": "personality"},
    {"text": "being extremely quiet and hard to read", "category": "personality"},
    {"text": "interrupting people with excitement (not rudeness, just passion)", "category": "personality"},
    {"text": "finishing other people's sentences", "category": "personality"},
    {"text": "giving unsolicited advice constantly", "category": "personality"},
    {"text": "never giving advice unless explicitly asked", "category": "personality"},
    {"text": "being brutally honest when asked for opinions", "category": "personality"},
    {"text": "saying it's great about everything to avoid conflict", "category": "personality"},
    {"text": "chronic optimism (everything is going to be fine!)", "category": "personality"},
    {"text": "realistic pessimism (I just plan for the worst)", "category": "personality"},
    {"text": "sarcasm as a primary language", "category": "personality"},
    {"text": "dry humor so dry people aren't sure if you're joking", "category": "personality"},
    {"text": "dad jokes, relentlessly", "category": "personality"},
    {"text": "dark humor about heavy things", "category": "personality"},
    {"text": "self-deprecating humor", "category": "personality"},
    {"text": "people who narrate what they're doing out loud", "category": "personality"},
    {"text": "people who talk to themselves and don't hide it", "category": "personality"},
    {"text": "naming your car", "category": "personality"},
    {"text": "naming all your plants and talking to them", "category": "personality"},
    {"text": "being best friends with all your exes", "category": "personality"},
    {"text": "having zero contact with any ex", "category": "personality"},
    {"text": "going through life phases intensely (fixation of the month)", "category": "personality"},
    {"text": "being consistently the same, no phases", "category": "personality"},
    {"text": "needing to research absolutely everything before deciding anything", "category": "personality"},
    {"text": "making decisions purely on instinct, immediately", "category": "personality"},
    {"text": "being sentimental about everything (keeping every ticket stub)", "category": "personality"},
    {"text": "not attaching to objects at all, throwing things out freely", "category": "personality"},
    {"text": "being very publicly emotional (crying at commercials)", "category": "personality"},
    {"text": "never crying in public, ever", "category": "personality"},
    {"text": "oversharing with strangers (whole life story on the plane)", "category": "personality"},
    {"text": "telling strangers nothing, classic 'I'm fine, thanks'", "category": "personality"},
    {"text": "being the person who remembers everyone's birthdays", "category": "personality"},
    {"text": "never remembering birthdays, not even your own", "category": "personality"},
    {"text": "sending physical birthday cards in the mail", "category": "personality"},
    {"text": "being extremely competitive about board games", "category": "personality"},
    {"text": "playing games just for fun, winning doesn't matter at all", "category": "personality"},
    {"text": "being very structured and needing a plan", "category": "personality"},
    {"text": "being extremely flexible and going with the flow", "category": "personality"},
    {"text": "always bringing snacks to share", "category": "personality"},
    {"text": "never sharing food, not even one bite", "category": "personality"},
    {"text": "people who hum or sing to themselves quietly", "category": "personality"},
    {"text": "people who cry at dog adoption videos", "category": "personality"},
    {"text": "defending your hometown no matter how bad it is", "category": "personality"},
    {"text": "talking badly about your hometown to anyone who'll listen", "category": "personality"},
    {"text": "people who wave thank you when you let them merge", "category": "personality"},
    {"text": "dressing up their pets in outfits", "category": "personality"},
    {"text": "people who dye their hair wild colors", "category": "personality"},
    {"text": "people who have had the same haircut since high school", "category": "personality"},

    # ── OUTDOORS & NATURE ─────────────────────────────────────────────────────
    {"text": "swimming in lakes and rivers (whatever is in there is probably fine)", "category": "outdoors"},
    {"text": "only swimming in pools (chlorine or nothing)", "category": "outdoors"},
    {"text": "going to the beach and sitting in the sun all day", "category": "outdoors"},
    {"text": "going to the beach and sitting in the shade with a book", "category": "outdoors"},
    {"text": "mountains over beaches, always", "category": "outdoors"},
    {"text": "beaches over mountains, always", "category": "outdoors"},
    {"text": "desert landscapes (sparse, harsh, beautiful)", "category": "outdoors"},
    {"text": "forests so dense you can't see the sky", "category": "outdoors"},
    {"text": "being caught in rain without an umbrella and deciding to commit to it", "category": "outdoors"},
    {"text": "extreme weather (tornadoes, blizzards) as exciting", "category": "outdoors"},
    {"text": "snow and winter as something to look forward to", "category": "outdoors"},
    {"text": "hating winter profoundly and personally", "category": "outdoors"},
    {"text": "walking barefoot in grass", "category": "outdoors"},
    {"text": "walking barefoot on hot sand and kind of liking the burn", "category": "outdoors"},
    {"text": "thunderstorms that shake the house", "category": "outdoors"},
    {"text": "quiet snowfall where the whole world goes silent", "category": "outdoors"},
    {"text": "the ocean at night (peaceful or terrifying)", "category": "outdoors"},
    {"text": "swimming in deep water where you can't see the bottom", "category": "outdoors"},
    {"text": "finding insects interesting and picking them up", "category": "outdoors"},
    {"text": "running from all insects regardless of size", "category": "outdoors"},
    {"text": "watching sunsets from a specific spot regularly", "category": "outdoors"},
    {"text": "getting up specifically for sunrises", "category": "outdoors"},
    {"text": "night hiking (headlamps, total darkness, questionable choices)", "category": "outdoors"},
    {"text": "the smell of campfire smoke in your hair the next day", "category": "outdoors"},
    {"text": "sleeping outside in a hammock", "category": "outdoors"},
    {"text": "being cold at night and loving it under a heavy blanket", "category": "outdoors"},

    # ── SPORTS & FITNESS ──────────────────────────────────────────────────────
    {"text": "running just for fun with no race involved", "category": "sports"},
    {"text": "lifting weights in silence for two hours", "category": "sports"},
    {"text": "CrossFit (the community is half the point)", "category": "sports"},
    {"text": "hot yoga (Bikram, the really sweaty kind)", "category": "sports"},
    {"text": "swimming laps as a meditative practice", "category": "sports"},
    {"text": "cycling on roads with a very specific outfit", "category": "sports"},
    {"text": "mountain biking (the crashing is part of it)", "category": "sports"},
    {"text": "rock climbing (indoor or the real thing)", "category": "sports"},
    {"text": "martial arts for self-improvement", "category": "sports"},
    {"text": "boxing as therapy", "category": "sports"},
    {"text": "golf (the pace, the quiet, the outfits)", "category": "sports"},
    {"text": "tennis", "category": "sports"},
    {"text": "pickleball (everyone eventually converts)", "category": "sports"},
    {"text": "bowling unironically", "category": "sports"},
    {"text": "archery", "category": "sports"},
    {"text": "American football (watching, not playing)", "category": "sports"},
    {"text": "soccer (the rest of the world is right)", "category": "sports"},
    {"text": "baseball (the pace is meditative, not boring)", "category": "sports"},
    {"text": "hockey", "category": "sports"},
    {"text": "MMA and UFC", "category": "sports"},
    {"text": "competitive eating", "category": "sports"},
    {"text": "obstacle course races (Tough Mudder, Spartan)", "category": "sports"},
    {"text": "running a marathon for a charity", "category": "sports"},
    {"text": "tracking every athletic metric obsessively", "category": "sports"},

    # ── TECHNOLOGY & MEDIA HABITS ─────────────────────────────────────────────
    {"text": "checking email first thing in the morning", "category": "tech"},
    {"text": "zero social media presence, completely offline", "category": "tech"},
    {"text": "being extremely chronically online", "category": "tech"},
    {"text": "still buying physical CDs and records", "category": "tech"},
    {"text": "streaming everything, owning nothing", "category": "tech"},
    {"text": "rotating streaming services to save money", "category": "tech"},
    {"text": "phone-free weeks with no anxiety", "category": "tech"},
    {"text": "needing your phone near you at all times", "category": "tech"},
    {"text": "smart home devices everywhere (Alexa, etc.)", "category": "tech"},
    {"text": "refusing all smart devices on principle", "category": "tech"},
    {"text": "print newspapers specifically", "category": "tech"},
    {"text": "never reading news intentionally", "category": "tech"},
    {"text": "reading everything and doom-spiraling about the world", "category": "tech"},
    {"text": "reading on your phone in bed until 2am", "category": "tech"},
    {"text": "paper books only, no exceptions", "category": "tech"},
    {"text": "audiobooks while doing other things", "category": "tech"},
    {"text": "podcasts for every activity (cooking, gym, commute)", "category": "tech"},
    {"text": "complete silence during all activities", "category": "tech"},
    {"text": "being very online about niche topics (extremely specific forums)", "category": "tech"},
    {"text": "using Reddit for years and never posting once", "category": "tech"},
    {"text": "muting all group chats immediately", "category": "tech"},
    {"text": "setting up elaborate phone notification systems", "category": "tech"},
    {"text": "no notifications from anything", "category": "tech"},
    {"text": "taking your phone to the bathroom every single time", "category": "tech"},
    {"text": "leaving your phone in another room for hours", "category": "tech"},
    {"text": "reading the comments section on purpose", "category": "tech"},
    {"text": "strict no-comments-section policy", "category": "tech"},
    {"text": "watching things at 1.5x speed and being smug about it", "category": "tech"},

    # ── QUIRKY SPECIFIC THINGS ────────────────────────────────────────────────
    {"text": "very long baths with books and candles", "category": "quirky"},
    {"text": "solving problems in the shower (best ideas come there)", "category": "quirky"},
    {"text": "letting voicemails pile up for weeks before listening", "category": "quirky"},
    {"text": "replying to voicemails with a text", "category": "quirky"},
    {"text": "the specific satisfaction of finishing a pen", "category": "quirky"},
    {"text": "never finishing a pen before losing it", "category": "quirky"},
    {"text": "folding fitted sheets correctly (either you can or you can't)", "category": "quirky"},
    {"text": "bundling fitted sheets into a ball and hiding them in the closet", "category": "quirky"},
    {"text": "alphabetizing your bookshelf", "category": "quirky"},
    {"text": "organizing bookshelves by color", "category": "quirky"},
    {"text": "total bookshelf organization chaos", "category": "quirky"},
    {"text": "rearranging furniture at random intervals", "category": "quirky"},
    {"text": "never moving any furniture, ever", "category": "quirky"},
    {"text": "keeping movie ticket stubs, receipts, and small papers", "category": "quirky"},
    {"text": "throwing everything away immediately", "category": "quirky"},
    {"text": "people who laugh at their own jokes before finishing them", "category": "quirky"},
    {"text": "people who tell very long stories with no discernible point", "category": "quirky"},
    {"text": "people who get to the point immediately, no preamble", "category": "quirky"},
    {"text": "when someone hiccups and cannot stop", "category": "quirky"},
    {"text": "when someone has a very specific, distinctive laugh", "category": "quirky"},
    {"text": "when people mispronounce a word consistently and confidently", "category": "quirky"},
    {"text": "correcting people's pronunciation (villain behavior or helpful?)", "category": "quirky"},
    {"text": "grammar corrections in casual conversation", "category": "quirky"},
    {"text": "using very obscure words casually in conversation", "category": "quirky"},
    {"text": "using made-up words that just feel right", "category": "quirky"},
    {"text": "the urge to fix a crooked painting on someone else's wall", "category": "quirky"},
    {"text": "having to touch all the textures at a store", "category": "quirky"},
    {"text": "counting things without realizing you're doing it", "category": "quirky"},
    {"text": "that feeling when you use a really good pen", "category": "quirky"},
    {"text": "keeping notebooks but rarely writing in them", "category": "quirky"},
    {"text": "filling every page of a notebook before starting a new one", "category": "quirky"},
    {"text": "loving the ritual of making coffee more than drinking it", "category": "quirky"},
    {"text": "wearing socks to bed", "category": "quirky"},
    {"text": "being unable to sleep with socks on", "category": "quirky"},
    {"text": "sleeping with one foot outside the blanket", "category": "quirky"},
    {"text": "full mummy-wrap blanket cocoon sleeping", "category": "quirky"},
    {"text": "sleeping absolutely flat on your back", "category": "quirky"},
    {"text": "sleeping in an absurd diagonal position taking up the whole bed", "category": "quirky"},
    {"text": "napping for exactly 20 minutes and waking up refreshed", "category": "quirky"},
    {"text": "napping for two hours and waking up confused about what year it is", "category": "quirky"},
    {"text": "remembering dreams in detail every morning", "category": "quirky"},
    {"text": "recurring dreams (spending real time figuring out what they mean)", "category": "quirky"},
    {"text": "needing total darkness to sleep", "category": "quirky"},
    {"text": "falling asleep with the light on, no problem", "category": "quirky"},
    {"text": "needing all doors and closets completely closed at night", "category": "quirky"},
    {"text": "leaving doors and closets open at night (the bravery)", "category": "quirky"},
    {"text": "the satisfaction of parallel parking on the first try", "category": "quirky"},
    {"text": "driving in complete silence with no music", "category": "quirky"},
    {"text": "driving with music at full volume, windows down", "category": "quirky"},
    {"text": "arguing with GPS directions out loud", "category": "quirky"},
    {"text": "running the gas tank until it's truly, dangerously empty", "category": "quirky"},
    {"text": "filling the tank at half every time (anxiety management)", "category": "quirky"},
    {"text": "finding money in an old jacket pocket", "category": "quirky"},
    {"text": "the specific satisfaction of using the last of something", "category": "quirky"},
    {"text": "wearing your favorite clothes until they completely fall apart", "category": "quirky"},
    {"text": "getting rid of something the moment it shows any wear", "category": "quirky"},

    # ── BELIEFS & WORLDVIEW ───────────────────────────────────────────────────
    {"text": "conspiracy theories as entertainment (Flat Earth, etc.)", "category": "beliefs"},
    {"text": "astrology as a real system for understanding people", "category": "beliefs"},
    {"text": "astrology people who judge you for not knowing your rising sign", "category": "beliefs"},
    {"text": "horoscopes as fun, not serious", "category": "beliefs"},
    {"text": "crystals for healing energy", "category": "beliefs"},
    {"text": "essential oils as medicine", "category": "beliefs"},
    {"text": "reiki and energy healing", "category": "beliefs"},
    {"text": "tarot as genuine guidance", "category": "beliefs"},
    {"text": "psychics and mediums", "category": "beliefs"},
    {"text": "religious faith as central to your entire life", "category": "beliefs"},
    {"text": "complete atheism with opinions about it", "category": "beliefs"},
    {"text": "agnosticism (perfectly comfortable not knowing)", "category": "beliefs"},
    {"text": "spiritual but not religious (a whole category unto itself)", "category": "beliefs"},
    {"text": "believing in ghosts because you've seen things", "category": "beliefs"},
    {"text": "not believing in anything supernatural, full stop", "category": "beliefs"},
    {"text": "the multiverse as something you think about daily", "category": "beliefs"},
    {"text": "the feeling that this is probably all there is, and being fine with that", "category": "beliefs"},
    {"text": "people who make bucket lists and actually complete them", "category": "beliefs"},
    {"text": "getting matching tattoos with someone", "category": "beliefs"},
    {"text": "sending flowers for no reason", "category": "beliefs"},
    {"text": "finding flowers excessive (just say it with words)", "category": "beliefs"},
    {"text": "grand romantic gestures (airport scenes, boomboxes, etc.)", "category": "beliefs"},
    {"text": "very private, quiet love that no one else sees", "category": "beliefs"},

    # ── MISCELLANEOUS ─────────────────────────────────────────────────────────
    {"text": "the specific satisfaction of a really clean house", "category": "misc"},
    {"text": "the specific satisfaction of a perfectly messy desk", "category": "misc"},
    {"text": "eating breakfast food at every meal if given the choice", "category": "misc"},
    {"text": "people who put their shopping cart back in the corral", "category": "misc"},
    {"text": "people who abandon their cart in the middle of the lot", "category": "misc"},
    {"text": "people who are aggressively cheerful in the morning", "category": "misc"},
    {"text": "people who need silence until noon minimum", "category": "misc"},
    {"text": "when someone remembers how you take your coffee", "category": "misc"},
    {"text": "very meaningful gifts that required real thought", "category": "misc"},
    {"text": "practical gifts (gift cards, money, useful things)", "category": "misc"},
    {"text": "over-the-top gift wrapping", "category": "misc"},
    {"text": "a gift in a crumpled paper bag (the chaos)", "category": "misc"},
    {"text": "always being the loudest one in the group", "category": "misc"},
    {"text": "always being the quietest one in the group", "category": "misc"},
    {"text": "people who carry snacks for other people", "category": "misc"},
    {"text": "people who make friends with every dog they encounter", "category": "misc"},
    {"text": "people who are afraid of dogs (valid but alienating)", "category": "misc"},
    {"text": "people who ask 'are you okay?' when you're clearly not okay", "category": "misc"},
    {"text": "people who sense something's wrong without you saying anything", "category": "misc"},
    {"text": "people who give very long hugs", "category": "misc"},
    {"text": "people who give very brief, pat-on-the-back hugs", "category": "misc"},
    {"text": "people who are perpetually cold and always stealing warmth from others", "category": "misc"},
    {"text": "people who run hot and are basically a human radiator", "category": "misc"},
    {"text": "people who fall asleep instantly anywhere", "category": "misc"},
    {"text": "people who lie awake for hours thinking about things they said in 2011", "category": "misc"},
    {"text": "very long voicemails (the whole update)", "category": "misc"},
    {"text": "people who will stand in the rain to finish a conversation", "category": "misc"},
    {"text": "people who hate being late so much it's almost a disorder", "category": "misc"},
    {"text": "people who cry at the national anthem", "category": "misc"},
    {"text": "people who are moved by absolutely nothing", "category": "misc"},
    {"text": "people who are moved by absolutely everything", "category": "misc"},
    {"text": "being absolutely addicted to chapstick", "category": "misc"},
    {"text": "collecting one specific thing obsessively (mugs, magnets, shot glasses)", "category": "misc"},
    {"text": "never collecting anything (clutter gives me anxiety)", "category": "misc"},
    {"text": "keeping a gratitude journal", "category": "misc"},
    {"text": "finding gratitude journaling insufferable", "category": "misc"},
    {"text": "people who bring their dog everywhere possible", "category": "misc"},
    {"text": "people who co-sleep with their pets", "category": "misc"},
    {"text": "people who won't let animals on the furniture", "category": "misc"},
    {"text": "being very loud at live sports events", "category": "misc"},
    {"text": "sitting silently at live sports events", "category": "misc"},
    {"text": "knowing every word to every song at a concert", "category": "misc"},
    {"text": "leaving concerts before the encore", "category": "misc"},
    {"text": "staying for the entire encore plus the lights-up cleanup", "category": "misc"},
    {"text": "people who clap after airplane landings", "category": "misc"},
    {"text": "people who are horrified by airplane clappers", "category": "misc"},
    {"text": "people who make small talk with their Uber drivers", "category": "misc"},
    {"text": "people who put headphones in the moment they get in the Uber", "category": "misc"},
    {"text": "the window seat, always, non-negotiable", "category": "misc"},
    {"text": "the aisle seat (easy exit, authority)", "category": "misc"},
    {"text": "people who recline their airplane seat fully", "category": "misc"},
    {"text": "people who refuse to recline on principle", "category": "misc"},
    {"text": "wearing noise-canceling headphones in public places", "category": "misc"},
    {"text": "never wearing headphones anywhere (absorbing ambient sound)", "category": "misc"},
    {"text": "re-reading the same books every few years", "category": "misc"},
    {"text": "strong feelings about the Oxford comma", "category": "misc"},
    {"text": "putting ketchup in the refrigerator", "category": "misc"},
    {"text": "leaving ketchup in the cabinet", "category": "misc"},
    {"text": "the toilet paper over vs. under debate (strong feelings)", "category": "misc"},
    {"text": "squeezing the toothpaste from the middle", "category": "misc"},
    {"text": "squeezing from the bottom and rolling it up neatly", "category": "misc"},
    {"text": "leaving cabinet doors open", "category": "misc"},
    {"text": "needing all cabinet doors completely closed at all times", "category": "misc"},
    {"text": "the kind of person who can't start working until everything is clean", "category": "misc"},
    {"text": "the kind of person who works best surrounded by organized chaos", "category": "misc"},
    {"text": "being able to fall asleep anywhere, anytime", "category": "misc"},
    {"text": "needing very specific conditions to sleep", "category": "misc"},
    {"text": "people who apologize too much", "category": "misc"},
    {"text": "people who never apologize", "category": "misc"},
    {"text": "people who remember every song lyric perfectly", "category": "misc"},
    {"text": "people who make up their own lyrics confidently and incorrectly", "category": "misc"},
    {"text": "being the kind of person who checks in on people out of nowhere", "category": "misc"},
    {"text": "being the kind of person who needs to be checked on", "category": "misc"},
    {"text": "people who always find a way to bring it back to themselves", "category": "misc"},
    {"text": "people who deflect every compliment", "category": "misc"},
    {"text": "people who receive compliments gracefully", "category": "misc"},
    {"text": "being the friend who shows up with food when something's wrong", "category": "misc"},
    {"text": "being the friend who shows up with a plan when something's wrong", "category": "misc"},
    {"text": "the smell of someone's specific soap or deodorant", "category": "misc"},
    {"text": "the sound of someone you love breathing when they're asleep", "category": "misc"},
    {"text": "the particular silence of being with someone and not needing to say anything", "category": "misc"},
]
